#!/usr/bin/php
<?php

declare(strict_types=1);


declare(strict_types=1);

use Phoundation\Business\Providers\Provider;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/business/providers/create
 *
 * This script will create a new provider with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho system business providers create NAME [OPTIONS]
./cli system business providers create test -d "This is a test provider!"');

Documentation::help('This script allows you to create providers



ARGUMENTS



NAME                                    The name for the provider

[-d / --description]                    The description for the provider');



// Validate arguments
$argv = ArgvValidator::new()
    ->select('name', true)->isName()
    ->select('-d,--description', true)->isOptional(null)->isDescription()
    ->select('-r,--rights,--right', true)->isOptional(null)->sanitizeForceArray()->each()->isName()
    ->noArgumentsLeft()
    ->validate();



// Check if the provider already exists
Provider::notExists($argv['name'], null, true);



// Ensure that specified providers exist
if ($argv['rights']) {
    foreach ($argv['rights'] as &$right) {
        $right = Provider::get($right);
    }

    unset($right);
}



// Create provider and save it
$provider = Provider::new()->create($argv)->save();



// Done!
Log::success(tr('Created new provider ":provider"', [':provider' => $provider->getName()]));