#!/usr/bin/php
<?php

use Phoundation\Business\Companies\Company;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/business/companies/create
 *
 * This script will create a new company with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./cli system business companies create NAME [OPTIONS]
./cli system business companies create test -d "This is a test company!"');

Documentation::help('This script allows you to create companies



ARGUMENTS (All arguments in square brackets are optional)



NAME                                    The name for the company

[-d / --description]                    The description for the company');



// Validate arguments
ArgvValidator::new()
    ->select('name', true)->isName()
    ->select('-d,--description', true)->isOptional(null)->isDescription()
    ->select('-r,--rights,--right', true)->isOptional(null)->sanitizeForceArray()->each()->isName()
    ->noArgumentsLeft()
    ->validate();



// Check if the company already exists
Company::notExists($argv['name'], null, true);



// Ensure that specified companies exist
if ($argv['rights']) {
    foreach ($argv['rights'] as &$right) {
        $right = Company::get($right);
    }

    unset($right);
}



// Create company and save it
$company = Company::new()->create($argv)->save();



// Done!
Log::success(tr('Created new company ":company"', [':company' => $company->getName()]));