<?php

/**
 * SshAccount class
 *
 * This DataEntry type class represents a single entry in the ssh_accounts table.
 *
 * This DataEntry class supports configuration loading from the path "ssh.accounts"
 *
 * Upon loading a new entry, if the column "file" is specified, but the "ssh_key" column is empty, the class will
 * automatically inject the contents of said file into the column "ssh_key"
 *
 * @see       DataEntry
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2024 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Servers
 */

declare(strict_types=1);

namespace Phoundation\Servers;

use Phoundation\Data\DataEntry\DataEntry;
use Phoundation\Data\DataEntry\Definitions\Definition;
use Phoundation\Data\DataEntry\Definitions\DefinitionFactory;
use Phoundation\Data\DataEntry\Definitions\Interfaces\DefinitionsInterface;
use Phoundation\Data\DataEntry\Interfaces\DataEntryInterface;
use Phoundation\Data\DataEntry\Traits\TraitDataEntryFile;
use Phoundation\Data\DataEntry\Traits\TraitDataEntryNameDescription;
use Phoundation\Data\DataEntry\Traits\TraitDataEntryUsername;
use Phoundation\Data\Validator\Interfaces\ValidatorInterface;
use Phoundation\Data\Traits\TraitDataRestrictions;
use Phoundation\Filesystem\FsDirectory;
use Phoundation\Filesystem\FsFile;
use Phoundation\Filesystem\FsRestrictions;
use Phoundation\Servers\Interfaces\SshAccountInterface;
use Phoundation\Web\Html\Enums\EnumInputType;

class SshAccount extends DataEntry implements SshAccountInterface
{
    use TraitDataRestrictions;
    use TraitDataEntryNameDescription;
    use TraitDataEntryUsername;
    use TraitDataEntryFile;


    /**
     * SshAccount class constructor
     *
     * @param DataEntryInterface|string|int|null $identifier
     * @param string|null                        $column
     * @param bool|null                          $meta_enabled
     * @param bool                               $init
     */
    public function __construct(DataEntryInterface|string|int|null $identifier = null, ?string $column = null, ?bool $meta_enabled = null, bool $init = true)
    {
        $this->configuration_path = 'ssh.accounts';
        $this->restrictions       = FsRestrictions::getFilesystemRoot();

        parent::__construct($identifier, $column, $meta_enabled, $init);
    }


    /**
     * Returns the table name used by this object
     *
     * @return string|null
     */
    public static function getTable(): ?string
    {
        return 'ssh_accounts';
    }


    /**
     * Returns the name of this DataEntry class
     *
     * @return string
     */
    public static function getDataEntryName(): string
    {
        return tr('SSH account');
    }


    /**
     * Returns a unique log identifier that is both unique but also human readable
     *
     * @return string
     */
    public function getLogId(): string
    {
        return $this->getTypesafe('int', 'id') . ' / ' . (static::getUniqueColumn() ? $this->getTypesafe('string', static::getUniqueColumn()) : '-') . '(' . $this->getUsername() . ')';
    }


    /**
     * Returns the field that is unique for this object
     *
     * @return string|null
     */
    public static function getUniqueColumn(): ?string
    {
        return 'name';
    }


    /**
     * Returns the ssh_key for this object
     *
     * @return string|null
     */
    public function getSshKey(): ?string
    {
        return $this->getTypesafe('string', 'ssh_key');
    }


    /**
     * Sets the ssh_key for this object
     *
     * @param string|null $ssh_key
     *
     * @return static
     */
    public function setSshKey(?string $ssh_key): static
    {
        return $this->set($ssh_key, 'ssh_key');
    }


    /**
     * Copies all specified source entries to the internal source and ensures "ssk_key" is loaded if "file" is specified
     *
     * @param array $source
     * @param bool $modify
     * @param bool $directly
     * @param bool $force
     * @return static
     */
    protected function copyValuesToSource(array $source, bool $modify, bool $directly = false, bool $force = false): static
    {
        parent::copyValuesToSource($source, $modify, $directly, $force); // TODO: Change the autogenerated stub

        if (!$this->isNew()) {
            // If any of the accounts have the "file" key, replace that key with ssh_key value
            if (empty($this->source['name'])) {
                // No name always default to username
                $this->source['name'] = $this->source['username'];
            }

            if (array_key_exists('file', $this->source)) {
                if ($this->source['file']) {
                    $this->source['ssh_key'] = FsFile::new($this->source['file'], FsRestrictions::getFilesystemRoot())->getContentsAsString();
                }
            }
        }

        return $this;
    }


    /**
     * Sets the available data keys for this entry
     *
     * @param DefinitionsInterface $definitions
     */
    protected function setDefinitions(DefinitionsInterface $definitions): void
    {
        $definitions->add(DefinitionFactory::getName($this)
                                           ->setSize(6)
                                           ->setHelpGroup(tr('Identification'))
                                           ->setHelpText(tr('The name for this account')))

                    ->add(Definition::new($this, 'seo_name')
                                    ->setRender(false)
                                    ->setReadonly(true))

                    ->add(Definition::new($this, 'username')
                                    ->setLabel(tr('Username'))
                                    ->setInputType(EnumInputType::username)
                                    ->setCliColumn(tr('-u,--username NAME'))
                                    ->setCliAutoComplete(true)
                                    ->setSize(6)
                                    ->setMaxlength(64)
                                    ->setHelpText(tr('The username on the server for this account')))

                    ->add(DefinitionFactory::getDescription($this)
                                           ->setHelpText(tr('The description for this account')))

                    ->add(DefinitionFactory::getFile($this, 'file')
                                           ->setLabel(tr('SSH key file'))
                                           ->setCliColumn(tr('-i,--ssh-key-file FILE'))
                                           ->setHelpText(tr('The SSH key file for this account'))
                                           ->addValidationFunction(function (ValidatorInterface $validator) {
                                               $validator->isFile(FsDirectory::getFilesystemRootObject());
                                           }))

                    ->add(Definition::new($this, 'ssh_key')
                                    ->setLabel(tr('SSH key'))
                                    ->setCliColumn(tr('-k,--ssh-key "KEY"'))
                                    ->setCliAutoComplete(true)
                                    ->setSize(12)
                                    ->setMaxlength(65_535)
                                    ->setHelpText(tr('The SSH private key associated with this username'))
                                    ->addValidationFunction(function (ValidatorInterface $validator) {
                                        $validator->matchesRegex('/-----BEGIN .+? PRIVATE KEY-----.+?-----END .+? PRIVATE KEY-----/s');
                                    }));
    }
}
