<?php

/**
 * SshAccount class
 *
 * This DataEntry type class represents a single entry in the ssh_accounts table.
 *
 * This DataEntry class supports configuration loading from the path "ssh.accounts"
 *
 * Upon loading a new entry, if the column "file" is specified, but the "ssh_key" column is empty, the class will
 * automatically inject the contents of said file into the column "ssh_key"
 *
 * @see       DataEntry
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright © 2025 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Servers
 */


declare(strict_types=1);

namespace Phoundation\Servers;

use Phoundation\Data\DataEntries\DataEntry;
use Phoundation\Data\DataEntries\Definitions\Definition;
use Phoundation\Data\DataEntries\Definitions\DefinitionFactory;
use Phoundation\Data\DataEntries\Definitions\Interfaces\DefinitionsInterface;
use Phoundation\Data\DataEntries\Interfaces\IdentifierInterface;
use Phoundation\Data\DataEntries\Traits\TraitDataEntryFile;
use Phoundation\Data\DataEntries\Traits\TraitDataEntryNameDescription;
use Phoundation\Data\DataEntries\Traits\TraitDataEntryUsername;
use Phoundation\Data\Validator\Interfaces\ValidatorInterface;
use Phoundation\Filesystem\Traits\TraitDataRestrictions;
use Phoundation\Filesystem\PhoDirectory;
use Phoundation\Filesystem\PhoFile;
use Phoundation\Filesystem\PhoRestrictions;
use Phoundation\Servers\Interfaces\SshAccountInterface;
use Phoundation\Web\Html\Enums\EnumInputType;


class SshAccount extends DataEntry implements SshAccountInterface
{
    use TraitDataRestrictions;
    use TraitDataEntryNameDescription;
    use TraitDataEntryUsername;
    use TraitDataEntryFile;

    /**
     * SshAccount class constructor
     *
     * @param IdentifierInterface|array|string|int|false|null $identifier
     */
    public function __construct(IdentifierInterface|array|string|int|false|null $identifier = false)
    {
        $this->o_restrictions = PhoRestrictions::newFilesystemRootObject();
        parent::__construct($identifier);
    }


    /**
     * Returns the configuration path for this DataEntry object, if it has one, or NULL instead
     *
     * @return string|null
     */
    public static function getConfigurationPath(): ?string
    {
        return 'ssh.accounts';
    }


    /**
     * Returns the table name used by this object
     *
     * @return string|null
     */
    public static function getTable(): ?string
    {
        return 'ssh_accounts';
    }


    /**
     * Returns the name of this DataEntry class
     *
     * @return string
     */
    public static function getEntryName(): string
    {
        return tr('SSH account');
    }


    /**
     * Returns a unique log identifier that is both unique but also human-readable
     *
     * @return string
     */
    public function getLogId(): string
    {
        return $this->getTypesafe('int', 'id') . ' / ' . (static::getUniqueColumn() ? $this->getTypesafe('string', static::getUniqueColumn()) : '-') . '(' . $this->getUsername() . ')';
    }


    /**
     * Returns the field that is unique for this object
     *
     * @return string|null
     */
    public static function getUniqueColumn(): ?string
    {
        return 'name';
    }


    /**
     * Returns the ssh_key for this object
     *
     * @return string|null
     */
    public function getSshKey(): ?string
    {
        return $this->getTypesafe('string', 'ssh_key');
    }


    /**
     * Sets the ssh_key for this object
     *
     * @param string|null $ssh_key
     *
     * @return static
     */
    public function setSshKey(?string $ssh_key): static
    {
        return $this->set($ssh_key, 'ssh_key');
    }


    /**
     * Copies all specified source entries to the internal source and ensures "ssk_key" is loaded if "file" is specified
     *
     * @param array $source
     * @param bool $modify
     * @param bool $directly
     * @param bool $force
     * @return static
     */
    protected function copyValuesToSource(array $source, bool $modify, bool $directly = false, bool $force = false): static
    {
        parent::copyValuesToSource($source, $modify, $directly, $force); // TODO: Change the autogenerated stub

        if (!$this->isNew()) {
            // If any of the accounts have the "file" key, replace that key with ssh_key value
            if (empty($this->source['name'])) {
                // No name always default to username
                $this->source['name'] = $this->source['username'];
            }

            if (array_key_exists('file', $this->source)) {
                if ($this->source['file']) {
                    $this->source['ssh_key'] = PhoFile::new($this->source['file'], PhoRestrictions::newFilesystemRootObject())->getContentsAsString();
                }
            }
        }

        return $this;
    }


    /**
     * Sets the available data keys for this entry
     *
     * @param DefinitionsInterface $o_definitions
     *
     * @return static
     */
    protected function setDefinitionsObject(DefinitionsInterface $o_definitions): static
    {
        $o_definitions->add(DefinitionFactory::newName()
                                             ->setSize(6)
                                             ->setUnique()
                                             ->setHelpGroup(tr('Identification'))
                                             ->setHelpText(tr('The name for this account')))

                      ->add(Definition::new('seo_name')
                                    ->setRender(false)
                                    ->setReadonly(true))

                    ->add(Definition::new('username')
                                    ->setLabel(tr('Username'))
                                    ->setInputType(EnumInputType::username)
                                    ->setCliColumn(tr('-u,--username NAME'))
                                    ->setCliAutoComplete(true)
                                    ->setSize(6)
                                    ->setMaxLength(64)
                                    ->setHelpText(tr('The username on the server for this account')))

                    ->add(DefinitionFactory::newDescription()
                                           ->setHelpText(tr('The description for this account')))

                    ->add(DefinitionFactory::newFile()
                                           ->setLabel(tr('SSH key file'))
                                           ->setCliColumn(tr('-i,--ssh-key-file FILE'))
                                           ->setHelpText(tr('The SSH key file for this account'))
                                           ->addValidationFunction(function (ValidatorInterface $o_validator) {
                                               $o_validator->isFile(PhoDirectory::newFilesystemRootObject());
                                           }))

                    ->add(Definition::new('ssh_key')
                                    ->setLabel(tr('SSH key'))
                                    ->setCliColumn(tr('-k,--ssh-key "KEY"'))
                                    ->setCliAutoComplete(true)
                                    ->setSize(12)
                                    ->setMaxLength(65_535)
                                    ->setHelpText(tr('The SSH private key associated with this username'))
                                    ->addValidationFunction(function (ValidatorInterface $o_validator) {
                                        $o_validator->matchesRegex('/-----BEGIN .+? PRIVATE KEY-----.+?-----END .+? PRIVATE KEY-----/s');
                                    }));

        return $this;
    }
}
