#!/usr/bin/php
<?php

use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Servers\SshAccount;


/**
 * Script system/servers/accounts/info
 *
 * This script displays information about the specified account.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system servers accounts info IDENTIFIER';

$help  = 'This script displays information about the specified SSH account.  



ARGUMENTS



IDENTIFIER                              The SSH account to display information about. Specify either by account id or  
                                        name';



// Validate arguments
$argv = ArgvValidator::new()
    ->select('identifier')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->noArgumentsLeft()
    ->validate();



// Display SSH account data
SshAccount::get($argv['account'])->getCliForm();
