#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Core\Config;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script config/create-default
 *
 * This script will create a default configuration file ROOT/config/default.yaml containing ALL possible configuration
 * paths and their default values
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho config create-default');

Documentation::help('This script will create a default configuration file ROOT/config/default.yaml containing ALL possible configuration paths and their default values');



// Validate no arguments
$argv = ArgvValidator::new()->noArgumentsLeft();



// Generate default yaml configuration file
$count = Config::generateDefaultYaml();
Log::success(tr('Created config/default.yaml with ":count" configuration paths', [':count' => $count]));