#!/usr/bin/php
<?php

use Phoundation\Cli\Cli;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Data\Validator\ArrayValidator;
use Phoundation\Exception\OutOfBoundsException;
use Phoundation\System\Environment\Environment;



/**
 * This is the setup script for the project. This script will be the first script to be run to set up your system
 *
 * In order to be able to set up, one conditions must be met: There is no configuration file available
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Core
 */

// Get command line arguments
ArgvValidator::new()
    ->select('--no-password-validation')->isOptional(false)->isBoolean()
    ->noArgumentsLeft()
    ->validate();



// Validate environment
$environment = Cli::readInput('Please specify the environment you wish to set up:', 'local');
$environment = Environment::sanitize($environment);

if (Environment::exists($environment)) {
    throw OutOfBoundsException::new(tr('Specified environment ":environment" has already been setup', [
        ':environment' => $environment
    ]))->makeWarning();
}



// Get configuration parameters
$configuration = [];
$configuration['project']        = Cli::readInput('Please specify the project name:', 'Phoundation');
$configuration['domain']         = Cli::readInput('Please specify the project domain name:', 'localhost');
$configuration['database_host']  = Cli::readInput('Please specify the core database host:', 'localhost');
$configuration['database_name']  = Cli::readInput('Please specify the core database name:', 'phoundation');
$configuration['database_user']  = Cli::readInput('Please specify the core database user:', 'phoundation');
$configuration['database_pass1'] = Cli::readPassword('Please specify the core database password:');
$configuration['database_pass2'] = Cli::readPassword('Please repeat the core database password:');
$configuration['admin_email']    = Cli::readInput('Please specify the administrator email:');
$configuration['admin_pass1']    = Cli::readPassword('Please specify the administrator password:');
$configuration['admin_pass2']    = Cli::readPassword('Please repeat the administrator password:');



// Validate configuration parameters
if ($argv['no_password_validation']) {
    ArrayValidator::new($configuration)
        ->select('project')->isWord()
        ->select('domain')->isDomain()
        ->select('database_host')->isDomain()
        ->select('database_name')->isWord()
        ->select('database_user')->isWord()
        ->select('database_pass1')->isPrintable()
        ->select('admin_email')->isEmail()
        ->select('admin_pass1')->isPrintable()
        ->validate();

} else {
    ArrayValidator::new($configuration)
        ->select('project')->isWord()
        ->select('domain')->isDomain()
        ->select('database_host')->isDomain()
        ->select('database_name')->isWord()
        ->select('database_user')->isWord()
        ->select('database_pass1')->isPassword()
        ->select('database_pass2')->isPassword()->isEqualTo('database_pass2')
        ->select('admin_email')->isEmail()
        ->select('admin_pass1')->isPassword()
        ->select('admin_pass2')->isPassword()->isEqualTo('admin_pass1')
        ->validate();
}



// Yay! We can safely set up this environment. Create a basic configuration file from a few basic questions.
$environment = Environment::new($environment);
$environment->getConfiguration()->setProject($configuration['project']);
$environment->getConfiguration()->setDomain($configuration['domain']);
$environment->getConfiguration()->setEmail($configuration['admin_email']);
$environment->getConfiguration()->setPassword($configuration['admin_pass1']);
$environment->getConfiguration()->getDatabase()->setHost($configuration['database_host']);
$environment->getConfiguration()->getDatabase()->setName($configuration['database_name']);
$environment->getConfiguration()->getDatabase()->setUser($configuration['database_user']);
$environment->getConfiguration()->getDatabase()->setPass($configuration['database_pass1']);
$environment->setup();
