#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Filesystem\Mounts\Mount;


/**
 * Script file-system/mount/unmount
 *
 * Unmounts the specified mount
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */


$argv = ArgvValidator::new()
    ->select('mount')->isVariable()
    ->validate();


Mount::new($argv['mount'])->unmount();