#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\CliColor;
use Phoundation\Cli\CliDocumentation;
use Phoundation\Core\Config;
use Phoundation\Core\Libraries\Libraries;
use Phoundation\Core\Log\Log;
use Phoundation\Core\Numbers;
use Phoundation\Core\Strings;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Databases\Sql\Exception\SqlAccessDeniedException;
use Phoundation\Databases\Sql\Exception\SqlDatabaseDoesNotExistException;
use Phoundation\Developer\Debug;
use Phoundation\Emails\Email;


/**
 * Script email/send
 *
 * This script can send out emails
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
CliDocumentation::usage('./pho email send');
CliDocumentation::help('This script can send out emails


ARGUMENTS


-');


$argv = ArgvValidator::new()
    ->select('-f,--from')->isEmail()
    ->select('-t,--to')->isEmail()
    ->select('-s,--subject')->hasMaxCharacters(255)
    ->select('-b,--body')->hasMaxCharacters(65536)
    ->validate();

Email::new()
    ->addFrom($argv['from'])
    ->addTo($argv['to'])
    ->setSubject($argv['subject'])
    ->setBody($argv['body'])
    ->send();
