#!/usr/bin/php
<?php

use Phoundation\Cli\Script;

require('./vendor/autoload.php');

Script::execute();


// https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial

//#/usr/bin/env bash
//_dothis_completions()
//{
//  if [ "${#COMP_WORDS[@]}" != "2" ]; then
//    return
//  fi
//
//  COMPREPLY=($(compgen -W "$(fc -l -50 | sed 's/\t//')" -- "${COMP_WORDS[1]}"))
//}
//
//complete -F _dothis_completions dothis
