#!/usr/bin/php
<?php

use Phoundation\Cli\Script;


/**
 * Pho
 *
 * This is the standard phoundation command execution script.
 *
 * With this script you can execute all Phoundation scripts. It supports auto complete so please try and use <TAB>
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Scripts
 * @package Phoundation\Cli
 */
require('./vendor/autoload.php');
Script::execute();
