#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Accounts\Users\User;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/accounts/users/delete
 *
 * This script can delete users
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho system accounts users delete USER_EMAIL');

Documentation::help('This script will delete the specified user. Note that deleted users will not be removed from the database, 
the status for the user will be updated to "deleted"



ARGUMENTS



USER_EMAIL                              The email address for the user to delete');



// Validate arguments
$argv = ArgvValidator::new()
    ->select('user')->isEmail()
    ->noArgumentsLeft()
    ->validate();



// Display user data
User::get($argv['user'])->delete();
