#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$usage = "./scripts/base/notifications/send CODE TITLE [--groups GROUPS] [MESSAGE] \n";

$help  = "Send event notifications to the specified classes";

$quiet = true;
require_once(__DIR__.'/../../../libs/startup.php');

try{
    cli_only();

    $class   = cli_argument(0);
    $event   = cli_argument(1);

    unset($argv[0]);
    unset($argv[1]);

    $message = implode(' ', cli_argument(null));

    if (empty($class)) {
        throw new CoreException(tr('No class name or id specified'), 'not-specified');
    }

    if (empty($class)) {
        throw new CoreException(tr('No event name specified'), 'not-specified');
    }

    if (empty($class)) {
        throw new CoreException(tr('No message specified'), 'not-specified');
    }

    notify(array('code'    => $code,
                 'groups'  => $groups,
                 'title'   => $title,
                 'message' => $message));

    log_console(tr('Sent notification ":event"', array(':event' => $event)), '', 'green');

}catch(Exception $e) {
    cli_error($e);
}
?>
