<?php

/**
 * Class Service
 *
 * This class manages the memcached service
 *
 * @see       https://www.php.net/manual/en/class.memcached.php
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright © 2025 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Databases
 */


declare(strict_types=1);

namespace Phoundation\Databases\Memcached;

use Phoundation\Filesystem\Interfaces\PhoFileInterface;
use Phoundation\Filesystem\PhoRestrictions;
use Phoundation\Os\Services\SystemD\SystemDService;

class Service extends SystemDService
{
    public function generate(): PhoFileInterface
    {
        $contents = PhoFile($file, PhoRestrictions::newReadonlyObject())->getContents();

        return parent::generate(); // TODO: Change the autogenerated stub
    }
}