#!/usr/bin/php
<?php

declare(strict_types=1);


declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Virtualization\Kubernetes\Secrets\Secret;


/**
 * Script devops/kubernetes/secrets/create
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho devops kubernetes delete secret');
Documentation::help('This script creates Kubernetes secrets');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('name', true)->matchesRegex('/^[a-z0-9-]+$/')
    ->noArgumentsLeft()
    ->validate();


// Create new secret and apply it
$secret = Secret::new($argv['name'])->delete();
