#!/usr/bin/php
<?php

use Phoundation\Core\Log;
use Phoundation\Exception\Exceptions;
use Phoundation\Exception\ScriptException;
use Phoundation\Processes\Exception\ProcessFailedException;
use Phoundation\Processes\Process;



/**
 * Script system/mysql/timezones/import
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\System
 */
$usage = './cli system mysql timezones import';

$help  = '';

try {
    Log::cli(tr('Importing timezone data files in MySQL'), 'white');
    Log::cli(tr('You may ignore any "Warning: Unable to load \'/usr/share/zoneinfo/........\' as time zone. Skipping it." messages'), 'warning');
    Log::cli(tr('Please fill in MySQL root password in the following "Enter password:" request'), 'white');

    $mysql = new Process('mysql');
    $mysql->addArguments(['-p', '-u', 'root', 'msql']);

    $process = new Process('mysql_tzinfo_to_sql');
    $process->addArgument('/usr/share/zoneinfo');
    $process->pipe($mysql->getFullCommand());
    $process->executePassthru();

}catch(ProcessFailedException $e) {
    // Something went wrong during import Get MySQL error
    $message = $e->getMessages();
    $message = array_shift($message);
    $message = json_decode_custom($message);
    $message = array_shift($message);

    if (str_contains($message, 'ERROR 1045')) {
        throw Exceptions::ScriptException(tr('Incorrect MySQL root password supplied'))->makeWarning();
    }

    throw $e;
}
