#!/usr/bin/php
<?php

use Phoundation\Cli\Color;
use Phoundation\Core\Log;
use Phoundation\Processes\Processes;



/**
 * Script system/mysql/timezones/import
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\System
 */
$usage = './cli system mysql timezones import';

$help  = '';

Log::cli(Color::apply(tr('Importing timezone data files in MySQL, this may take a couple of seconds'), 'white'));
Log::cli(tr('You may ignore any "Warning: Unable to load \'/usr/share/zoneinfo/........\' as time zone. Skipping it." messages'));
Log::cli(tr('Please fill in MySQL root password in the following "Enter password:" request'));

$mysql = Processes::create('mysql')
    ->setTimeout(10)
    ->addArguments(['-p', '-u', 'root', 'mysql']);

Processes::create('mysql_tzinfo_to_sql')
    ->setTimeout(10)
    ->addArgument('/usr/share/zoneinfo')
    ->setPipe($mysql)
    ->executePassthru();
