#!/usr/bin/php
<?php

use Phoundation\Cli\Color;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Databases\Mysql;



/**
 * Script system/mysql/timezones/import
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system mysql timezones import';

$help  = '';

ArgvValidator::new()->noArgumentsLeft();

Log::cli(Color::apply(tr('Importing timezone data files in MySQL, this may take a couple of seconds'), 'white'));
Log::cli(tr('You may ignore any "Warning: Unable to load \'/usr/share/zoneinfo/........\' as time zone. Skipping it." messages'));
Log::cli(tr('Please fill in MySQL root password in the following "Enter password:" request'));

Mysql::getInstance()->importTimezones();