#!/usr/bin/php
<?php
/*
 * This is a script template
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package template
 */
$usage = './scripts/base/template
./scripts/base/template option [option]';

$help  = 'No help available';

cli_only();
load_libs('test');

switch (cli_method()) {
    case '':
        throw new CoreException(tr('No method specified'), 'no-method');

    default:
        throw new CoreException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}
?>
