#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Versioning\Git\Git;


/**
 * THIS SCRIPT IS ONLY FOR PHOUNDATION DEVELOPERS
 *
 * This script is an interface to the git command through Phoundation. Its not really needed -nor useful- beyond testing
 * the git library
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Development
 */
Documentation::usage('./cli system development git status [PATH]
./cli system dev git status [PATH]');
Documentation::help('This script is an interface to the git command through Phoundation. Its not really needed -nor 
useful- beyond testing the git library');



// Get command line arguments
$argv = ArgvValidator::new()
    ->select('path', true)->isOptional()->isFile()
    ->noArgumentsLeft()
    ->validate();


Git::new(PATH_ROOT)->getStatus($argv['path'])->CliDisplayTable();