<?php

/**
 * Class DataIterator
 *
 *
 *
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright © 2025 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Data
 */


declare(strict_types=1);

namespace Phoundation\Data\DataEntries;

use PDOStatement;
use Phoundation\Accounts\Users\Sessions\Session;
use Phoundation\Cache\Cache;
use Phoundation\Cli\CliAutoComplete;
use Phoundation\Core\Interfaces\ArrayableInterface;
use Phoundation\Core\Log\Log;
use Phoundation\Core\Meta\Meta;
use Phoundation\Data\DataEntries\Exception\DataEntryNotExistsException;
use Phoundation\Data\DataEntries\Exception\DataEntryReadonlyException;
use Phoundation\Data\DataEntries\Interfaces\DataEntryInterface;
use Phoundation\Data\DataEntries\Interfaces\DataIteratorInterface;
use Phoundation\Data\DataEntries\Interfaces\IdentifierInterface;
use Phoundation\Data\DataEntries\Interfaces\ListOperationsInterface;
use Phoundation\Data\Exception\IteratorDataTypeNotAcceptedException;
use Phoundation\Data\Exception\IteratorValidatorFailedException;
use Phoundation\Data\Interfaces\EntryInterface;
use Phoundation\Data\Interfaces\IteratorInterface;
use Phoundation\Data\IteratorCore;
use Phoundation\Data\Traits\TraitDataCacheKey;
use Phoundation\Data\Traits\TraitDataColumns;
use Phoundation\Data\Traits\TraitDataConnector;
use Phoundation\Data\Traits\TraitDataDebug;
use Phoundation\Data\Traits\TraitDataFilterForm;
use Phoundation\Data\Traits\TraitDataMetaEnabled;
use Phoundation\Data\Traits\TraitDataStatusFilter;
use Phoundation\Data\Traits\TraitMethodBuildManualQuery;
use Phoundation\Data\Traits\TraitMethodsTableState;
use Phoundation\Data\Validator\Exception\ValidationFailedException;
use Phoundation\Data\Validator\Interfaces\ValidatorInterface;
use Phoundation\Data\Validator\Validator;
use Phoundation\Databases\Sql\Interfaces\QueryBuilderInterface;
use Phoundation\Databases\Sql\QueryBuilder\QueryBuilder;
use Phoundation\Databases\Sql\SqlQueries;
use Phoundation\Exception\NotExistsException;
use Phoundation\Exception\ObsoleteException;
use Phoundation\Exception\OutOfBoundsException;
use Phoundation\Security\Incidents\Incident;
use Phoundation\Utils\Arrays;
use Phoundation\Utils\Json;
use Phoundation\Utils\Strings;
use Phoundation\Web\Html\Components\Input\InputSelect;
use Phoundation\Web\Html\Components\Input\Interfaces\InputSelectInterface;
use Phoundation\Web\Html\Components\Tables\HtmlDataTable;
use Phoundation\Web\Html\Components\Tables\HtmlTable;
use Phoundation\Web\Html\Components\Tables\Interfaces\HtmlDataTableInterface;
use Phoundation\Web\Html\Components\Tables\Interfaces\HtmlTableInterface;
use Phoundation\Web\Html\Enums\EnumTableIdColumn;
use ReturnTypeWillChange;
use Stringable;


class DataIteratorCore extends IteratorCore implements DataIteratorInterface, IdentifierInterface
{
    use TraitDataColumns {
        setColumns as protected __setColumns;
    }
    use TraitDataCacheKey;
    use TraitDataConnector;
    use TraitDataDebug;
    use TraitDataFilterForm;
    use TraitDataStatusFilter;
    use TraitDataMetaEnabled;
    use TraitMethodBuildManualQuery;
    use TraitMethodsTableState;
    use TraitDataMetaEnabled;


    /**
     * The iterator position
     *
     * @var int $position
     */
    protected int $position = 0;

    /**
     * The query to display an HTML table for this list
     *
     * @var string|null $query
     */
    protected ?string $query = null;

    /**
     * The execution array for the HTML query
     *
     * @var array|null $execute
     */
    protected ?array $execute = null;

    /**
     * Tracks if this data list has data loaded from a database
     *
     * @var bool $is_loaded
     */
    protected bool $is_loaded = false;

    /**
     * Tracks if this data list is currently loading data from a database
     *
     * @var bool $is_loading
     */
    protected bool $is_loading = false;

    /**
     * If set, use the query generated by this builder instead of the default query
     *
     * @var QueryBuilderInterface
     */
    protected QueryBuilderInterface $o_query_builder;

    /**
     * Tracks if entries are stored by id or unique column
     *
     * @var bool $keys_are_unique_column
     */
    protected bool $keys_are_unique_column = false;

    /**
     * Tracks the class used to generate the select input
     *
     * @var string $input_select_class
     */
    protected string $input_select_class = InputSelect::class;

    /**
     * Tracks the entries in this iterator that were modified
     *
     * @var int $modified_count
     */
    protected int $modified_count = 0;

    /**
     * Tracks the entries in this iterator that were saved
     *
     * @var int $saved_count
     */
    protected int $saved_count = 0;

    /**
     * Tracks if DataEntry objects should be created using normal setSource() or setSourceDirectly()
     *
     * @var bool $inject_source_directly
     */
    protected bool $inject_source_directly = true;

    /**
     * Tracks if added object must have a key that match either the objects id or unique identifier
     *
     * @var bool $require_key_match_unique_identifier
     */
    protected bool $require_key_match_unique_identifier = true;


    /**
     * DataIterator class constructor
     *
     * @param IteratorInterface|array|string|PDOStatement|null $source
     */
    public function __construct(IteratorInterface|array|string|PDOStatement|null $source = null)
    {
        parent::__construct($source);

        // If this data iterator had a source specified, consider it loaded
        $this->setAcceptedDataTypes(DataEntry::class, false);
        $this->is_loaded = (bool) $source;
        $this->use_cache = Cache::isEnabled();
    }


    /**
     * Returns true if the ID column is the specified column
     *
     * @param string $column
     *
     * @return bool
     */
    public static function uniqueColumnIs(string $column): bool
    {
        return (static::getUniqueColumn() ?? static::getIdColumn()) === $column;
    }


    /**
     * Returns the column that is unique for this object
     *
     * @return string|null
     */
    public static function getUniqueColumn(): ?string
    {
        return static::getIdColumn();
    }


    /**
     * Returns the column that is the ID column for this object. Typically this is "id" but may be changed as needed by
     * overriding this method
     *
     * @return string|null
     */
    public static function getIdColumn(): ?string
    {
        return 'id';
    }


    /**
     * Returns the configuration path for this DataEntry object, if it has one, or NULL instead
     *
     * @return string|null
     */
    public static function getConfigurationPath(): ?string
    {
        return null;
    }


    /**
     * Sets the datatype restrictions for all elements in this iterator, NULL if none
     *
     * @param array|string|null $data_types
     * @param bool              $overwrite
     *
     * @return static
     */
    public function setAcceptedDataTypes(array|string|null $data_types, bool $overwrite = true): static
    {
        if ($this->accepted_data_types and !$overwrite) {
            return $this;
        }

        $data_types = Arrays::force($data_types, '|');

        if (count($data_types) != 1) {
            throw new OutOfBoundsException(tr('Cannot specify ":count" data types for class ":class", DataIterator classes require exactly one datatype', [
                ':count' => count($data_types),
                ':class' => static::class
            ]));
        }

        return parent::setAcceptedDataTypes($data_types, $overwrite);
    }


    /**
     * Access the direct list operations for this class
     *
     * @todo Remove this. "Direct operations" was a bad idea and should be removed when we have some time
     * @return ListOperationsInterface
     */
    public static function directOperations(): ListOperationsInterface
    {
throw new ObsoleteException();
        return new ListOperations(static::class);
    }


    /**
     * Returns if the specified data entry key exists in the data list
     *
     * @param DataEntryInterface|Stringable|string|float|int $key
     *
     * @return bool
     */
    public function keyExists(DataEntryInterface|Stringable|string|float|int $key): bool
    {
        if ($key instanceof DataEntryInterface) {
            $key = $key->getId();
        }

        return parent::keyExists($key);
    }


    /**
     * Returns the query for this object when generating internal content
     *
     * @return string|null
     */
    public function getQuery(): ?string
    {
        $this->selectQuery();

        return $this->query;
    }


    /**
     * Returns a QueryBuilder object from this DataIterator to modify the internal query for this object
     *
     * @return QueryBuilderInterface
     */
    public function getQueryBuilderObject(): QueryBuilderInterface
    {
        $this->useQueryBuilder();
        return $this->o_query_builder;
    }


    /**
     * Returns the hash for the executed query
     *
     * @return string|null
     */
    public function getQueryHash(): ?string
    {
        if (isset($this->o_query_builder)) {
            $hash = 'QB-' . $this->o_query_builder->getQueryHash() . sha1(sql()->parseQuery($this->query, $this->execute));
//Log::printr('QUERY BUILDER: ' . sql()->parseQuery($this->query_builder->getQuery(), $this->query_builder->getExecute()));

        } elseif ($this->query) {
            $hash = 'SQL-' . sha1(sql()->parseQuery($this->query, $this->execute));
//Log::printr('QUERY SQL: ' . sql()->parseQuery($this->query, $this->execute));

        } else {
            $hash = null;
        }

//Log::printr($hash);
        return $hash;
    }


    /**
     * Allows the query builder to be modified through a callback function
     *
     * @param callable $callback
     *
     * @return static
     */
    public function modifyQueryBuilderObject(callable $callback): static
    {
        $callback($this->o_query_builder);
        return $this;
    }


    /**
     * Initializes the QueryBuilder object for this DataIterator
     *
     * @return static
     */
    public function useQueryBuilder(): static
    {
        if (empty($this->o_query_builder)) {
            $this->o_query_builder = QueryBuilder::new($this)
                                                 ->setDebug($this->debug)
                                                 ->setMetaEnabled($this->getMetaEnabled())
                                                 ->setConnectorObject($this->getConnectorObject())
                                                 ->setSelects($this->getSqlSelectColumns());

            if ($this->status_filter !== false) {
                $this->o_query_builder->addWhere(SqlQueries::is('`' . static::getTable() . '`.`status`', $this->status_filter, ':status'));
            }
        }

        return $this;
    }


    /**
     * Sets the QueryBuilder object to modify the internal query for this object
     *
     * @param QueryBuilderInterface $query_builder
     *
     * @return static
     */
    public function setQueryBuilderObject(QueryBuilderInterface $query_builder): static
    {
        $this->o_query_builder = $query_builder;
        return $this;
    }


    /**
     * Set the query for this object when generating internal content
     *
     * @param string|null $query
     * @param array|null  $execute
     *
     * @return static
     */
    public function setQuery(?string $query, ?array $execute = null): static
    {
        unset($this->o_query_builder);

        $this->query   = $query;
        $this->execute = $execute;

        return $this;
    }


    /**
     * Selects if we use the default query or a query from the QueryBuilder
     *
     * @param array|string|int|null $identifiers
     * @param bool                  $like
     *
     * @return static
     */
    protected function selectQuery(array|string|int|null $identifiers = null, bool $like = false): static
    {
        // Use the query builder or hard-coded query
        if (isset($this->o_query_builder)) {
            // Add query builder filters from filter_form if attached, or identifiers first if specified
            if (empty($identifiers)) {
                $this->filter_form?->applyFiltersToQueryBuilder($this->o_query_builder);

            } else {
                $this->getQueryBuilderObject()->setIdentifiers($identifiers, $like);
            }

            $this->query   = $this->o_query_builder->getQuery();
            $this->execute = $this->o_query_builder->getExecute();

        } elseif (empty($this->query) or $identifiers) {
            if (static::getTable()) {
                // Define default identifiers
                if ($identifiers === null) {
                    $identifiers = ['status' => null];
                }

                // Create a query with optional filtering for parents_id
                if ($this->o_parent) {
                    $parent_filter = '`' . static::getTable() . '`.`' . Strings::fromReverse($this->o_parent::getTable(), '_') . '_id` = :parents_id AND ';
                    $this->execute['parents_id'] = $this->o_parent->getId();

                } else {
                    $parent_filter = null;
                }

                $this->buildManualQuery($identifiers, $where, $joins, $group, $order, $this->execute);

                // Set default query
                $this->query = 'SELECT  ' . $this->getSqlSelectColumns() . '
                                FROM   `' . static::getTable() . '`
                                ' . $joins . '
                                WHERE  ' . $parent_filter .  $where . $group . $order;
            }
        }

        return $this;
    }


    /**
     * Returns if added object must have a key that match either the objects id or unique identifier
     *
     * @return bool
     */
    public function getRequireKeyMatchUniqueIdentifier(): bool
    {
        return $this->require_key_match_unique_identifier;
    }


    /**
     * Sets if added object must have a key that match either the objects id or unique identifier
     *
     * @param bool $require_key_match_unique_identifier
     *
     * @return static
     */
    public function setRequireKeyMatchUniqueIdentifier(bool $require_key_match_unique_identifier): static
    {
        $this->require_key_match_unique_identifier = $require_key_match_unique_identifier;
        return $this;
    }


    /**
     * Returns if the source keys will be the DataEntry object id or DataEntry unique identifier
     *
     * @return bool
     */
    public function getKeysAreUniqueColumn(): bool
    {
        return $this->keys_are_unique_column;
    }


    /**
     * Sets if the source keys will be the DataEntry object id or DataEntry unique identifier
     *
     * @param bool $value
     *
     * @return static
     */
    public function setKeysAreUniqueColumn(bool $value): static
    {
        $this->keys_are_unique_column = $value;
        return $this;
    }


    /**
     * Returns if DataEntry objects should be created using normal setSource() or setSourceDirectly()
     *
     * @return bool
     */
    public function getInjectSourceDirectly(): bool
    {
        return $this->inject_source_directly;
    }


    /**
     * Sets if DataEntry objects should be created using normal setSource() or setSourceDirectly()
     *
     * @param bool $inject_source_directly
     *
     * @return static
     */
    public function setInjectSourceDirectly(bool $inject_source_directly): static
    {
        $this->inject_source_directly = $inject_source_directly;
        return $this;
    }


    /**
     * Returns the "execute" array for the query for this object when generating internal content
     *
     * @return array|null
     */
    public function getExecute(): ?array
    {
        $this->selectQuery();

        return $this->execute;
    }


    /**
     * Returns the table name used by this object
     *
     * @return string|null
     */
    public static function getTable(): ?string
    {
        return null;
    }


    /**
     * Returns what SQL columns will be used in loading data
     *
     * @return string
     */
    public function getSqlSelectColumns(): string
    {
        if ($this->columns) {
            $return = [];

            // Add SQL SELECT for each specified column
            foreach ($this->columns as $column) {
                $return[] = SqlQueries::ensureQuotes(static::getTable()) . '.' . SqlQueries::ensureQuotes($column);
            }

            return implode(', ', $return);
        }

        // Load all columns
        return SqlQueries::ensureQuotes(static::getTableIdColumn()) . ' AS `unique_identifier`, ' . SqlQueries::ensureQuotes(static::getTable()) . '.* ';
    }


    /**
     * Returns all data for this data entry at once with values being the specified column
     *
     * @note This method filters out all keys defined in static::getProtectedKeys() to ensure that keys like "password"
     *       will not become available outside this object
     *
     * @see EntryCore::getSource()
     * @param string $column
     *
     * @return array
     */
    public function getSourceColumn(string $column): array
    {
        $source = $this->getSource();

        foreach ($source as &$value) {
            if (is_array($value)) {
                $value = $value[$column];

            } elseif ($value instanceof EntryInterface) {
                $value = $value->get($column);

            } else {
                throw new OutOfBoundsException(tr('Cannot return specified column ":column", the Iterator source contains invalid value ":value"', [
                    ':column' => $column,
                    ':value'  => $value
                ]));
            }
        }

        unset($value);
        return $source;
    }


    /**
     * Returns the column that (by default) is used for keys
     *
     * @return string
     */
    protected function getTableIdColumn(): string
    {
        return '`' . static::getTable() . '`.`' . (static::getUniqueColumn() ?? static::getIdColumn()) . '`';
    }


    /**
     * Returns the entry with the specified identifier
     *
     * @param Stringable|string|float|int $key
     * @param bool                        $exception
     *
     * @return mixed
     */
    #[ReturnTypeWillChange] public function get(Stringable|string|float|int $key, bool $exception = true): mixed
    {
        // Does this entry exist?
        if (array_key_exists($key, $this->source)) {
            return $this->ensureObject($key);
        }

        if ($exception) {
            throw new NotExistsException(tr('Key ":key" does not exist in this ":class" DataIterator', [
                ':key'   => $key,
                ':class' => static::class,
            ]));
        }

        return null;
    }


    /**
     * Returns the random entry
     *
     * @return mixed
     */
    #[ReturnTypeWillChange] public function getRandom(): mixed
    {
        if (empty($this->source)) {
            return null;
        }

        return $this->ensureObject(array_rand($this->source, 1));
    }


    /**
     * Returns the data types that are allowed and accepted for this data iterator
     *
     * @return string|null
     */
    public static function getDefaultContentDataType(): ?string
    {
        return DataEntry::class;
    }


    /**
     * Sets the value for the specified key
     *
     * @param DataEntryInterface          $value
     * @param Stringable|string|float|int $key
     * @param bool                        $skip_null_values
     *
     * @return static
     */
    public function set(mixed $value, Stringable|string|float|int $key, bool $skip_null_values = true): static
    {
        if ($value instanceof DataEntryInterface) {
            return parent::set($value, $key);
        }

        throw new OutOfBoundsException(tr('Cannot set value ":value" to key ":key" in the list ":list", the value does not have a required DataEntryInterface', [
            ':list'  => static::class,
            ':key'   => $key,
            ':value' => $value,
        ]));
    }


    /**
     * Creates and returns an HTML table for the data in this list
     *
     * @param array|string|null $columns
     *
     * @return HtmlTableInterface
     */
    public function getHtmlTableObject(array|string|null $columns = null): HtmlTableInterface
    {
        $columns = get_null(Arrays::force($columns ?? $this->columns));

        if ($this->source) {
            // Source is already loaded, use that
            return parent::getHtmlTableObject($columns)
                         ->setId(static::getTable());
        }

        $this->selectQuery();

        // Create and return the table
        return HtmlTable::new($this)
                        ->setId(static::getTable())
                        ->setConnectorObject($this->getConnectorObject())
                        ->setHeaders($this->prepareHeaders($columns))
                        ->setSourceQuery($this->query, $this->execute)
                        ->setRowCallbacks($this->row_callbacks)
                        ->setCheckboxSelectors(EnumTableIdColumn::checkbox);
    }


    /**
     * Creates and returns a fancy HTML data table for the data in this list
     *
     * @param array|string|null $columns
     *
     * @return HtmlDataTableInterface
     */
    public function getHtmlDataTableObject(array|string|null $columns = null): HtmlDataTableInterface
    {
        $columns = get_null(Arrays::force($columns ?? $this->columns));

        if ($this->is_loaded) {
            // Source is already loaded, use that
            return parent::getHtmlDataTableObject($columns)
                         ->setId(static::getTable());
        }

        // This DataIterator is empty, automatically load
        $this->selectQuery();

        // Create and return the table
        return HtmlDataTable::new($this)
                            ->setId(static::getTable())
                            ->setConnectorObject($this->getConnectorObject())
                            ->setHeaders($this->prepareHeaders($columns))
                            ->setSourceQuery($this->query, $this->execute)
                            ->setRowCallbacks($this->row_callbacks)
                            ->setCheckboxSelectors(EnumTableIdColumn::checkbox);
    }


    /**
     * Returns an HTML <select> for the available object entries
     *
     * @param string|null $value_column
     * @param string|null $key_column
     * @param string      $class
     *
     * @return InputSelectInterface
     */
    public function getHtmlSelectObject(?string $value_column = 'name', ?string $key_column = 'id', string $class = InputSelect::class): InputSelectInterface
    {
        if ($this->is_loaded) {
            // Source is already loaded, use that
            return parent::getHtmlSelectObject($value_column, $key_column, $class)
                         ->setId(static::getTable());
        }

        // Create and return the select object
        return ($class ?? InputSelect::class)::new($this)
                                             ->setId(static::getTable())
                                             ->setKeyColumn($key_column)
                                             ->setValueColumn($value_column)
                                             ->setName(static::getTable())
                                             ->setConnectorObject($this->getConnectorObject())
                                             ->setSourceQuery($this->query, $this->execute);
    }


    /**
     * Returns an HTML <select> for the available object entries
     *
     * @param string      $value_column
     * @param string|null $key_column
     * @param string|null $order
     * @param array|null  $joins
     * @param array|null  $filters
     *
     * @return InputSelectInterface
     */
    public function getHtmlSelectOld(string $value_column = 'name', ?string $key_column = null, ?string $order = null, ?array $joins = null, ?array $filters = ['status' => null]): InputSelectInterface
    {
        $execute = [];
        $select  = $this->input_select_class::new($this);

        if (!$key_column) {
            $key_column = static::getUniqueColumn();
        }

        if ($this->is_loaded or count($this->source)) {
            // Data was either loaded from DB or manually added. $value_column may contain query parts, strip em.
            $value_column = trim($value_column);
            $value_column = Strings::fromReverse($value_column, ' ');
            $value_column = str_replace('`', '', $value_column);

            $select->setSource($this->getAllRowsSingleColumn($value_column, true))
                   ->setValueColumn($value_column);

        } else {
            $query = 'SELECT ' . $key_column . ', ' . $value_column . '
                      FROM  `' . static::getTable() . '`
                      ' . Strings::force($joins, ' ');

            if ($filters) {
                $where = [];

                foreach ($filters as $key => $value) {
                    if (str_contains($key, '.')) {
                        $key = Strings::ensureSurroundedWith($key, '`');

                    } else {
                        $key = '`' . static::getTable() . '`.' . Strings::ensureSurroundedWith($key, '`');
                    }

                    $where[] = SqlQueries::is($key, $value, 'value', $execute);
                }

                $query .= ' WHERE ' . implode(' AND ', $where);
            }

            if ($order === null) {
                // Default order by the value column. Value column may have SQL, make sure its stripped
                $order = Strings::fromReverse($value_column, ' ') . ' ASC';
            }

            // Only order if an order column has been specified
            if ($order) {
                $query .= ' ORDER BY ' . $order;
            }

            $value_column = trim($value_column);
            $value_column = Strings::fromReverse($value_column, ' ');
            $value_column = str_replace('`', '', $value_column);

            // No data was loaded from DB or manually added
            $select->setDebug($this->debug)
                   ->setConnectorObject($this->getConnectorObject())
                   ->setSourceQuery($query, $execute)
                   ->setValueColumn($value_column)
                   ->setNotSelectedLabel(tr('Select an item'))
                   ->setComponentEmptyLabel(tr('No items available'));
        }

        return $select;
    }


    /**
     * Creates and returns a CLI table for the data in this list
     *
     * @param array|string|null $columns
     * @param array             $filters
     * @param string|null       $id_column
     *
     * @return static
     */
    public function displayCliTable(array|string|null $columns = null, array $filters = [], ?string $id_column = 'id'): static
    {
        // If this list is empty, then load data from a query, else show list contents
        if (empty($this->source)) {
            $this->selectQuery();
            $this->source = sql($this->getConnectorObject())->setDebug($this->debug)
                                                            ->list($this->query, $this->execute);
        }

        return parent::displayCliTable($columns, $filters, $id_column);
    }


    /**
     * Delete all the entries in this list
     *
     * @param string|null $comments
     * @param bool        $auto_save
     *
     * @return static
     */
    public function delete(?string $comments = null, bool $auto_save = true): static
    {
        return $this->setStatus('deleted', $comments, $auto_save);
    }


    /**
     * Undelete the specified entries
     *
     * @note This will set the status "NULL" to the entries in this datalist, NOT the original value of their status!
     *
     * @param string|null $comments
     * @param bool        $auto_save
     *
     * @return static
     */
    public function undelete(?string $comments = null, bool $auto_save = true): static
    {
        return $this->setStatus(null, $comments, $auto_save);
    }


    /**
     * Set the specified status for the specified entries
     *
     * @param string|null $status
     * @param string|null $comments
     * @param bool        $auto_save
     *
     * @return static
     */
    public function setStatus(?string $status, ?string $comments = null, bool $auto_save = true): static
    {
        foreach ($this->source as $entry) {
            $entry->setStatus($status, $comments, $auto_save);
        }

        return $this->setModifiedCount(count($this->source));
    }


    /**
     * Erase (as in SQL DELETE) the specified entries from the database, also erasing their meta data
     *
     * @return static
     */
    public function erase(): static
    {
        $ids  = [];
        $meta = [];

        // Delete the meta data entries
        foreach ($this->source as $id => $entry) {
            $ids[] = $id;

            if (is_array($entry)) {
                $meta[] = $entry['meta_id'];

            } elseif ($entry instanceof DataEntryInterface) {
                $meta[] = $entry->getMetaId();
            }
        }

        if ($ids) {
            // Delete the meta data
            Meta::eraseEntries($meta);

            // Delete the entries themselves
            sql($this->getConnectorObject())->setDebug($this->debug)
                                            ->erase(static::getTable(), ['id' => $ids]);
        }

        return $this;
    }


    /**
     * Deletes ALL entries in this table!
     *
     * This method reads in $size entries at the time, erases them, and continues onto the next until all are erased
     *
     * @param int $size
     *
     * @return void
     */
    public static function truncate(int $size = 10): void
    {
        Log::action(tr('Truncating table ":table"', [':table' => static::getTable()]), echo_newline: false);

        do {
            $iterator = static::new()->setQuery('SELECT * FROM `' . static::getTable() . '` LIMIT ' . $size);
            $iterator->erase();
            Log::dot(1);

        } while ($iterator->getCount());

        Log::success(tr('Done!'));

        Incident::new()
                ->setType('sysop')
                ->setTitle(ts('Mobile Billing Reset'))
                ->setBody(ts('User ":user" performed a truncate on table ":table"', [
                    ':user'  => Session::getUserObject()->getDisplayName(),
                    ':table' => static::getTable()
                ]))
                ->setNotifyRoles('developer')
                ->save();
    }


    /**
     * Returns an array with all id's for the specified entry identifiers
     *
     * @param array $identifiers
     *
     * @return array
     */
    public function listIds(array $identifiers): array
    {
        if ($identifiers) {
            $in = SqlQueries::in($identifiers);

            return sql($this->getConnectorObject())->setDebug($this->debug)
                                                   ->list('SELECT `id`
                                                           FROM   `' . static::getTable() . '`
                                                           WHERE  `' . static::getUniqueColumn() . '` IN (' . implode(', ', array_keys($in)) . ')', $in);
        }

        return [];
    }


    /**
     * Add the specified data entry to the end of the source list
     *
     * @note if no key was specified, the entry will be assigned as-if a new array entry
     *
     * @param mixed                            $value
     * @param Stringable|string|float|int|null $key
     * @param bool                             $skip_null_values
     * @param bool                             $exception
     *
     * @return static
     */
    public function append(mixed $value, Stringable|string|float|int|null $key = null, bool $skip_null_values = true, bool $exception = true): static
    {
        // Skip NULL values?
        if ($value === null) {
            if ($skip_null_values) {
                return $this;
            }
        }

        $key = $this->prepareKey($value, $key);

        return parent::append($value, $key, $skip_null_values, $exception);
    }


    /**
     * Add the specified data entry to the beginning of the source list
     *
     * @note if no key was specified, the entry will be assigned as-if a new array entry
     *
     * @param mixed                      $value
     * @param Stringable|string|float|int|null $key
     * @param bool                       $skip_null_values
     * @param bool                       $exception
     *
     * @return static
     */
    public function prepend(mixed $value, Stringable|string|float|int|null $key = null, bool $skip_null_values = true, bool $exception = true): static
    {
        // Skip NULL values?
        if ($value === null) {
            if ($skip_null_values) {
                return $this;
            }
        }

        $key = $this->prepareKey($value, $key);

        return parent::prepend($value, $key, $skip_null_values, $exception);
    }


    /**
     * Prepares the value to be added to the source
     *
     * @param mixed                            $value
     * @param Stringable|string|float|int|null $key
     *
     * @return string|int
     */
    protected function prepareKey(mixed $value, Stringable|string|float|int|null $key = null): string|int
    {
        // If the value is a DataEntry object, make sure its saved
        if ($value instanceof DataEntryInterface) {
            // If this DataEntry object is NOT modified, DataEntry::save() will automatically not save, this is ok
            $value->save();

        } else {
            // Value might be NULL if we skip NULLs?
            if (is_data_scalar($value)) {
                // Try to load the specified value from the database, assuming $value is the unique identifier
                try {
                    $value = static::getDefaultContentDataType()::new()
                                                                ->setMetaEnabled($this->getMetaEnabled())
                                                                ->load($value);

                } catch (DataEntryNotExistsException $e) {
                    throw new DataEntryNotExistsException(tr('Cannot add specified value ":value" it must be an instance of DataEntryInterface or a unique identifier value for the class ":class"', [
                        ':value' => $value,
                        ':class' => static::getDefaultContentDataType()
                    ]), $e);
                }

                // Now we have a DataEntryInterface type value, we can continue, yay!

            } else {
                if ($value === null) {
                    return $key;
                }

                throw new OutOfBoundsException(tr('Cannot add specified value ":value" it must be an instance of DataEntryInterface', [
                    ':value' => $value,
                ]));
            }
        }

        if ($this->keys_are_unique_column) {
            if ($key) {
                if ($this->require_key_match_unique_identifier) {
                    if (!$value->isNew() and ($key != $value->getUniqueColumnValue())) {
                        // Key must either not be specified or match the id of the DataEntry
                        throw new OutOfBoundsException(tr('Cannot add ":class" class DataEntry with id ":id", the specified key ":key" must either match the value ":value" of the unique column ":unique" or be null', [
                            ':value'  => $value->getUniqueColumnValue(),
                            ':unique' => $value::getUniqueColumn(),
                            ':class'  => $value::class,
                            ':id'     => $value->getId() ?? 'N/A',
                            ':key'    => $key,
                        ]));
                    }
                }

                // Either the specified DataEntry object has no value for its unique column, or the unique column
                // matches the specified key. Either way, we're good to go

            } else {
                $key = $value->getUniqueColumnValue();

                if (!$key) {
                    throw new OutOfBoundsException(tr('Cannot add entry ":value" because the ":class" DataIterator object should use unique column ":column" as keys, but has no unique column value', [
                        ':column' => $value->getUniqueColumn(),
                        ':value'  => $value,
                        ':class'  => static::class,
                    ]));
                }
            }

        } else {
            if ($key) {
                if ($this->require_key_match_unique_identifier) {
                    if ($key != $value->getId()) {
                        // Key must either not be specified or match the id of the DataEntry
                        throw new OutOfBoundsException(tr('Cannot add ":class" class DataEntry with id ":id" and unique column value ":unique", the specified key ":key" must either match the id, unique column value, or be null', [
                            ':class'  => $value::class,
                            ':id'     => $value->getId(),
                            ':unique' => $value->getUniqueColumnValue(),
                            ':key'    => $key,
                        ]));
                    }
                }

                // Either the specified DataEntry object is new or the id matches the specified key, we're good to go
            } else {
                // Key was not specified, use the ID from the DataEntry object as key
                $key = $value->getId();
            }
        }

        return $key;
    }


    /**
     * Clears all entries in this DataIterator, but also all entries in this iterator from the table
     *
     * @note: Clearing means that the entries will NOT be deleted, it will set the status for all entries to "deleted"
     *        and update the unique column to NULL
     *
     * @return static
     */
    public function clearIteratorFromTable(): static
    {
        foreach ($this->source as $entry) {
            $this->ensureObject($entry)
                     ->setStatus('deleted')
                     ->setUniqueColumnValue(null)
                     ->save();
        }

        return parent::clear();
    }


    /**
     * Clears all entries in this DataIterator, but also ALL entries from the table
     *
     * @param string|bool|null $status
     * @todo This method is utterly useless as its only use is deleting every entry in a database. Rewrite the entire setStatus set methods
     *       There should be 2 methods: setStatus on the current entry in the table, and setStatus on all entries specified in a query
     *
     * @return static
     */
    public function deleteAllFromTable(string|bool|null $status = false): static
    {
        if ($status === false) {
            $results = sql()->listKeyValues('SELECT `id` FROM `' . static::getTable() . '`');

        } else {
            $execute = [':status' => $status];
            $results = sql()->listKeyValues('SELECT `id` FROM `' . static::getTable() . '` WHERE' . SqlQueries::is('status', $status, 'status', $execute), $execute);
        }

        if ($results) {
            $this->source = $results;

            foreach ($results as $entry) {
                Log::action(ts('Deleting ":class" entry with id ":id"', [
                    ':class' => static::class,
                    ':id'    => $entry['id'],
                ]), 2);

                $this->ensureObject($entry['id'])
                     ->setStatus('deleted')
                     ->setUniqueColumnValue(null)
                     ->save();
            }

            return parent::clear();
        }

        return $this;
    }


    /**
     * Creates a new DataEntry object and returns it
     *
     * @param IdentifierInterface|array|string|int|null $identifier
     *
     * @return DataEntryInterface
     */
    protected function loadObject(IdentifierInterface|array|string|int|null $identifier): DataEntryInterface
    {
        return $this->getAcceptedDataType()::new()
                                           ->setDebug($this->debug)
                                           ->setMetaEnabled($this->getMetaEnabled())
                                           ->setRestrictionsObject($this->o_restrictions)
                                           ->setConnectorObject($this->getConnectorObject())
                                           ->loadOrThis($identifier);
    }


    /**
     * Ensure the entry we're going to return is from DataEntryInterface interface
     *
     * @param string|float|int $key
     * @param bool             $force
     *
     * @return DataEntryInterface|null
     */
    #[ReturnTypeWillChange] protected function ensureObject(string|float|int $key, bool $force = false): mixed
    {
        if ($this->ensure_objects) {
            // Ensure the source key is of DataEntryInterface
            if (!$this->source[$key] instanceof DataEntryInterface) {
                if (is_array($this->source[$key])) {
                    // Source is stored as an array. Create a new DataEntry and copy the source array into the entry
                    if ($this->inject_source_directly) {
                        $entry = $this->getAcceptedDataType()::new()
                                                             ->setDebug($this->getDebug())
                                                             ->setMetaEnabled($this->getMetaEnabled())
                                                             ->setSourceDirect($this->source[$key]);

                    } else {
                        $entry = $this->getAcceptedDataType()::new()
                                                             ->setDebug($this->getDebug())
                                                             ->setMetaEnabled($this->getMetaEnabled())
                                                             ->setSource($this->source[$key]);
                    }

                } elseif ($this->source[$key] === null) {
                    return null;

                } else {
                    // Load the entry manually from DB. REQUIRES the DataEntry object to have a unique column specified!
                    $entry = $this->loadObject($this->source[$key]);
                }

                $this->source[$key] = $entry->setDebug($this->debug)
                                            ->setColumns($this->columns);
            }
        }

        return $this->source[$key];
    }


    /**
     * Returns the current entry
     *
     * @note overrides the IteratorCore::current() method which returns mixed
     *
     * @return mixed
     */
    #[ReturnTypeWillChange] public function current(): mixed
    {
        return $this->ensureObject(key($this->source));
    }


    /**
     * Returns the first element contained in this object without changing the internal pointer
     *
     * @return DataEntryInterface|null
     */
    #[ReturnTypeWillChange] public function getFirstValue(): ?DataEntryInterface
    {
        return $this->ensureObject(array_key_first($this->source));
    }


    /**
     * Returns the last element contained in this object without changing the internal pointer
     *
     * @return DataEntryInterface|null
     */
    #[ReturnTypeWillChange] public function getLastValue(): ?DataEntryInterface
    {
        return $this->ensureObject(array_key_last($this->source));
    }


    /**
     * Shift an entry off the beginning of this Iterator
     *
     * @return DataEntryInterface|null
     */
    #[ReturnTypeWillChange] public function extractFirstValue(): ?DataEntryInterface
    {
        return $this->ensureObject(parent::extractFirstValue());
    }


    /**
     * Prepend elements to the beginning of an array
     *
     * @return mixed
     */
    public function extractLastValue(mixed ...$values): static
    {
        foreach ($values as $value) {
            if (($value !== null) and !($value instanceof DataEntryInterface)) {
                throw OutOfBoundsException::new(tr('Cannot unshift value ":value" to this iterator, the value must be an DataEntryInterface object', [
                    ':value' =>  get_class_or_datatype($value)
                ]))->setData([
                    'value' => $value
                ]);
            }
        }

        return parent::extractLastValue($values);
    }


    /**
     * Returns a cache key for this object
     *
     * @return string|null
     */
    public function getCacheKeySeed(): ?string
    {
        return PROJECT . '#DataIterator#' . static::class . '#' . Json::encode([static::getTableState() . '-' . $this->getQueryHash()], force_single_line: true);
    }


    /**
     * Load the Iterator list data from the database for use with auto complete
     *
     * This method will load only the specified column and automatically like filter on identifier [name => word%]
     *
     * @param string|null $word   The word to filter on, if any. If no word is specified, all results will be returned
     * @param string|null $column The column to filter on. If not specified, will default to the unique column for this
     *                            DataIterator
     *
     * @return static
     * @todo Add support for specifying which column should be the identifier column instead of only id_column or unique_column
     */
    public function loadForAutocomplete(?string $word = null, ?string $column = null): static
    {
        if ($column === 'id') {
            throw new OutOfBoundsException(tr('Cannot use auto complete on "id" column'));
        }

        $column = $column ?? $this->getUniqueColumn();

        return $this->setColumns(['id', $column])->load([$column => $word . '%'], true)->getAllRowsSingleColumn('name');
    }


    /**
     * Load the Iterator list data from the database
     *
     * @param array|string|int|null $identifiers
     * @param bool                  $like
     *
     * @return static
     * @todo Add support for specifying which column should be the identifier column instead of only id_column or unique_column
     */
    public function load(array|string|int|null $identifiers = null, bool $like = false): static
    {
        $this->setIsLoading(true)
             ->selectQuery($identifiers, $like);

        cache('dataentries')->get($this->getCacheKey(), function ()  use ($identifiers) {
            if (empty($this->source)) {
                $this->source = sql($this->getConnectorObject())->setDebug($this->debug)
                                                                ->listKeyValues($this->query, $this->execute, $this->keys_are_unique_column ? $this->getUniqueColumn() : $this->getIdColumn());

                if (static::getConfigurationPath()) {
                    $this->source = array_merge($this->source, $this->loadFromConfiguration());
                }

            } else {
                $this->source = array_merge(
                    $this->source,
                    sql($this->getConnectorObject())->setDebug($this->debug)
                                                    ->listKeyValues(
                                                        $this->query,
                                                        $this->execute,
                                                        static::getUniqueColumn()));
            }

            $this->is_loaded  = true;
            $this->is_loading = false;
        });

        return $this;
    }


    /**
     * Load configuration from the specified configuration path
     *
     * @return array
     */
    protected function loadFromConfiguration(): array
    {
        $source      = config()->getArray(Strings::ensureEndsNotWith(static::getConfigurationPath(), '.'), []);
        $entry       = static::getDefaultContentDataType();
        $entry       = new $entry();
        $o_definitions = $entry->getDefinitionsObject();

        // Ensure all entry definition columns are available, apply default values where they don't
        foreach ($source as &$value) {
            $value['status'] = 'configuration';

            foreach ($o_definitions as $column => $o_definition) {
                if (array_key_exists($column, $value)) {
                    continue;
                }

                // Apply the default value for this column
                $value[$column] = $o_definition->getDefault();
            }
        }

        unset($value);
        return $source;
    }


    /**
     * Check if the datatype of the given value or Interface (in case of an object) is allowed
     *
     * Throws an OutOfBounds exception if the datatype or Interface is not allowed
     *
     * @param mixed                            $value
     * @param Stringable|string|float|int|null $key
     *
     * @return mixed
     * @throws IteratorDataTypeNotAcceptedException | IteratorValidatorFailedException
     */
    protected function checkDataTypeAndContent(mixed $value, Stringable|string|float|int|null $key = null): mixed
    {
        if (is_array($value)) {
            // Since values may only be DataEntry type objects, convert arrays to the correct DataEntry object type
            if ($this->inject_source_directly) {
                $value = $this->getAcceptedDataType()::new()
                                                     ->setDebug($this->getDebug())
                                                     ->setMetaEnabled($this->getMetaEnabled())
                                                     ->setSourceDirect($value);

            } else {
                $value = $this->getAcceptedDataType()::new()
                                                     ->setDebug($this->getDebug())
                                                     ->setMetaEnabled($this->getMetaEnabled())
                                                     ->Source($value);
            }
        }

        return parent::checkDataTypeAndContent($value, $key);
    }


    /**
     * Returns an array of
     *
     * @param string|null $word
     *
     * @return array
     */
    public function autoCompleteFind(?string $word = null): array
    {
        return sql($this->getConnectorObject())->setDebug($this->debug)
                                               ->listKeyValue('SELECT `id`, `' . static::getUniqueColumn() . '`
                                                               FROM   `' . static::getTable() . '`' .
                                                    ($word ? ' WHERE  `' . static::getUniqueColumn() . '` LIKE :like' : null) . '
                                                               LIMIT   ' . CliAutoComplete::getLimit(),
                                                     $word ? [':like' => $word . '%'] : null);
    }


    /**
     * Ensures that all objects in the source are DataEntry objects
     *
     * @return static
     */
    protected function ensureDataEntries(): static
    {
        foreach ($this->source as $key => $value) {
            $this->ensureObject($key);
        }

        return $this;
    }


    /**
     * Sets if this DataIterator is currently loading data from the database
     *
     * @param bool $is_loading
     *
     * @return DataIteratorCore
     */
    protected function setIsLoading(bool $is_loading): static
    {
        $this->is_loading = $is_loading;
        return $this;
    }


    /**
     * Returns true if this DataIterator is currently loading data from the database
     *
     * @return bool
     */
    public function isLoading(): bool
    {
        return $this->is_loading;
    }


    /**
     * Returns true if this DataIterator has data loaded into it's source
     *
     * Data will be considered loaded into the source if either it was specified as a source during constructor, or
     * whendata was loaded using the DataIterator::load() method
     *
     * @return bool
     */
    public function isLoaded(): bool
    {
        return $this->is_loaded;
    }


    /**
     * Returns the number of entries that have been modified
     *
     * @return int
     */
    public function getModifiedCount(): int
    {
        return $this->modified_count;
    }


    /**
     * Sets the number of entries that have been modified
     *
     * @param int $count
     *
     * @return static
     */
    protected function setModifiedCount(int $count): static
    {
        $this->modified_count = $count;
        return $this;
    }


    /**
     * Returns the number of entries that have been saved
     *
     * @return int
     */
    public function getSavedCount(): int
    {
        return $this->saved_count;
    }


    /**
     * Sets the number of entries that have been saved
     *
     * @param int $count
     *
     * @return static
     */
    protected function setSavedCount(int $count): static
    {
        $this->saved_count = $count;
        return $this;
    }


    /**
     * Apply the specified data source over the current source
     *
     * @param bool                           $require_clean_source
     * @param ValidatorInterface|array|null &$source
     *
     * @return static
     */
    public function apply(bool $require_clean_source = true, ValidatorInterface|array|null &$source = null): static
    {
        if ($this->readonly) {
            throw new DataEntryReadonlyException(tr('Cannot apply changes to ":name" object, the object is readonly', [
                ':name' => static::class,
            ]));
        }

        // Place source in a validator
        $o_validator = Validator::pick($source);
        $source    = Arrays::groupByPrefix($o_validator->getSource(), non_prefix_action: Arrays::GROUP_BY_DROP);

        // First, ensure we have all the entries specified by the source
        if ($require_clean_source) {
            try {
                foreach ($source as $data_entry_id => $data_entry_source) {
                    $this->get($data_entry_id);
                }

            } catch (NotExistsException $e) {
                throw new ValidationFailedException(tr('Cannot apply changes to ":id", the specified DataEntry does not exist', [
                    ':id' => $data_entry_id,
                ]), $e);
            }
        }

        // Apply will first validate, so we know ALL has been validated before we're saving
        foreach ($source as $data_entry_id => $data_entry_source) {
            $this->get($data_entry_id, $require_clean_source)?->apply(true, $data_entry_source);
        }

        // Require clean source
        if ($require_clean_source) {
            $o_validator->validate($require_clean_source);
        }

        return $this;
    }


    /**
     * Saves each DataEntry object stored in this DataIterator
     *
     * @param bool        $force
     * @param bool        $skip_validation
     * @param string|null $comments
     *
     * @return static
     */
    public function save(bool $force = false, bool $skip_validation = false, ?string $comments = null): static
    {
        $this->saved_count = 0;

        foreach ($this as $entry) {
            if ($entry) {
                $entry->save($force, $skip_validation, $comments);

                if ($entry->isSaved()) {
                    $this->saved_count++;
                }
            }
        }

        return $this;
    }


    /**
     * Sets the columns that this DataIterator will load for each entry
     *
     * @param ArrayableInterface|array|string|null $columns
     *
     * @return static
     */
    public function setColumns(ArrayableInterface|array|string|null $columns): static
    {
        // Tell the QueryBuilder object to only use the specified columns
        $this->__setColumns($columns);
        $this->getQueryBuilderObject()->setSelects($this->getSqlSelectColumns());

        return $this;
    }
}
