#!/usr/bin/php
<?php

use Phoundation\Content\Images\Image;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Exception\Exceptions;
use Phoundation\Filesystem\Restrictions;



/**
 * Script system/image/convert
 *
 * This script can apply various conversions to the specified image
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system image convert IMAGE';

$help  = 'This script can apply various conversions to the specified image';

ArgvValidator::new()
    ->select('method')->isName()
    ->select('file')->isExistingFile()
    ->validate();

// Validate arguments
if (!$argv['file']) {
    throw Exceptions::OutOfBoundsException(tr('No image specified'))->makeWarning();
}

// Get image object
$image = Image::new(Restrictions::new(PATH_DATA, true))->setFile($argv['file']);
$image->convert()->crop();

// Display image information
Log::information(tr('Displaying image information for ":file"', [':file' => $argv['file']]));
