#!/usr/bin/php
<?php

use Phoundation\Cli\Cli;
use Phoundation\Content\Images\Image;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Exception\Exceptions;



/**
 * Script system/image/info
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system image info IMAGE_FILE_NAME';

$help  = 'This script will display basic information about the specified image';

$arguments = ArgvValidator::new()
    ->select('file', true)->isExistingFile()
    ->validate()
    ->extract(true);

// Validate arguments
if (!$arguments['file']) {
    throw Exceptions::OutOfBoundsException(tr('No image specified'))->makeWarning();
}

// Get image object
$image = Image::new($arguments['file'], PATH_DATA);

// Display image information
Log::information(tr('Displaying image information for ":file"', [':file' => $arguments['file']]));
Cli::displayArray($image->getInformation());