#!/usr/bin/php
<?php
use Phoundation\Cli\Script;
use Phoundation\Content\Images\Image;
use Phoundation\Filesystem\Restrictions;
use Phoundation\Servers\Localhost;


/**
 * Script system/image/info
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\System
 */
$usage = './cli system image info';

$help  = 'This script will display basic information about the specified image';

$file         = Script::argument();
$restrictions = Restrictions::new(PATH_ROOT);

Script::noArgumentsLeft();

// Validate arguments
if (!$file) {
    throw new \Phoundation\Exception\OutOfBoundsException(tr('No image specified'));
}

// Get image object
$image = Image::new(Localhost::new(PATH_DATA))->setFile($file);

// Display image information
showdie($image->getInformation());