#!/usr/bin/php
<?php

use Phoundation\Cli\Cli;
use Phoundation\Content\Images\Image;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/image/info
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system image info IMAGE_FILE_NAME';

$help  = 'This script will display basic information about the specified image';



// Validate arguments
ArgvValidator::new()
    ->select('file', true)->isExistingFile()
    ->noArgumentsLeft()
    ->validate();



// Get image object
$image = Image::new($argv['file'], PATH_DATA);



// Display image information
Log::information(tr('Displaying image information for ":file"', [':file' => $argv['file']]));
Cli::displayTable($image->getInformation());