#!/usr/bin/php
<?php

use Phoundation\Cli\Cli;
use Phoundation\Cli\Script;
use Phoundation\Content\Images\Image;
use Phoundation\Core\Log;
use Phoundation\Exception\Exceptions;
use Phoundation\Filesystem\Restrictions;
use Phoundation\Servers\Server;


/**
 * Script system/image/convert
 *
 * This script can apply various conversions to the specified image
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\System
 */
$usage = './cli system image resize IMAGE';

$help  = 'This script can apply various conversions to the specified image';

$method       = Script::argument('-m,--method', false, 'scale');
$width        = Script::integerArgument('-x,--width');
$height       = Script::integerArgument('-y,--height');
$file         = Script::argument();
$restrictions = Restrictions::new(PATH_ROOT);

Script::noArgumentsLeft();

// Validate arguments
if (!$file) {
    throw Exceptions::OutOfBoundsException(tr('No image specified'))->makeWarning();
}

// Get image object
$image = Image::new($file, Server::new(PATH_DATA));

// Display image information
Log::information(tr('Resizing image ":file" to ":xx:y"', [
    ':x' => $width,
    ':y' => $height,
    ':file' => $file
]));

$backup = $image->backup();
$backup->view();

$image->convert()->resize()->setMethod($method)->absolute($width, $height);
$image->view();