#!/usr/bin/php
<?php

use Phoundation\Content\Images\Image;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/image/convert
 *
 * This script can apply various conversions to the specified image
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system image resize IMAGE_FILE_NAME -x 500 -y 500 -m scale';

$help  = 'This script can apply various conversions to the specified image



ARGUMENTS



-x, --width WIDTH                       Width of the image
-y, --height HEIGHT                     Height of the image
-m, --method METHOD                     Resizing method (scale, sample, resample)
-t, --type                              Resizing type ';

// Validate command line arguments
$arguments = ArgvValidator::new()
    ->select('-m,--method', true)->isOptional('scale')->isName()
    ->select('-x,--width', true)->isInteger()
    ->select('-y,--height', true)->isInteger()
    ->select('file')->isExistingFile()
    ->validate()
    ->extract(true);

// Get image object
$image = Image::new($arguments['file'], PATH_DATA);

// Display image information
Log::information(tr('Resizing image ":file" to ":xx:y"', [
    ':x' => $arguments['width'],
    ':y' => $arguments['height'],
    ':file' => $arguments['file']
]));

$backup = $image->backup();
$backup->view();

$image->convert()
    ->resize()
    ->setMethod($arguments['method'])
    ->absolute($arguments['width'], $arguments['height']);

$image->view();