#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Servers\Server;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;


/**
 * Script system/servers/create
 *
 * This script will create a new server with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::autoComplete(Server::getAutoComplete());

Documentation::usage('./pho system servers create [OPTIONS]
./cli system servers create --name phoundation --hostname www.phoundation.org -d "This is a phoundation server" --port 22');

Documentation::help(Server::getHelp('This script allows you to create servers



ARGUMENTS'));


// Create server.
$server = Server::new()->create();


// Done!
Log::success(tr('Created new server ":server"', [':server' => $server->getHostName()]));