#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Servers\Servers;


/**
 * Script system/servers/list
 *
 * This script will list the available servers on this system
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./cli system servers list [OPTIONS]
./cli system servers list -D');

Documentation::help('This script will list the configured servers on this system



ARGUMENTS


[-D / --deleted]                       Will also show deleted servers');



// Validate arguments
$argv = ArgvValidator::new()
    ->noArgumentsLeft()
    ->validate();



// Display the available servers
Servers::new()
    ->addFilter('status', (DELETED ? 'deleted' : null))
    ->CliDisplayTable();