<?php

/**
 * Class Events
 *
 * This class adds event handling support to your classes
 *
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Events 2
 * @copyright Copyright © 2025 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Utils
 */


declare(strict_types=1);

namespace Phoundation\Utils;

use Phoundation\Data\IteratorCore;
use Phoundation\Data\Traits\TraitDataArraySource;
use Stringable;

class Events extends IteratorCore
{
    use TraitDataArraySource;


    /**
     *
     *
     * @param mixed                            $value
     * @param float|Stringable|int|string|null $key
     * @param bool                             $skip_null_values
     * @param bool                             $exception
     *
     * @return $this
     */
    public function add(mixed $value, float|Stringable|int|string|null $key = null, bool $skip_null_values = true, bool $exception = true): static
    {
        return parent::add($value, $key, $skip_null_values, $exception); // TODO: Change the autogenerated stub
    }
}
