#!/usr/bin/php
<?php

use Phoundation\Accounts\Exception\AccountsException;
use Phoundation\Accounts\Roles\Role;
use Phoundation\Accounts\Users\User;
use Phoundation\Cli\Cli;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;



/**
 * Script system/accounts/users/info
 *
 * This script displays information about the specified user.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system accounts users info USER';

$help  = 'This script displays information about the specified user.  



ARGUMENTS



USER                                    The user to display information about. Specify either by user id or email 
                                        address';



// Validate arguments
ArgvValidator::new()
    ->select('user')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->validate();



// Display user data
Cli::displayTable(User::get($argv['user'])->getData());