#!/usr/bin/php
<?php

use Phoundation\Accounts\Rights\Rights;
use Phoundation\Data\Validator\ArgvValidator;



/**
 * Script system/accounts/rights/list
 *
 * This script will list the available rights on this system
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system accounts rights list [OPTIONS]
./cli system accounts rights list -d -r god';

$help  = 'This script will list the available rights on this system



ARGUMENTS


-d / --details                          Will show more details about each role

--deleted                               Will also show deleted rights

-r/--role ROLE                          Will only display rights with the specified role';



// Validate arguments
ArgvValidator::new()
    ->select('-d,--details')->isOptional(false)->isBoolean()
    ->select('-r,--rights,--role', true)->isOptional(null)->isName()
    ->validate();


Rights::new()
    ->addFilter('rights', $argv['rights'])
    ->addFilter('status', (DELETED ? 'deleted' : null))
    ->CliDisplayTable();