#!/usr/bin/php
<?php

use Phoundation\Accounts\Rights\Right;
use Phoundation\Core\Log;
use Phoundation\Data\Validator\ArgvValidator;



/**
 * Script system/accounts/rights/create
 *
 * This script will create a new right with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system accounts right create -n NAME [OPTIONS]
./cli system accounts right create -n test -d "This is a test right!"';

$help  = 'This script allows you to create rights



ARGUMENTS



-n / --name                             The name for the right

[-d / --description]                    The description for the right';



// Validate arguments
ArgvValidator::new()
    ->select('right', true)->isName()
    ->select('-n,--name', true)->isOptional(null)->isName()
    ->select('-d,--description', true)->isOptional(null)->isDescription()
    ->validate();



// Create right and save it
$right = Right::get($argv['right'])
    ->setName($argv['name'])
    ->setDescription($argv['description'])
    ->save();



// Done!
Log::success(tr('Modified right ":right"', [':right' => $right->getName()]));