<?php

namespace Phoundation\Security\Incidents;

use Templates\AdminLte\Components\DataEntryForm;



/**
 * Class FilterForm
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Security
 */
class FilterForm extends DataEntryForm
{
    /**
     * FilterForm class constructor
     */
    public function __construct()
    {
        parent::__construct();

        $this->keys = [
            'type[]'   => [
                'label'    => tr('Type'),
                'element'  => 'select',
                'source'   => [
                    'type'     => tr('Type'),
                    'severity' => tr('Severity')
                ],
            ],
            'filter[]' => [
                'label'    => tr('Filter'),

            ],
        ];

        $this->form_keys = [
            'type[]'   => 6,
            'filter[]' => 6,
        ];
    }



    /**
     * @param array|null $source
     * @return $this
     */
    public function setSource(?array $source): static
    {
        return parent::setSource($source); // TODO: Change the autogenerated stub
    }
}