#!/usr/bin/php
<?php

use Phoundation\Accounts\Exception\AccountsException;
use Phoundation\Accounts\Roles\Role;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Log;
use Phoundation\Data\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;



/**
 * Script system/accounts/roles/create
 *
 * This script will create a new role with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./cli system accounts roles create NAME [OPTIONS]
./cli system accounts roles create test -d "This is a test role!"');

Documentation::help('This script allows you to create roles



ARGUMENTS



NAME                                    The name for the role

[-d / --description]                    The description for the role');



// Validate arguments
ArgvValidator::new()
    ->select('name', true)->isName()
    ->select('-d,--description', true)->isOptional(null)->isDescription()
    ->select('-r,--rights,--right', true)->isOptional(null)->sanitizeForceArray()->each()->isName()
    ->noArgumentsLeft()
    ->validate();



// Check if the role already exists
if (Role::exists($argv['name'])) {
    throw AccountsException::new(tr('Cannot create role with name ":name", it already exists', [
        ':name' => $argv['name']
    ]))->makeWarning();
}



try {
    // Ensure that specified roles exist
    if ($argv['rights']) {
        foreach ($argv['rights'] as &$right) {
            $right = Role::get($right);
        }

        unset($right);
    }

}catch (DataEntryNotExistsException $e) {
    throw $e->makeWarning();
}



// Create role and save it
$role = Role::new()
    ->setName($argv['name'])
    ->setDescription($argv['description'])
    ->save();



// Set the rights for this role
$role->rights()->set($argv['rights']);



// Done!
Log::success(tr('Created new role ":role"', [':role' => $role->getName()]));