#!/usr/bin/php
<?php

use Phoundation\Accounts\Roles\Role;
use Phoundation\Cli\Cli;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/accounts/roles/info
 *
 * This script displays information about the specified role.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system accounts roles info USER';

$help  = 'This script displays information about the specified role.  



ARGUMENTS (All arguments in square brackets are optional)



USER                                    The role to display information about. Specify either by role id or seo-name';



// Validate arguments
ArgvValidator::new()
    ->select('role')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->noArgumentsLeft()
    ->validate();



try {
    // Display role data
    Cli::displayForm(Role::get($argv['role'])->getData());

}catch (DataEntryNotExistsException $e) {
    throw $e->makeWarning();
}
