#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Libraries\Libraries;
use Phoundation\Developer\Project\Project;


/**
 * This is the init script for the project. Run this script to ensure that the database is running with the same version
 * as the code
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Core
 */
Documentation::usage('./cli system project init [OPTIONS]
./cli system project init --drop
./cli system project init --import');

Documentation::help('This script allows you to setup a new project



ARGUMENTS



[--drop]                                Drops the system database and start init from version 0.0.0 

[--force]                               (SYSTEM FLAG) If set, will run import (That is, truncate old data and import 
                                        new) even if data was already available 

[--import]                              Run import for all libraries that support it. This will automatically import all 
                                        data for all systems. Since this requires (amongst things) downloading and 
                                        importing (sometimes) very large data sets, this may take a little while

-l / --library LIBRARY                  Only initialize the specified library

-p / --plugins                          Only initalize plugin libraries
                                       
-s / --system                           Only initialize system libraries
                                       
-t / --templates                        Only initialize template libraries
                                       
-c / --comments                         The optional comments to add in the versions table about this init');



// Get command line arguments
ArgvValidator::new()
    ->select('--drop')->isOptional(false)->isBoolean()
    ->select('--import')->isOptional(false)->isBoolean()
    ->select('-c,--comments', true)->isOptional()->isPrintable()
    ->select('-l,--library', true)->isOptional()->isVariable()
    ->select('-p,--plugins')->isOptional(true)->isBoolean()
    ->select('-s,--system')->isOptional(true)->isBoolean()
    ->select('-t,--templates')->isOptional(true)->isBoolean()
    ->noArgumentsLeft()
    ->validate();



// Drop the database and start from scratch? DANGER!
if ($argv['drop']) {
    Libraries::reset();
}



// Initialize the system
Libraries::initialize($argv['system'], $argv['plugins'], $argv['templates'], $argv['comments'], $argv['library']);



// Run import?
if ($argv['import']) {
    Project::import();
}



//    // During init, force EMULATE_PREPARES because loads of init stuff will NOT work without
//    foreach ($_CONFIG['db'] as $name => &$connector) {
//        if ($name == 'default') continue;
//
//        if (!empty($connector['init'])) {
//            $connector['pdo_attributes'] = array(PDO::ATTR_EMULATE_PREPARES => true,
//                PDO::ATTR_STRINGIFY_FETCHES => true);
//        }
//    }

