#!/usr/bin/php
<?php

use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\System\Libraries;



/**
 * This is the init script for the project. Run this script to ensure that the database is running with the same version
 * as the code
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Core
 */



// Get command line arguments
ArgvValidator::new()
    ->select('--drop')->isOptional(false)->isBoolean()
    ->select('-s,--system')->isOptional(true)->isBoolean()
    ->select('-p,--plugins')->isOptional(true)->isBoolean()
    ->select('-l,--library', true)->isOptional(true)->isBoolean()
    ->select('-c,--comments', true)->isOptional(true)->isBoolean()
    ->noArgumentsLeft()
    ->validate();



// Drop the database and start from scratch? DANGER!
if ($argv['drop']) {
    Libraries::reset();
}



// Initialize the system
Libraries::initialize($argv['system'], $argv['plugins'], $argv['comments'], $argv['library']);

//    // During init, force EMULATE_PREPARES because loads of init stuff will NOT work without
//    foreach ($_CONFIG['db'] as $name => &$connector) {
//        if ($name == 'default') continue;
//
//        if (!empty($connector['init'])) {
//            $connector['pdo_attributes'] = array(PDO::ATTR_EMULATE_PREPARES => true,
//                PDO::ATTR_STRINGIFY_FETCHES => true);
//        }
//    }

