#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Project\Project;



/**
 * Script system/accounts/users/authenticate
 *
 * This script can be used to test the authentication for the specified user
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */

Documentation::usage('./cli system project update [OPTIONS]
./cli system project update --check
./cli system project update
');

Documentation::help('This script will update your Phoundation libraries and list


ARGUMENTS


[-c / --check]                          If specified will only check for available updates');



// Get command line arguments
ArgvValidator::new()
    ->select('-c,--check')->isOptional()->isBoolean()
    ->noArgumentsLeft()
    ->validate();



if ($argv['local']) {
    Log::information(tr('Pulling updates from local Phoundation installation...'));
    Project::updateLocal();
} elseif ($argv['check']) {
    Log::information(tr('Checking for Phoundation updates...'));
    Project::checkUpdates();
} else {
    Log::information(tr('Updating Phoundation...'));
    Project::update();
}