#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Accounts\Roles\Role;
use Phoundation\Accounts\Users\User;
use Phoundation\Cli\CliDocumentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Utils\Config;


/**
 * Script accounts/roles/add-roles
 *
 * This script will create a new role with the specified properties
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyrole Copyrole (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
CliDocumentation::autoComplete([
    'positions' => [
        0 => [
            'word'   => 'SELECT `email` FROM `accounts_users` WHERE `email` LIKE :word AND `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50),
            'noword' => 'SELECT `email` FROM `accounts_users` WHERE `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50)
        ],
        -1 => [
            'word'   => 'SELECT `name` FROM `accounts_roles` WHERE `name` LIKE :word AND `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50),
            'noword' => 'SELECT `name` FROM `accounts_roles` WHERE `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50)
        ]
    ],
]);

CliDocumentation::usage('./pho accounts users add-roles NAME "ROLE[,ROLE,ROLE,...]"
./pho system accounts users add-roles -n test -d "This is a test role!"');

CliDocumentation::help('This script allows you to add roles to the specified user



ARGUMENTS



EMAIL                                   The identifier email of the user to which the roles should be added

ROLE[,ROLE,ROLE,...]                    The roles linked with the role. Each user that gets this role assigned will 
                                        also get these roles assigned');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('user', true)->isEmail()
    ->select('roles', true)->isOptional(null)->sanitizeForceArray()->each()->isName()
    ->validate();


try {
    // Ensure that specified roles exist
    if ($argv['roles']) {
        foreach ($argv['roles'] as &$role) {
            $role = Role::get($role);
        }

        unset($role);
    }

    // Get role and add roles
    $user = User::get($argv['user']);
    $user->getRoles()->add($argv['roles']);

}catch (DataEntryNotExistsException $e) {
    throw $e->makeWarning();
}


// Done!
Log::success(tr('Modified user ":user"', [':user' => $user->getName()]));
