#!/usr/bin/php
<?php

use Phoundation\Accounts\Users\User;
use Phoundation\Core\Log\Log;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script accounts/users/info
 *
 * This script displays information about the specified user.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './pho accounts users info USER';

$help  = 'This script displays information about the specified user.  



ARGUMENTS



USER                                    The user to display information about. Specify either by user id or email 
                                        address';


// Validate arguments
$argv = ArgvValidator::new()
    ->select('user')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->validate();


$user = User::get($argv['user']);

// Display user data
$user->getCliForm();

Log::information('Alternative email accounts for this user:');
$user->getEmails()->CliDisplayTable();

Log::information('Roles assigned to this user:');
$user->getRoles()->CliDisplayTable();

Log::information('Roles assigned to this user through its roles:');
$user->getRights()->CliDisplayTable();
