#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Accounts\Users\User;
use Phoundation\Cli\Cli;
use Phoundation\Cli\CliCommand;
use Phoundation\Cli\CliDocumentation;
use Phoundation\Core\Config;
use Phoundation\Core\Log\Log;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script accounts/users/authenticate
 *
 * This script can be used to test the authentication for the specified user
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */

CliDocumentation::autoComplete(User::getAutoComplete([
    'positions' => [
        0 => [
            'word'   => 'SELECT `email` FROM `accounts_users` WHERE `email` LIKE :word AND `status` IS NULL',
            'noword' => 'SELECT `email` FROM `accounts_users` WHERE `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50)
        ]
    ],
]));
CliDocumentation::usage('./pho accounts users password USER
echo PASSWORD | ./pho accounts users password USER');
CliDocumentation::help('This script can be used to test the authentication for the specified user

This command accepts the password through a command line pipe in which case it will run in non-interactive mode

NOTE: This script is interactive as it asks the password for the user on the command line! 

NOTE This can run into non-interactive mode and accept the password through a CLI pipe. See USAGE for an example of this 


ARGUMENTS


-');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('user')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->validate();


// Read password from stdin stream?
if (CliCommand::hasStdInStream()) {
    $argv['password'] = CliCommand::readStdInStream();
    $argv['password_validate'] = $argv['password'];

} else {
    // Read password in interactive mode instead
    $argv['password'] = Cli::readPassword(tr('Please type the users password:'));
    $argv['password_validate'] = Cli::readPassword(tr('Please re-type the users password:'));
}


// Get user and update password
try {
    $user = User::get($argv['user'])->setPassword($argv['password'], $argv['password_validate']);

}catch (DataEntryNotExistsException $e) {
    throw $e->makeWarning();
}


// Done!
Log::success(tr('Successfully set new password for user ":user"', [':user' => $user->getDisplayName()]));
