#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Accounts\Users\User;
use Phoundation\Cli\CliDocumentation;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script accounts/users/unlock
 *
 * This script can unlock users
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */

CliDocumentation::autoComplete(User::getAutoComplete([
    'positions' => [
        0 => [
            'word'   => 'SELECT `email` FROM `accounts_users` WHERE `email` LIKE :word AND `status` IS NULL',
            'noword' => 'SELECT `email` FROM `accounts_users` WHERE `status` IS NULL LIMIT ' . Config::getInteger('shell.autocomplete.limit', 50)
        ]
    ]
]));

CliDocumentation::usage('./pho accounts users unlock USER_EMAIL');

CliDocumentation::help('This script will unlock the specified user. Note that unlocked users will have the status
 updated to NULL


ARGUMENTS


USER_EMAIL                              The email address for the user to unlock');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('user')->isEmail()
    ->validate();


// Unlock this user
User::get($argv['user'])->unlock();
