#!/usr/bin/php
<?php
/*
 * Execute all test scripts
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test');

/*
 * Empty command line arguments so that
 */
$path     = ROOT.'scripts/tests/';
$argv     = array();
$skiplist = array('.',
                  '..',
                  '.test',
                  'all',
                  'empty'); // Empty is a template script, dont execute it!

foreach(scandir($path) as $file) {
    try{
        if (in_array($file, $skiplist)) continue;

        /*
         * Create temporary test file that does not contain the shell hashbang header
         */
        log_console(tr('Executing ":test" tests', array(':test' => $file)), 'white');
        script_exec(array('commands' => array('tests/'.$file)));

    }catch(Exception $e) {
        log_console($e, 'warning/'.$e->getCode());
    }
}
?>
