#!/usr/bin/php
<?php
/*
 * This is an array test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test');

test('array_implode_with_keys()', 'Function call should convert associative array to string with keys and values', function() {
    if(array_implode_with_keys(array('foo' => 'bar', 'test' => 'test'), "\n", ' => ') != "foo => bar\ntest => test") {
        throw new CoreException('Did not convert array to correct string');
    }
});

test('array_implode_with_keys()', 'Function call should convert associative array with sub arrays to string with keys and values', function() {
    if(array_implode_with_keys(array('foo' => 'bar', 'test' => array('foo' => 'bar', 'test' => 'test')), "|", ' => ') != "foo => bar|test => |foo => bar|test => test") {
        throw new CoreException('Did not convert array with sub arrays to correct string');
    }
});
?>
