#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test,facebook,google,microsoft');

//test('facebook_get_avatar()', 'Function should obtain facebook avatar for specified facebook id (Sven Oostenbrink) and convert it into the configured number of sub avatars', function() {
//    global $_CONFIG;
//
//    $avatar = facebook_get_avatar(array('fb_id' => 1368195482));
//
//    foreach ($_CONFIG['avatars']['types'] as $type => $data) {
//        if (!file_exists($file = PATH_ROOT.'www/avatars/'.$avatar.'_'.$type.'.jpg')) {
//            throw new CoreException('Did not create avatar type "'.Strings::Log($type).'"');
//
//        } else {
//            /*
//             * Remove the temporary avatar file
//             */
//            file_delete($file);
//        }
//    }
//});
?>
