#!/usr/bin/php
<?php
/*
 * This is a standard test script
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test');

/*
 * Test cli_list_processes()
 */
test('cli_list_processes()', 'This test will use cli_list_processes() to find this process itself', function() {
    /*
     * Results should include this process itself
     */
    $results = cli_list_processes('php');

    foreach($results as $result) {
        if(str_contains($result, 'scripts/tests/cli')) {
            return $result;
        }
    }

    throw new CoreException(tr('The current process could not be found with cli_list_processes()'), 'not-exist');
});
?>
