#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test');

/*
 * Test
 */
test('NAME()', 'DESCRIPTION', function() {
    /*
     * TEST CODE HERE
     */
});
?>
