#!/usr/bin/php
<?php
/*
 * This is an file test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test');

test('file_clear_path()', 'Function call should clear test path', function() {
    $file = TESTPATH.'file_clear_path/'.file_assign_target(TESTPATH.'file_clear_path/');

    touch($file);
    file_clear_path($file, TESTPATH);

    if (file_exists(dirname($file)) or file_exists(dirname(dirname($file)))) {
        throw new CoreException(tr('Function file_clear_path() did not clear test path ":path"', array(':path' => $file)), 'failed');
    }
});
?>
