#!/usr/bin/php
<?php
/*
 * Import data from aquinegocio
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test,googlemaps,inet');

//test('googlemaps_get_streetview_image()', 'Function call should ......?', function() {
//    $img = googlemaps_get_streetview_image(40.452205,-3.692807);
////        log_console('Image recieved "'.number_format(strlen($img)).'" Bytes');
//
//});
//
//test('googlemaps_get_streetview_image()', 'Function call should ......?', function() {
//    $img = googlemaps_get_streetview_image(40.452205,-23.892807);
//    log_console('Testing googlemaps_get_streetview_image (invalid location)', 'test');
//
//    if (!$img) {
////            log_console("Image recieved was too small, that is ok");
//
//    } else {
////            log_console('Image recieved "'.Strings::Log(number_format(strlen($img))).'" Bytes, this should not happen', 'yellow');
//    }
//});
?>
