#!/usr/bin/php
<?php
/*
 * This is a mail test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only(true);
load_libs('test,mail');

//test('mail()', 'Function call should send test mail to devs@sven.com.mx because not in production, and sent to external email', function() {
//    mail_send_templated_email(array('to_name'  => 'Blergh von Blah',
//                                    'to_email' => 'test@testblah.blah'), 'Test subject', 'Test Body');
//
//    mail_send_templated_email(array('to_name'  => 'Sven Oostenbrink',
//                                    'to_email' => 'so.oostenbrink@gmail.com'), 'Test subject', 'Test Body');
//});
?>
