#!/usr/bin/php
<?php

declare(strict_types=1);


declare(strict_types=1);

use Phoundation\Cli\Cli;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Plugins\Plugins;
use Phoundation\Data\Validator\ArgvValidator;



/**
 * plugins/list script
 *
 * This script allows you to view your registered plugins
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Core
 */
Documentation::usage('./pho system plugins list [OPTIONS]
./cli system plugins init --all');

Documentation::help('This script allows you to view your registered plugins



ARGUMENTS



[-A / --all]                            List all plugins, not only the active ones');



// Get command line arguments
$argv = ArgvValidator::new()
    ->noArgumentsLeft()
    ->validate();



// Display the plugins
if ($argv['all']) {
    Cli::displayTable(Plugins::getAvailable());
} else {
    Cli::displayTable(Plugins::getEnabled());
}
