#!/usr/bin/php
<?php

declare(strict_types=1);


declare(strict_types=1);

use Phoundation\Cli\Cli;
use Phoundation\Cli\Documentation;
use Phoundation\Core\Plugins\Plugins;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * plugins/scan script
 *
 * This script allows you to scan the plugins directory PATH_ROOT/Plugins/ for new plugins and update the core_plugins
 * database table accordingly
 *
 * @author Sven Oostenbrink <support@capmega.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Core
 */
Documentation::usage('./pho system plugins scan');

Documentation::help('This script allows you to scan the plugins directory PATH_ROOT/Plugins/ for new plugins and 
update the core_plugins database table accordingly



ARGUMENTS



[-A / --all]                            List all plugins, not only the active ones');



// Get command line arguments
$argv = ArgvValidator::new()
    ->noArgumentsLeft()
    ->validate();



// Display the results of the plugins scan
Cli::displayTable(Plugins::scan());
