<?php

declare(strict_types=1);

namespace Phoundation\Web\Routing\Interfaces;

use Phoundation\Accounts\Rights\Interfaces\RightInterface;
use Phoundation\Filesystem\Interfaces\PhoRestrictionsInterface;
use Phoundation\Web\Html\Template\Interfaces\TemplateInterface;

interface RoutingParametersInterface
{
    /**
     * Returns the template as an object
     *
     * @return TemplateInterface
     */
    public function getTemplateObject(): TemplateInterface;


    /**
     * Returns the template to use
     *
     * @return string
     */
    public function getTemplate(): string;


    /**
     * Sets the template to use
     *
     * @param string $template
     *
     * @return static
     */
    public function setTemplate(string $template): static;


    /**
     * Returns the URI being processed
     *
     * @return string|null
     */
    public function getUri(): ?string;


    /**
     * Sets the URI being processed
     *
     * @param string $uri
     *
     * @return static
     */
    public function setUri(string $uri): static;


    /**
     * Returns the matches for the URI being processed
     *
     * @return array|null
     */
    public function getMatches(): ?array;


    /**
     * Returns the matches for the URI being processed
     *
     * @param array $matches
     *
     * @return static
     */
    public function setMatches(array $matches): static;


    /**
     * Returns the directory to use for the router so that it knows where to find the scripts to route to
     *
     * @return string
     */
    public function getRootDirectory(): string;


    /**
     * Sets the directory to use for the router so that it knows where to find the scripts to route to
     *
     * @param string $root_directory
     *
     * @return static
     */
    public function setRootDirectory(string $root_directory): static;


    /**
     * Returns the server restrictions
     *
     * @return PhoRestrictionsInterface
     */
    public function getRestrictionsObject(): PhoRestrictionsInterface;


    /**
     * Sets the server restrictions
     *
     * @param PhoRestrictionsInterface|array|string|null $o_restrictions
     *
     * @return static
     */
    public function setRestrictionsObject(PhoRestrictionsInterface|array|string|null $o_restrictions): static;


    /**
     * Returns the default base url for links generated by these pages
     *
     * @return string
     */
    public function getRootUrl(): string;


    /**
     * Sets the default base url for links generated by these pages
     *
     * @param string $root_url
     *
     * @return static
     */
    public function setRootUrl(string $root_url): static;


    /**
     * Returns the regex that selects on what scripts these parameters will be applied
     *
     * @return string
     */
    public function getPattern(): string;


    /**
     * Sets the regex that selects on what scripts these parameters will be applied
     *
     * @param string $pattern
     *
     * @return static
     */
    public function setPattern(string $pattern): static;


    /**
     * Returns if these parameters can only be used for system pages
     *
     * @return bool
     */
    public function getSystemPagesOnly(): bool;


    /**
     * Sets if these parameters can only be used for system pages
     *
     * @param bool $system_pages_only
     *
     * @return static
     */
    public function setSystemPagesOnly(bool $system_pages_only): static;
}
