#!/usr/bin/php
<?php
/*
 * This is a standard test script
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');
cli_only();
load_libs('test');

/*
 * Simple echo to screen test
 */
test('Echo', 'Simple test that echos "1" to the screen', function() {
    echo '1';
});
?>
