#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Cli;
use Phoundation\Cli\Documentation;
use Phoundation\Cli\Script;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script tools/display-ascii
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho tools display-ascii');
Documentation::help('The display-ascii tool script will display the specified text in pure HEX ASCII code');

$argv = ArgvValidator::new()
    ->select('text')->hasMaxCharacters(1048576)
    ->validate();

Script::echo(bin2hex($argv['text']));