#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Cli\Script;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script tools/urlencode
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho tools urlencode TEXT');
Documentation::help('This tool will echo the specified TEXT using URL encoding');

$argv = ArgvValidator::new()
    ->select('text')->hasMaxCharacters(1048576)
    ->validate();

Script::echo(urlencode($argv['text']));