security:
  seed: d5OK9sDYiWzq3gbD
debug: false
project:
  name: phoundation
  version: 0.0.0
languages:
  supported:
  - en
  default: en
databases:
  sql:
    debug: false
    instances:
      system:
        type: mysql
        server: localhost
        name: phoundation
        user: base
        pass: base
  memcached:
    instances:
      system: ~
notifications:
  groups:
    developers:
    - so.oostenbrink@gmail.com
web:
  minify: false
  sessions:
    cookies:
      secure: false
      domain: auto
  domains:
    primary:
      www: http://localhost/:LANGUAGE/
      cdn: http://cdn.localhost/:LANGUAGE/
    whitelabel1.phoundation.org:
      www: https://whitelabel1.phoundation.org/:LANGUAGE/
      cdn: https://cdn.whitelabel1.phoundation.org/:LANGUAGE/
  route:
    known-hacks: []
