security:
  seed: 8ZNl2d0e0gKnmGGNKp
debug:
  enabled: true
  production: false
project:
  name: phoundation
  version: 0.0.0
languages:
  supported:
  - en
  default: en
databases:
  sql:
    debug: false
    instances:
      system:
        type: mysql
        server: localhost
        name: phoundation
        user: base
        pass: base
  memcached:
    instances:
      system: ~
notifications:
  groups:
    developers:
    - so.oostenbrink@gmail.com
web:
  minify: false
  sessions:
    cookies:
      secure: false
      domain: auto
  domains:
    primary:
      web: http://phoundation.org.local/:LANGUAGE/
      cdn: http://cdn.phoundation.org.local/:LANGUAGE/
  route:
    known-hacks: []
