security:
  seed: "t456lerwtvgjh2ql453kywlkcejghle5k6jy14v(4%#^yrtynRY1"
debug:
  enabled: true
project:
  name: "Phoundation"
  version: "0.0.0"
languages:
  supported: "en", "es"
  default: "en"
web:
  sessions:
    cookies:
  domains:
    primary:
      www:
        domain: www.phoundation.localhost
        protocol: https://
        path-prefix: /:LANGUAGE/
        index: /
      cdn: cdn.phoundation.localhost
    test:
      www:
        domain: www.test.localhost
        protocol: https://
        path-prefix: /:LANGUAGE/
      cdn: cdn.test.localhost
    trial:
      www:
        domain: www.trial.localhost
        protocol: https://
        path-prefix: /:LANGUAGE/
      cdn: cdn.trial.localhost
  route:
    known-hacks:
  template:
    class: "Phoundation"
notifications:
  groups:
    developers:
      "so.oostenbrink@gmail.com"
databases:
  sql:
    debug: false
    instances:
      system:
        type: "mysql"
        server: "localhost"
        name: "phoundation"
        user: "base"
        pass: "base"
  mongo:
    instances:
