security:
  seed: "t456lerwtvgjh2ql453kywlkcejghle5k6jy14v(4%#^yrtynRY1"
debug:
  enabled: true
project:
  name: "Phoundation"
  version: "0.0.0"
languages:
  supported: ["en", "es"]
  default: "en"
web:
  sessions:
    cookies:
  domains:
    primary:
      www: "http://phoundation.org/:LANGUAGE/"
      cdn: "http://cdn.phoundation.org/:LANGUAGE/"
    test.phoundation.org.local:
      www: "https://test.phoundation.org.local/:LANGUAGE/"
      cdn: "https://cdn.test.phoundation.org.local/:LANGUAGE/"
    trial.phoundation.local:
      www: "https://trial.phoundation.org.local/:LANGUAGE/"
      cdn: "https://cdn.trial.phoundation.org.local/:LANGUAGE/"
  route:
    known-hacks:
  template:
    name: "phoundation"
notifications:
  groups:
    developers:
      "so.oostenbrink@gmail.com"
databases:
  sql:
    debug: false
    instances:
      system:
        type: "mysql"
        server: "localhost"
        name: "phoundation"
        user: "base"
        pass: "base"
  memcached:
    instances:
      system:
