security:
  seed: "t456lerwtvgjh2ql453kywlkcejghle5k6jy14v(4%#^yrtynRY1"
debug:
  enabled: true
project:
  name: "Phoundation"
  version: "0.0.0"
languages:
  supported: null
web:
  sessions:
    cookies:
  domains:
    primary: localhost
  route:
    known-hacks:
notifications:
  groups:
    developers:
      "so.oostenbrink@gmail.com"
databases:
  sql:
    debug: false
    instances:
      system:
        type: "mysql"
        server: "localhost"
        name: "phoundation"
        user: "base"
        pass: "base"
  mongo:
    instances:
