#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Accounts\Roles\Role;
use Phoundation\Cli\Cli;
use Phoundation\Cli\CliColor;
use Phoundation\Cli\CliDocumentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\DataEntry\Exception\DataEntryNotExistsException;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Utils\Arrays;


/**
 * Script accounts/roles/info
 *
 * This script displays information about the specified role.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
CliDocumentation::usage('./pho accounts roles info USER');

CliDocumentation::help('This script displays information about the specified role.  



ARGUMENTS



USER                                    The role to display information about. Specify either by role id or seo-name');



// Validate arguments
$argv = ArgvValidator::new()
    ->select('role')->hasMinCharacters(2)->hasMaxCharacters(255)
    ->validate();



try {
    $role = Role::get($argv['role']);

    // Display role data and rights
    Cli::displayForm($role->getSource());

    Log::cli();
    Log::cli(CliColor::apply('Rights available for this role:', 'white'));

    Cli::displayTable(Arrays::listKeep($role->getRights(), 'id,name'), id_column: null);

}catch (DataEntryNotExistsException $e) {
    throw $e->makeWarning();
}
