#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Phoundation\Phoundation;


/**
 * THIS SCRIPT IS ONLY FOR PHOUNDATION DEVELOPERS
 *
 * This script will copy changed files back to your phoundation installation. The script will assume your phoundation
 * installation is in ~/projects/phoundation
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @category Function reference
 * @package Phoundation\Development
 */

Documentation::usage('./pho system project update [OPTIONS]
./cli system development phoundation patch -b BRANCH
./cli system development phoundation patch -b  BRANCH --no-checkout -s
./cli system development phoundation patch -l --branch BRANCH -p /home/USER/projects/phoundation  
');

Documentation::help('This script will update your Phoundation libraries and list



ARGUMENTS



-b / --branch                           The branch from which to update

[-c / --no-checkout]                    If specified will not automatically checkout (and thus remove) the local changes  

[-m / --message]                        The git commit message for this update. If not specified, a default will be used  

[-s / --signed]                         If specified will make a signed commit. This requires your git setup to be 
                                        configured correctly for this
                                        
[-p / --phoundation]                    If specified should contain the path to your local Phoundation installation');



// Get command line arguments
$argv = ArgvValidator::new()
    ->select('-b,--branch', true)->isOptional()->isPrintable()
    ->select('-c,--no-checkout')->isOptional()->isBoolean()
    ->select('-m,--message', true)->isOptional()->isPrintable()->hasMinCharacters(10)->hasMaxCharacters(1024)
    ->select('-p,--phoundation', true)->isOptional()->isPrintable()
    ->select('-s,--signed')->isOptional()->isBoolean()
    ->noArgumentsLeft()
    ->validate();


Log::information(tr('Copying local changes in ":project" project back to your Phoundation installation', [
        ':project' => PROJECT
]));

Phoundation::new($argv['phoundation'])->patch($argv['branch'], $argv['message'], $argv['signed'], !$argv['no_checkout']);