<?php

declare(strict_types=1);

namespace Phoundation\Data\DataEntry;

use PDOStatement;
use Phoundation\Cli\Cli;
use Phoundation\Data\DataEntry\Interfaces\DataEntryInterface;
use Phoundation\Data\DataEntry\Interfaces\DataListInterface;
use Phoundation\Data\Interfaces\IteratorInterface;
use Phoundation\Data\Iterator;
use Phoundation\Data\Traits\DataParent;
use Phoundation\Databases\Sql\Interfaces\QueryBuilderInterface;
use Phoundation\Databases\Sql\QueryBuilder;
use Phoundation\Databases\Sql\Sql;
use Phoundation\Exception\OutOfBoundsException;
use Phoundation\Utils\Json;
use Phoundation\Web\Http\Html\Components\DataTable;
use Phoundation\Web\Http\Html\Components\Input\Interfaces\SelectInterface;
use Phoundation\Web\Http\Html\Components\Table;
use ReturnTypeWillChange;
use Stringable;


/**
 * Class DataList
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2023 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Company\Data
 */
abstract class DataList extends Iterator implements DataListInterface
{
    use DataParent;


    /**
     * The iterator position
     *
     * @var int $position
     */
    protected int $position = 0;

    /**
     * The class for the items in this list when the item is dynamically created
     *
     * @var string $entry_class
     */
    protected string $entry_class;

    /**
     * The query to display an HTML table for this list
     *
     * @var string $query
     */
    protected string $query;

    /**
     * The execution array for the HTML query
     *
     * @var array|null $execute
     */
    protected ?array $execute;

    /**
     * The name of the source table for this DataList
     *
     * @var string
     */
    protected string $table;

    /**
     * The unique column identifier, next to id
     *
     * @var string|null $unique_column
     */
    protected ?string $unique_column = null;

    /**
     * If set, use the query generated by this builder instead of the default query
     *
     * @var QueryBuilderInterface
     */
    protected QueryBuilderInterface $query_builder;


    /**
     * Return the object source contents in JSON string format
     *
     * @return string
     */
    public function __toString(): string
    {
        return Json::encode($this->source);
    }


    /**
     * Return the object contents in JSON string format
     *
     * @return array
     */
    public function __toArray(): array
    {
        return $this->source;
    }


    /**
     * Iterator class constructor
     *
     * @param IteratorInterface|PDOStatement|array|string|null $source
     * @param array|null $execute
     */
    public function __construct(IteratorInterface|PDOStatement|array|string|null $source = null, array|null $execute = null)
    {
        parent::__construct();
    }


    /**
     * Returns a new Iterator object
     *
     * @param IteratorInterface|PDOStatement|array|string|null $source
     * @param array|null $execute
     * @return static
     */
    public static function new(IteratorInterface|PDOStatement|array|string|null $source = null, array|null $execute = null): static
    {
        return new static($source, $execute);
    }


    /**
     * Returns if the specified data entry exists in the data list
     *
     * @param DataEntryInterface|Stringable|string|float|int $key
     * @return bool
     */
    public function exists(DataEntryInterface|Stringable|string|float|int $key): bool
    {
        if ($key instanceof DataEntryInterface) {
            return array_key_exists($key->getId(), $this->source);
        }

        return parent::exists($key);
    }


    /**
     * Returns a list of items that are specified, but not available in this DataList
     *
     * @param DataListInterface|array|string $list
     * @param string|null $always_match
     * @return array
     */
    public function getMissingKeys(DataListInterface|array|string $list, string $always_match = null): array
    {
        if (is_string($list)) {
            $list = explode(',', $list);
        }

        $return = [];

        foreach ($list as $entry) {
            if (array_key_exists($entry, $this->source)) {
                continue;
            }

            // Can still match if $always_match is available!
            if ($always_match and array_key_exists($always_match, $this->source)) {
                // Okay, this list contains ALL the requested entries due to $always_match
                return [];
            }

            $return[] = $entry;
        }

        return $return;
    }


    /**
     * Returns if all (or optionally any) of the specified entries are in this list
     *
     * @param DataListInterface|array|string $list
     * @param bool $all
     * @param string|null $always_match
     * @return bool
     */
    public function containsKeys(DataListInterface|array|string $list, bool $all = true, string $always_match = null): bool
    {
        if (is_string($list)) {
            $list = explode(',', $list);
        }

        foreach ($list as $entry) {
            if (!array_key_exists($entry, $this->source)) {
                if ($all) {
                    // All need to be in the array, but we found one missing.
                    // Can still match if $always_match is available!
                    if ($always_match and array_key_exists($always_match, $this->source)) {
                        // Okay, this list contains ALL the requested entries due to $always_match
                        return true;
                    }

                    return false;
                }
            } else {
                if (!$all) {
                    // only one needs to be in the array, we found one, we're good!
                    return true;
                }
            }
        }

        // All were in the array
        return true;
    }


    /**
     * Returns if all (or optionally any) of the specified entries are in this list
     *
     * @param DataListInterface|array|string $list
     * @param bool $all
     * @param string|null $always_match
     * @return bool
     */
    public function containsValues(DataListInterface|array|string $list, bool $all = true, string $always_match = null): bool
    {
        if (is_string($list)) {
            $list = explode(',', $list);
        }

        foreach ($list as $entry) {
            if (!in_array($entry, $this->source)) {
                if ($all) {
                    // All need to be in the array, but we found one missing.
                    // Can still match if $always_match is available!
                    if ($always_match and in_array($always_match, $this->source)) {
                        // Okay, this list contains ALL the requested entries due to $always_match
                        return true;
                    }

                    return false;
                }
            } else {
                if (!$all) {
                    // only one needs to be in the array, we found one, we're good!
                    return true;
                }
            }
        }

        // All were in the array
        return true;
    }


    /**
     * Returns the entire internal list
     *
     * @return array
     */
    public function list(): array
    {
        return array_flip($this->source);
    }


    /**
     * Returns the internal list filtered by the specified keyword
     *
     * @param string|null $keyword
     * @return array
     */
    public function filteredList(?string $keyword): array
    {
        $return = [];
        $keyword = strtolower((string) $keyword);

        foreach ($this->list() as $value) {
            if (!$keyword or str_contains(strtolower(trim($value)), $keyword)) {
                $return[] = $value;
            }
        }

        return $return;
    }


    /**
     * Set the query for this object when generating internal content
     *
     * @param string $query
     * @param array|null $execute
     * @return static
     */
    public function setQuery(string $query, ?array $execute = null): static
    {
        $this->query   = $query;
        $this->execute = $execute;

        return $this;
    }


    /**
     * Returns the query for this object when generating internal content
     *
     * @return string
     */
    public function getQuery(): string
    {
        return $this->query;
    }


    /**
     * Returns the table name that is the source for this DataList object
     *
     * @return string
     */
    public function getTable(): string
    {
        return $this->table;
    }


    /**
     * Returns the schema Table object for the table that is the source for this DataList object
     *
     * @return \Phoundation\Databases\Sql\Schema\Table
     */
    public function getTableSchema(): \Phoundation\Databases\Sql\Schema\Table
    {
        return sql()->schema()->table($this->table);
    }


    /**
     * Returns the item with the specified identifier
     *
     * @param Stringable|string|float|int $key
     * @param bool $exception
     * @return DataEntry|null
     */
    #[ReturnTypeWillChange] function get(Stringable|string|float|int $key, bool $exception = false): ?DataEntryInterface
    {
        // Does this entry exist?
        if (!array_key_exists($key, $this->source)) {
            throw new OutOfBoundsException(tr('Key ":key" does not exist in this DataList', [
                ':key' => $key
            ]));
        }

        // Is this entry available as a DataEntry already?
        if (!is_object($this->source[$key])) {
            $this->source[$key] = $this->entry_class::new()->load($this->source[$key]);
        }

        return $this->source[$key];
    }


    /**
     * Creates and returns an HTML table for the data in this list
     *
     * @return Table
     */
    public function getHtmlTable(): Table
    {
        $this->selectQuery();

        // Create and return the table
        return Table::new()
            ->setSourceQuery($this->query, $this->execute)
            ->setCheckboxSelectors(true);
    }


    /**
     * Returns a QueryBuilder object to modify the internal query for this object
     *
     * @return QueryBuilderInterface
     */
    public function getQueryBuilder(): QueryBuilderInterface
    {
        if (!isset($this->query_builder)) {
            $this->query_builder = new QueryBuilder($this);
        }

        return $this->query_builder;
    }


    /**
     * Creates and returns a fancy HTML data table for the data in this list
     *
     * @return DataTable
     */
    public function getHtmlDataTable(): DataTable
    {
        $this->selectQuery();

        // Create and return the table
        return DataTable::new()
            ->setId($this->table)
            ->setSourceQuery($this->query, $this->execute)
            ->setCheckboxSelectors(true);
    }


    /**
     * Returns an HTML <select> for the available object entries
     *
     * @return SelectInterface
     */
    abstract public function getHtmlSelect(): SelectInterface;


    /**
     * Creates and returns a CLI table for the data in this list
     *
     * @param array|null $columns
     * @param array $filters
     * @param string|null $id_column
     * @return void
     */
    public function CliDisplayTable(?array $columns = null, array $filters = [], ?string $id_column = 'id'): void
    {
        $list = $this->loadDetails($columns, $filters);
        Cli::displayTable($list, $columns, $id_column);
    }


    /**
     * Set the specified status for the specified entries
     *
     * @param string|null $status
     * @param array $entries
     * @param string|null $comments
     * @return int
     */
    public function setStatus(?string $status, array $entries, ?string $comments = null): int
    {
        return sql()->setStatus($status, $this->table, $entries, $comments);
    }


    /**
     * Delete the specified entries
     *
     * @param array $entries
     * @param string|null $comments
     * @return int
     */
    public function dbDelete(array $entries, ?string $comments = null): int
    {
showdie('$entries IS IN CORRECT HERE, AS SQL EXPECTS IT, IT SHOULD BE AN ARRAY FOR A SINGLE ROW!');
        return $this->setStatus('deleted', $entries, $comments);
    }


    /**
     * Undelete the specified entries
     *
     * @param array $entries
     * @param string|null $comments
     * @return int
     */
    public function dbUndelete(array $entries, ?string $comments = null): int
    {
showdie('$entries IS IN CORRECT HERE, AS SQL EXPECTS IT, IT SHOULD BE AN ARRAY FOR A SINGLE ROW!');
        return $this->setStatus(null, $entries, $comments);
    }


    /**
     * Returns an array with all id's for the specified entry identifiers
     *
     * @param array $identifiers
     * @return array
     */
    public function listIds(array $identifiers): array
    {
        $in = Sql::in($identifiers);

        return sql()->list('SELECT `id` 
                                  FROM   `' . $this->table . '` 
                                  WHERE  `' . $this->unique_column . '` IN (' . implode(', ', array_keys($in)) . ')', $in);
    }


//    /**
//     * Erase the specified entries
//     *
//     * @param array $entries
//     * @return int
//     */
//    public function erase(array $entries): int
//    {
//        return sql()->erase($this->table_name, $entries);
//    }


    /**
     * Add the specified data entry to the data list
     *
     * @param DataEntry|null $entry
     * @return static
     */
    protected function addEntry(?DataEntryInterface $entry): static
    {
        if ($entry) {
            $this->source[$entry->getId()] = $entry;
        }

        return $this;
    }


    /**
     * Remove the specified data entry from the data list
     *
     * @param DataEntry|int|null $entry
     * @return static
     */
    protected function removeEntry(DataEntryInterface|int|null $entry): static
    {
        if ($entry) {
            if (is_object($entry)) {
                $entry = $entry->getId();
            }

            unset($this->source[$entry]);
        }

        return $this;
    }


    /**
     * Remove all the entries from the DataList
     *
     * @return static
     */
    protected function clearEntries(): static
    {
        $this->source = [];
        return $this;
    }


    /**
     * If the list has not yet loaded its content, do so now
     *
     * @return void
     */
    protected function ensureLoaded(): void
    {
        if (!isset($this->source)) {
            $this->load();
        }
    }


    /**
     * Will throw an OutOfBoundsException exception if no parent was set for this list
     *
     * @param string $action
     * @return void
     */
    protected function ensureParent(string $action): void
    {
        if (!$this->parent) {
            throw new OutOfBoundsException(tr('Cannot ":action", no parent specified', [':action' => $action]));
        }
    }


    /**
     * Selects if we use the default query or a query from the QueryBuilder
     *
     * @return void
     */
    protected function selectQuery(): void
    {
        // Use the default html_query and html_execute or QueryBuilder html_query and html_execute?
        if (isset($this->query_builder)) {
            $this->query   = $this->query_builder->getQuery();
            $this->execute = $this->query_builder->getExecute();

        } elseif (!isset($this->query)) {
            throw new OutOfBoundsException(tr('Cannot generate HMTL table for ":class", no html query specified', [
                ':class' => get_class($this)
            ]));
        }
    }


    /**
     * Returns the current item
     *
     * @return DataEntry|null
     */
    #[ReturnTypeWillChange] public function current(): ?DataEntryInterface
    {
        return $this->get(key($this->source));
    }


    /**
     * Load the id list from database
     *
     * @deprecated This function will be replaced by the QueryBuilder. DO NOT USE
     * @param string|null $id_column
     * @return static
     */
    abstract public function load(?string $id_column = null): static;


    /**
     * Load the data list elements from database
     *
     * @deprecated This function will be replaced by the QueryBuilder. DO NOT USE
     * @param array|string|null $columns
     * @param array $filters
     * @param array $order_by
     * @return array
     */
    abstract public function loadDetails(array|string|null $columns, array $filters = [], array $order_by = []): array;


    /**
     * Save the data list elements to database
     *
     * @return static
     */
    abstract public function save(): static;
}