#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Project\Project;



/**
 * Script project/check
 *
 * This script will check for - and report - (and optionally fix) the project and its systems
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho system deploy
./pho system deploy TARGET --
');

Documentation::help('This script will deploy your project from this machine to the target environment

Most options are configured in a per-target basis and can be specified on the command line to override this
configuration in a do or do not way. For example, the "production" environment can have "execute-hooks" enabled with
true, but this can be overridden on the command line by using --no-execute-hooks. Please note that modifiers specified
on the command line apply on all specified targets. If you wish to use different modifiers for different targets, then
execute an individual deploy process for each target

The general deployment configuration is stored in config/deploy/deploy.yml. Every target environment must have its own
deployment configuration file named config/deploy/ENVIRONMENT.yml where ENVIRONMENT is the name of the target
environment. If the required target environment has no configuration file, you will not be able to deploy to it.



ARGUMENTS



TARGET                                  - The target name to which to deploy

-c / --categories                       - List all available deployment categories

-t / --targets                          - List all available deployment targets


--do-ignore-changes                     - Do not ignore git status, check for uncommitted changes
--no-ignore-changes                     - Ignore git status, don\'t check for uncommitted changes

--do-content-check                      - Do check content files

--no-content-check                      - Do not check content files

--do-execute-hooks                      - Do execute hooks

--no-execute-hooks                      - Do not execute hooks

--do-init                               - Do execute an init on the target server

--no-init                               - Do not execute an init on the target server

--no-notify                             - Do not send notifications

--no-compress                           - Do not compress the javascript / CSS files.

--no-push                               - Do not automatically git push all changes and tags

--no-parrallel                          - Do not use parallel rsync deploy, even if the website is configured to do so 
                                          anyway

--no-sitemap                            - Do not automatically reupdate the sitemap files

--no-translate                          - Do not execute file translation

--no-bom-check                          - Do not test for BOM character in all PHP files. The ByteOrderMark character is  
                                          a UTF8 character (added mostly by apple machines) that indicates how to read 
                                          the UTF8 text, but is interpreted by the PHP as a character before the <?php 
                                          tag, which can cause problems with headers(). The clearbom script will strip 
                                          the BOM characters and is by default always executed on each deploy to be sure 
                                          no BOM characters end up in production code. This option disables the BOM 
                                          check.

--no-backup                             - Do NOT execute a site / database backup, even though per configuration, a  
                                          backup should be done

--do-backup                             - Execute a site / database backup, even if per configuration, a backup should 
                                          not be done

--stash                                 - Execute a \"git stash\" before and \"git stash pop\" after deploy, in case the WT
                                          contained changes

--update-sitemap                        - rsync the www/LANG/sitemap file as well (Normally always skipped)

-F / --force                            - Force a deploy, even when it should be stopped due to (for example) git changes

--test-syntax                           - Do PHP syntax tests

--test-unit                             - Do PHP unit tests ');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('targets', true)->isOptional()->isVariable()
    ->select('-c,--categories', true)->isOptional()->isVariable()
    ->select('--do-ignore-changes')->isOptional()->isBoolean()
    ->select('--no-ignore-changes')->isOptional()->isBoolean()
    ->select('--do-content-check')->isOptional()->isBoolean()
    ->select('--no-content-check')->isOptional()->isBoolean()
    ->select('--do-hooks')->isOptional()->isBoolean()
    ->select('--no-hooks')->isOptional()->isBoolean()
    ->select('--do-init')->isOptional()->isBoolean()
    ->select('--no-init')->isOptional()->isBoolean()
    ->select('--do-notify')->isOptional()->isBoolean()
    ->select('--no-notify')->isOptional()->isBoolean()
    ->select('--do-compress')->isOptional()->isBoolean()
    ->select('--no-compress')->isOptional()->isBoolean()
    ->select('--do-push')->isOptional()->isBoolean()
    ->select('--no-push')->isOptional()->isBoolean()
    ->select('--do-parallel')->isOptional()->isBoolean()
    ->select('--no-parallel')->isOptional()->isBoolean()
    ->select('--do-sitemap')->isOptional()->isBoolean()
    ->select('--no-sitemap')->isOptional()->isBoolean()
    ->select('--do-translate')->isOptional()->isBoolean()
    ->select('--no-translate')->isOptional()->isBoolean()
    ->select('--do-bom-check')->isOptional()->isBoolean()
    ->select('--no-bom-check')->isOptional()->isBoolean()
    ->select('--do-backup')->isOptional()->isBoolean()
    ->select('--no-backup')->isOptional()->isBoolean()
    ->select('--do-stash')->isOptional()->isBoolean()
    ->select('--no-stash')->isOptional()->isBoolean()
    ->select('--do-update-sitemap')->isOptional()->isBoolean()
    ->select('--no-update-sitemap')->isOptional()->isBoolean()
    ->select('--do-test-syntax')->isOptional()->isBoolean()
    ->select('--no-test-syntax')->isOptional()->isBoolean()
    ->select('--do-test-unit')->isOptional()->isBoolean()
    ->select('--no-test-unit')->isOptional()->isBoolean()
    ->noArgumentsLeft()
    ->validate();


Log::information('Starting deployment process');

Project::new()->getDeploy($argv['targets'])
    ->setExecuteHooks($argv['execute_hooks'], $argv['execute_hooks'])
    ->execute();
