#!/usr/bin/php
<?php
use Phoundation\Cli\Color;
use Phoundation\Cli\Scripts;
use Phoundation\Core\Config;
use Phoundation\Core\Core;
use Phoundation\Core\Log;
use Phoundation\Core\Strings;
use Phoundation\Databases\Sql\Sql;
use Phoundation\Developer\Debug;
use Phoundation\Exception\ScriptException;
use Phoundation\Libraries\Libraries;



/**
 * Script system/info
 *
 * This script will display detailed information about the current framework, project, database ,etc.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\System
 */
$usage = './cli system info';

$help  = 'The info script will show detailed information about the current framework, project, database and more';

Scripts::noArgumentsLeft();

try {
    Sql()->query('SELECT 1');

}catch(Exception $e) {
    if ($e->getCode() != '1049') {
        throw $e;
    }

    $no_db = true;
    define('FRAMEWORKDBVERSION', tr('database ":db" does not exist', [':db' => Config::get('databases.system.name')]));
    define('PROJECTDBVERSION'  , tr('database ":db" does not exist', [':db' => Config::get('databases.system.name')]));
}

//$framework_status = version_compare(Core::FRAMEWORKCODEVERSION, Core::getVersion('framework'));
//$project_status   = version_compare(Config::get('project.version')  , Core::getVersion('project'));

Log::cli(Color::apply(Strings::size(tr('Project name:') , 28), 'white') . ' ' . PROJECT);
Log::cli(Color::apply(Strings::size(tr('Platform:')     , 28), 'white') . ' ' . PLATFORM);
Log::cli(Color::apply(Strings::size(tr('Environment:')  , 28), 'white') . ' ' . ENVIRONMENT);
Log::cli(Color::apply(Strings::size(tr('Production:')   , 28), 'white') . ' ' . Strings::boolean(Debug::production()));
Log::cli(Color::apply(Strings::size(tr('Debug:')        , 28), 'white') . ' ' . Strings::boolean(Debug::enabled()));
Log::cli(Color::apply(Strings::size(tr('Core database:'), 28), 'white') . ' ' . Config::get('databases.sql.instances.system.name', 'unknown'));
Log::cli();
Log::cli(Color::apply(Strings::size(tr('System libraries:'), 28), 'white') . ' ' . Strings::size(tr('Code version'), 14) . tr('Database version'));

foreach (Libraries::listLibraries(true, false) as $library) {
    Log::cli(Color::apply(Strings::size($library->getName(), 28), 'white') . ' ' . Strings::size($library->getCodeVersion() ?? '-', 14) . ($library->getDatabaseVersion() ?? '-'));
}

Log::cli();
Log::cli(Color::apply(Strings::size(tr('Plugin libraries:'), 28), 'white') . ' ' . Strings::size(tr('Code version'), 14) . tr('Database version'));

foreach (Libraries::listLibraries(false) as $library) {
    Log::cli(Color::apply(Strings::size($library->getName(), 28), 'white') . ' ' . Strings::size($library->getCodeVersion() ?? '-', 14) . ($library->getDatabaseVersion() ?? '-'));
}

Log::cli();
