#!/usr/bin/php
<?php
use Phoundation\Cli\Script;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Sync;



/**
 * Script system/sync
 *
 * This script will synchronize either the specified environment to your local environment or vice versa.
 *
 * With this, a production environment can easily be tested locally, for example
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system sync ENVIRONMENT
./cli system sync -l -i --to ENVIRONMENT';

$help  = 'This script will synchronize either the specified environment to your local environment or vice versa.
With this, a production environment can easily be tested locally, for example';

// Validate arguments
ArgvValidator::new()
    ->select('-l,--lock')->isOptional(false)->isBoolean()
    ->select('-i,--init')->isOptional(true)->isBoolean()
    ->select('-t,--to')->isOptional(true)->isBoolean()
    ->select('-e,--environment')->isOptional(null)->isName()
    ->validate();

$sync = Sync::new()
    ->setEnvironment($argv['environment'])
    ->setLock($argv['lock'])
    ->setInit($argv['init']);

if ($argv['to']) {
    $sync->toEnvironment();
} else {
    $sync->fromEnvironment();
}