#!/usr/bin/php
<?php
use Phoundation\Cli\Script;
use Phoundation\Developer\Sync;



/**
 * Script system/sync
 *
 * This script will synchronize either the specified environment to your local environment or vice versa.
 *
 * With this, a production environment can easily be tested locally, for example
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
$usage = './cli system sync ENVIRONMENT
./cli system sync -l -i --to ENVIRONMENT';

$help  = 'This script will synchronize either the specified environment to your local environment or vice versa.
With this, a production environment can easily be tested locally, for example';

$lock = Script::boolArgument('-l,--lock', true);
$init = Script::boolArgument('-i,--init', true);
$to   = Script::boolArgument('-t,--to'  , true);

$environment = Script::Argument('-e,--environment', true);

Script::noArgumentsLeft();

$sync = Sync::new()
    ->setEnvironment($environment)
    ->setLock($lock)
    ->setLock($lock);

if ($to) {
    $sync->toEnvironment();
} else {
    $sync->fromEnvironment();
}