#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Cli\Script;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Developer\Sync;



/**
 * Script system/sync
 *
 * This script will synchronize either the specified environment to your local environment or vice versa.
 *
 * With this, a production environment can easily be tested locally, for example
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho system sync ENVIRONMENT
./pho system sync -l -i --to ENVIRONMENT');

Documentation::help('This script will synchronize either the specified environment to your local environment or vice versa.
With this, a production environment can easily be tested locally, for example



ARGUMENTS



[-f / --from]                           If specified

[-i / --init]

[-l / --lock]                           If specified

[-t / --target]                         If specified

[-t / --to]                             If specified');



// Validate arguments
$argv = ArgvValidator::new()
    ->select('-l,--lock')->isOptional(false)->isBoolean()
    ->select('-i,--init')->isOptional(true)->isBoolean()
    ->select('-t,--to', true)->isOptional()->isVariable()
    ->select('-f,--from', true)->xor('to')->isVariable()
    ->select('-t,--target')->isOptional(null)->isName()
    ->noArgumentsLeft()
    ->validate();



// Sync environments
$sync = Sync::new()
    ->setLock($argv['lock'])
    ->setInit($argv['init']);

if ($argv['to']) {
    $sync->toEnvironment($argv['target']);
} else {
    $sync->fromEnvironment($argv['target']);
}