#!/usr/bin/php
<?php
/*
 *
 */

try {
    if (cli_exclusive()) {
        echo "This script is already running and it cannot run twice!\n";

    } else {
        while (true) {
            echo "WHHEEE!! I got the world to my own!!\n";
            sleep(1);
        }
    }

}catch(Exception $e) {
    throw new CoreException('scripts/test: Failed', $e);
}
?>
