#!/usr/bin/php
<?php
/*
 * This is a test interface that lets the admin do some diagnostics
 */
require_once(__DIR__.'/../../libs/startup.php');

cli_no_arguments_left();

if(cli_run_once('kill')) {
    echo "This script is already running and it cannot run twice!\n";

} else {
    while(true) {
        echo "WHHEEE!! I got the world to my own!!\n";
        sleep(1);
    }
}
?>
