#!/usr/bin/php
<?php
/*
 * This script is a front end to PHP composer
 */
$usage = './scripts/base/composer OPTIONS
./scripts/base/composer version
./scripts/base/composer init
./scripts/base/composer install PACKAGE
./scripts/base/composer install';

$help  = 'This is the phoundation composer front-end script';

require_once(__DIR__.'/../../libs/startup.php');
load_libs('composer');

switch (cli_method()) {
    case 'init':
        /*
         * Setup a composer JSON data file
         */
        composer_init_file();
        break;

    case 'version':
        composer_execute('-V');
        break;

    case 'install':
        $packages = cli_arguments();
        composer_install($packages);
        break;

    case 'require':
        $packages = cli_arguments();
        composer_require($packages);
        break;

    case 'explain':
        composer_exec(array('help'));
        break;

    case 'list':
        safe_exec(array('function' => 'passthru',
                        'commands' => array('cd' , array(ROOT),
                                            'php', array($composer, 'list'))));
        break;

    case 'search':
        $query = cli_arguments();

        if (!$query) {
            throw new CoreException(tr('No query specified'), 'not-specified');
        }

        $arguments = array($composer, 'search');
        $arguments = array_merge($arguments, $query);

        safe_exec(array('function' => 'passthru',
                        'commands' => array('cd' , array(ROOT),
                                            'php', $arguments)));
        break;

    case 'show':
        $query = cli_arguments();

        if (!$query) {
            throw new CoreException(tr('No query specified'), 'not-specified');
        }

        $arguments   = array($composer, 'show');
        $arguments   = array_merge($arguments, $query);
        $arguments[] = '--all';

        safe_exec(array('function' => 'passthru',
                        'commands' => array('cd' , array(ROOT),
                                            'php', $arguments)));
        break;

    case '':
        throw new CoreException(tr('No method specified, please specify one of "init"'), 'no-method');

    default:
        throw new CoreException(tr('Unknown method ":method" specified, please specify one of "init"', array(':method' => cli_method())), 'unknown');
}
?>
