#!/usr/bin/php
<?php
/*
 * This is the crawler script
 */
$usage = './scripts/base/crawler
./scripts/base/crawler cache URL [options]';

$help  = 'The crawler script can help with crawling websites



ARGUMENTS (apply to all methods)

    --use-proxies yes|no        - Skip the default setting and force usage of proxies, or not



METHODS



projects                        - Project management method

    add PROJECTNAME             - Add a new project

    list                        - List projects

cache                           - Force cache refreshes on the specified BASE
                                  type website

run                             - Run the crawler';

require_once(__DIR__.'/../../libs/startup.php');
cli_only();
load_libs('curl');

switch (cli_method()) {
    case 'projects':
        switch (cli_method(1)) {
            case 'add':
                $project['name'] = cli_argument(0);
                $project         = crawler_validate_project($project);
                break;

            case 'list':

                break;

            case '':
                throw new CoreException(tr('No sub method specified for method "projects"'), 'no-method');

            default:
                throw new CoreException(tr('Unknown sub method ":method" specified for method "projects"', array(':method' => cli_method())), 'unknown-method');
        }

        break;

    case 'run':
        break;

    case '':
        throw new CoreException(tr('No method specified'), 'no-method');

    default:
        throw new CoreException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}
?>
