#!/usr/bin/php
<?php
/*
 * This is the fonts management script
 */
$usage = './scripts/base/fonts
./scripts/base/fonts providers
./scripts/base/fonts install PROVIDER
./scripts/base/fonts update PROVIDER';

$help  = 'This script can help with managing the various font icons installations';

require_once(__DIR__.'/../../libs/startup.php');
cli_only();
load_libs('fonts');

switch(cli_method()) {
    case 'providers':
        foreach(fonts_providers() as $provider => $supported) {
            console_log();
        }

        break;

    case 'install':
        $provider = cli_method(1);

        break;

    case 'update':
        break;

    case '':
        throw new CoreException(tr('No method specified'), 'no-method');

    default:
        throw new CoreException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}
?>
