#!/usr/bin/php
<?php
/*
 * This script restarts itself. Its more of a test script
 */
$usage = './scripts/base/restart [--delay DELAY] [--seconds SECONDS]';

$help  = 'All this script does is restarting itself until eternity


ARGUMENTS

-d, --delay DELAY               - The amount of seconds that the background
                                  restart should wait until it restarts the
                                  script to ensure that this current script has
                                  had enough time to shut down. Defaults to 2


-s, --seconds SECONDS           - The amount of seconds to wait until the
                                  reset() call is made. Defaults to 1';

require_once(__DIR__.'/../../libs/startup.php');
cli_only(true);

/*
 * Ensure we have a fair amound of delay
 */
$seconds = cli_argument('-s,--seconds', true, 2);
$delay   = cli_argument('-d,--delay'  , true, 1);
cli_no_arguments_left();

if($seconds){
    if(!is_numeric($seconds) or ($seconds < 0)){
        throw new BException(tr('Please specify a valid amount of seconds, like 1, 0.5, .4, 3.9, 7, etc.'), 'invalid');
    }

}else{
    $seconds = 2;
}

log_console(tr('Restarting in ":seconds" seconds...', array(':seconds' => $seconds)), 'cyan');
sleep($seconds);
cli_restart($delay);
?>
