#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Core\Locale\Language\Import;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/languages/import
 *
 * This script will import data into the languages table from the data/sources/languages/languages file
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./cli system languages import');

Documentation::help('This script allows you to create users



ARGUMENTS (All arguments in square brackets are optional)



[--min] (10)                            If demo mode is enabled, this will specified the minimum amount of records added 
                                        in each library 

[--max] (1000)                          If demo mode is enabled, this will specified the maximum amount of records added 
                                        in each library 

[-d / --demo]                           If specified, will load demo data into the database tables so the system can 
                                        quickly show actual functionality');



// Validate arguments
ArgvValidator::new()
    ->select('--min', true)->isOptional(10)->isNatural()
    ->select('--max', true)->isOptional(1000)->isNatural()
    ->select('-d,--demo')->isOptional()->isBoolean()
    ->noArgumentsLeft()
    ->validate();



Import::new($argv['demo'], $argv['min'], $argv['max'])->execute();