#!/usr/bin/php
<?php

use Phoundation\Cli\Documentation;
use Phoundation\Core\Locale\Language\Import;
use Phoundation\Data\Validator\ArgvValidator;


/**
 * Script system/languages/import
 *
 * This script will import data into the languages table from the data/sources/languages/languages file
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./cli system languages import');

Documentation::help('This script allows you to create users



ARGUMENTS


-');



// Validate arguments
ArgvValidator::new()
    ->noArgumentsLeft()
    ->validate();



Import::execute();