#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\CliDocumentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Os\Processes\Task;


/**
 * Script tasks/execute
 *
 * This script will display detailed information about the current framework, project, database ,etc.
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
CliDocumentation::usage('./pho tasks execute');
CliDocumentation::help('This script can execute one or multiple tasks.

If a task id has been specified, then that specific task will be executed. If not, the system will scan for tasks that are due to be executed and execute them in order.


ARGUMENTS


[-t, --task ID]                         The ID of a specific task that should be executed');


$argv = ArgvValidator::new()
    ->select('-t,--task', true)->isInteger()
    ->validate();


if (empty($argv['task'])) {

} else {
    // Execute this specific task
    $task = Task::get($argv['task'])->execute();
}
