#!/usr/bin/php
<?php

declare(strict_types=1);

use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Virtualization\Docker\DockerFile;


/**
 * Script devops/docker/build
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho devops docker build');
Documentation::help('This script can build docker images');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('-p,--path', true)->isOptional(PATH_ROOT)->isFile()
    ->select('-i,--image', true)->isOptional(strtolower(PROJECT) . '-default')->matchesRegex('/^[a-z-]+$/')
    ->noArgumentsLeft()
    ->validate();


// Build the docker image
DockerFile::new($argv['image'], $argv['path'])
    ->setRestrictions(PATH_ROOT, true)
    ->writeConfig()
    ->build();

