#!/usr/bin/php
<?php

use Phoundation\Cli\Cli;
use Phoundation\Cli\Documentation;
use Phoundation\Data\Validator\ArgvValidator;
use Phoundation\Virtualization\Kubernetes\Pods\Pod;
use Phoundation\Virtualization\Kubernetes\Pods\Pods;


/**
 * Script devops/kubernetes/get/pods
 *
 *
 *
 * @author Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package Phoundation\Scripts
 */
Documentation::usage('./pho devops kubernetes get pods');
Documentation::help('This script returns the available kubernetes pods');


// Validate arguments
$argv = ArgvValidator::new()
    ->select('-n,--name', true)->isOptional()->matchesRegex('/^[a-z0-9-]+$/')
    ->noArgumentsLeft()
    ->validate();

if ($argv['name']) {
    // Display the specified name only
    Pod::new($argv['name'])->getCliForm();
} else {
    // Display all deployments
    $output = Pods::new();
    Cli::displayTable($output);
}
