#!/usr/bin/php
<?php
/*
 * This script can clear the contents of the tmp directory
 */
$usage = './script/base/clear METHOD';

$help = 'The clear script can clear temporary data



METHODS



all                             - Clear all temporary data

tmp                             - Clear only the PATH_TMP directory

cache                           - Clear the cache directory';


$tmp   = false;
$cache = false;

switch (cli_method()) {
    case 'cache':
        cli_no_arguments_left();
        log_console('Clearing cache', 'white');
        $cache = true;
        break;

    case 'tmp':
        cli_no_arguments_left();
        log_console(tr('Clearing tmp path ":tmp"', array(':tmp' => PATH_TMP)), 'white');
        $tmp = true;
        break;

    case 'all':
        log_console(tr('Clearing botch cache and tmp path ":tmp"', array(':tmp' => PATH_TMP)), 'white');
        cli_no_arguments_left();
        $tmp   = false;
        $cache = false;
        break;

    case '':
        throw new CoreException(tr('No method specified'), 'no-method');

    default:
        throw new CoreException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}



/*
 * Clear the PATH_TMP directory
 */
if ($tmp) {
    /*
     * Move PATH_TMP out of the way, then delete it
     */
    $delete = Strings::unslash(PATH_TMP).'~delete';

    rename(PATH_TMP, $delete);
    mkdir(PATH_TMP, $_CONFIG['file']['dir_mode'], true);

    file_delete($delete, false);
    log_console(tr('Done!'), 'green');
}



/*
 * Clear the cache directory
 */
if ($cache) {
    safe_script('base/cache', '--clear');
}
?>