#!/usr/bin/php
<?php
/*
 * This is the servers management script.
 *
 * @auhthor Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @copyright Copyright (c) 2022 Sven Olaf Oostenbrink
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @category Function reference
 * @package base-scripts
 */
$usage = './scripts/domains
./scripts/domains add DOMAIN [DOMAIN DOMAIN ...]
./scripts/domains list domains [options]
./scripts/domains show domain SERVER
./scripts/domains link domain [SERVER SERVER SERVER]
./scripts/domains unlink domain [SERVER SERVER SERVER]';

$help  = 'This is the domains management script

This script can manage the domains.



METHODS



list [%DOMAIN%]                 - List all registerd domains, or by part of
                                  specified domain

        --only-domains          - Show only the domains. Useful with --quiet

        --provider DOMAIN       - List all domains for the specified provider

        --customer CUSTOMER     - List all domains for the specified customer


show DOMAIN                     - Show details about the specified domain

add DOMAIN [SERVER...]          - Add specified domain to the database. If a
                                  list of servers is specified, the domain will
                                  immediately be linked to these servers

update DOMAIN                   - Update specified domain in the database

link DOMAIN SERVER [SERVER...]  - Link the specified domain to the specified
                                  list of servers. Both domain and servers can
                                  be specified by either the domain or their
                                  respectitive id\'s

unlink DOMAIN SERVER [SERVER...]- Unlink the specified domain from the specified
                                  list of servers. Both domain and servers can
                                  be specified by either the domain or their
                                  respectitive id\'s

delete ID | DOMAIN              - Set the status of the specified domain to
                                  "deleted" and remove the SSH fingerprints from
                                  both ssh_fingerprints and the
                                  PATH_ROOT/data/ssh/known_hosts file. Linked servers
                                  will remain linked.

erase ID | DOMAIN               - Erase the specified host from the database.
                                  Linked servers will be (obviously) unlinked

register HOSTNAME [SSH-PORT]    - Add the fingerprints for the specified
                                  domain / port to the ssh_fingerprints table
                                  and the PATH_ROOT/data/ssh/known_host file

unregister HOSTNAME [SSH-PORT]  - Remove the registered domain / port
                                  fingerprints from the PATH_ROOT/data/ssh/known_host
                                  file and the ssh_fingerprints table';


try {
    cli_only();
    load_libs('whois');

    switch (cli_method()) {
        case 'scan':
            $domains = sql_query('SELECT `domain` FROM `domains` WHERE `type` = "scan" AND `status` IS NULL');

            while ($domain = sql_fetch($domains, true)) {
                log_console(tr('Scanning domain ":domain"', array()));

                $results = safe_exec(array('ok_exitcodes' => '1',
                                           'commands'     => array('whois', array($domain, 'connector' => '|'),
                                                                   'grep' , array('Name Server'))));
                $ns      = array();
                $errors  = array();

                foreach ($results as $result) {
                    if (strstr($result, 'Name Server')) {
                        $nameserver = Strings::from($result, 'Name Server');
                        $nameserver = str_replace(':', '', $nameserver);
                        $nameserver = trim($nameserver);
                        $ns[] = $nameserver;

                    } else {
                        /*
                         * No "Name Server" in here, error?
                         *
                         */
                        $errors[] = $result;
                    }
                }

                if ($errors) {
                    foreach ($errors as $error) {
                        log_console(tr('Found possible error ":error"', array(':error' => $error)));
                    }
                }

                if ($ns) {
                    foreach ($ns as $nameserver) {
                        log_console(tr('Found name server record ":nameserver"', array(':nameserver' => $nameserver)));
                    }

                    log_console(tr('Domain ":domain" exists', array(':domain' => $domain)));
                    sql_query('UPDATE `domains` SET `status` = "exists" WHERE `domain` = :domain AND `type` = "scan"', array(':domain' => $domain));

                } else {
                    log_console(tr('Domain ":domain" is available', array(':domain' => $domain)));
                    sql_query('UPDATE `domains` SET `status` = "available" WHERE `domain` = :domain AND `type` = "scan"', array(':domain' => $domain));
                }
            }

            break;

        case 'reset':
            $results = sql_query('UPDATE `domains` SET `status` = NULL WHERE `type` = "scan"');
            $count   = sql_num_rows($results);

            if ($count) {
                log_console(tr('Reset ":count" scanned domains', array(':count' => $count)));

            } else {
                log_console(tr('No scanned domains reset'), 'yellow');
            }

            break;

        case 'add':
            $domain  = cli_arguments(0);
            $server_restrictionss = cli_arguments();
            $count   = 0;

            cli_no_arguments_left();

            try {
                domains_insert(array('domain'  => $domain,
                                     'servers' => $server_restrictionss));

                log_console(tr('Added domain ":domain"', array(':domain' => $domain)), 'green');

            }catch(Exception $e) {
                if ($e->getCode() !== 'validation') {
                    throw $e;
                }

                if (preg_match('/Domain ".+?" already exists/', $e->getMessage())) {
                    log_console(tr('Domain":domain" already exists', array(':domain' => $domain)), 'warning');

                } else {
                    log_console($e);
                }
            }

            break;

        case 'update':
            $server_restrictions['domain'] = cli_argument(0);
            domains_update($server_restrictions);
            break;

        case 'register':
            $server_restrictions = cli_argument(1);
            cli_no_arguments_left();

            $server_restrictions = domains_like($server_restrictions);
            $server_restrictions = domains_get($server_restrictions);
            $count  = ssh_add_known_host($server_restrictions['domain'], $server_restrictions['port']);

            if ($count) {
                log_console(tr('Added ":count" domains', array(':count' => $count)), 'green');

            } else {
                log_console(tr('Added no domains, domain was probably already registered'), 'yellow');
            }

            break;

        case 'unregister':
            $server_restrictions = cli_argument(1);
            cli_no_arguments_left();

            $server_restrictions = domains_like($server_restrictions);
            $server_restrictions = domains_get($server_restrictions);
            $count  = ssh_remove_known_host($server_restrictions['domain'], $server_restrictions['port']);

            if ($count) {
                log_console(tr('Removed ":count" domains', array(':count' => $count)), 'green');

            } else {
                log_console(tr('Removed no domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'delete':
            $status = ensure_variable($status, 'deleted');
            // FALLTHROUH

        case 'undelete':
            $status = ensure_variable($status, null);
            // FALLTHROUH

        case 'status':
            $server_restrictions = cli_argument(1);
            $status   = ensure_variable($status, cli_argument(2));
            cli_no_arguments_left();

            $count = domains_unregister_host(array('domain'      => $server_restrictions,
                                                   'identity_file' => $identity_file));

            if ($count) {
                log_console(tr('Removed ":count" hashed domains', array(':count' => $count)), 'green');

            } else {
                log_console(tr('Removed no hashed domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'erase':
            $server_restrictions = cli_argument(1);
            cli_no_arguments_left();

            $count = domains_unregister_host(array('domain'      => $server_restrictions,
                                                   'identity_file' => $identity_file));

            if ($count) {
                log_console(tr('Removed ":count" hashed domains', array(':count' => $count)), 'green');

            } else {
                log_console(tr('Removed no hashed domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'list':
            $only_domains = cli_argument('--only-domains');
            $customer       = cli_argument('--customer', true);
            $provider       = cli_argument('--provider', true);
            $execute        = array();
            $where          = array();

            cli_no_arguments_left();

            if (DELETED) {
                $where[] = ' `domains`.`status` = "deleted" ';

            } elseif (!$core->register['all']) {
                $where[] = ' `domains`.`status` IS NULL OR `domains`.`status` = "testing" ';
            }

            if (STATUS) {
                $execute = array_merge($execute, sql_in(STATUS));
                $where[] = ' `domains`.`status` IN ('.implode(', ', array_keys(STATUS)).') ';
            }

            if ($customer) {
                load_libs('customers');
                $customers_id = customers_get(array('columns' => 'id',
                                                    'filters' => array('seoname' => $customer)));

                if (!$customers_id) {
                    throw new CoreException(tr('The specified customer ":customer" does not exist', array(':customer' => $customer)), 'warning');
                }

                $execute[':customers_id'] = $customers_id;
                $where[] = ' `domains`.`customers_id` = :customers_id ';
            }

            if ($provider) {
                load_libs('providers');
                $providers_id = providers_get($provider, 'id');

                if (!$providers_id) {
                    throw new CoreException(tr('The specified provider ":provider" does not exist', array(':provider' => $provider)), 'warning');
                }

                $execute[':providers_id'] = $providers_id;
                $where[] = ' `domains`.`providers_id` = :providers_id ';
            }

            $query   = 'SELECT    `domains`.`id`,
                                  `domains`.`domain`,
                                  `domains`.`seodomain`,
                                  `domains`.`status`,
                                  `domains`.`createdon`,
                                  `domains`.`description`,

                                  `customers`.`name` AS `customer`,

                                  `providers`.`name` AS `provider`,

                                  `users`.`name`     AS `user_name`,
                                  `users`.`email`    AS `user_email`,
                                  `users`.`username` AS `user_username`,
                                  `users`.`nickname` AS `user_nickname`

                        FROM      `domains`

                        LEFT JOIN `customers`
                        ON        `customers`.`id` = `domains`.`customers_id`

                        LEFT JOIN `providers`
                        ON        `providers`.`id` = `domains`.`providers_id`

                        LEFT JOIN `users`
                        ON        `users`.`id` = `domains`.`created_by`';

            if (empty($where)) {
                $where = '';

            } else {
                $where = ' WHERE '.implode(' AND ', $where);
            }

            $order   = ' ORDER BY `domains`.`status` IS NOT NULL DESC ';
            $server_restrictionss = sql_query($query.$where.$order.sql_limit(), $execute);

            if (!$server_restrictionss->rowCount()) {
                    log_console(tr('There are currently no servers registered'), 'QUIET/yellow');

            } else {
                if ($only_domains) {
                    log_console(tr('Hostname'), 'QUIET/cyan');

                    while ($server_restrictions = sql_fetch($server_restrictionss)) {
                        log_console($server_restrictions['domain']);
                    }

                } else {
                    log_console(Strings::size(tr('#id'), 7).Strings::size(tr('Customer'), 25).Strings::size(tr('Provider'), 25).Strings::size(tr('Hostname'), 33).Strings::size(tr('Status'), 13).Strings::size(tr('Created by'), 32), 'QUIET/cyan');

                    while ($server_restrictions = sql_fetch($server_restrictionss)) {
                        log_console(Strings::size($server_restrictions['id'], 6, ' ', true).' '.Strings::size($server_restrictions['customer'], 24).' '.Strings::size($server_restrictions['provider'], 24).' '.Strings::size($server_restrictions['domain'], 32).' '.cli_status_color(Strings::size($server_restrictions['status'], 12)).' '.name($server_restrictions, 'user'));
                    }
                }
            }

            break;

        case '':
            throw new CoreException(tr('No method specified'), 'not-specified');

        default:
            throw new CoreException(tr('Unknown argument ":method" specified', array(':method' => cli_method())), 'unknown');
    }

}catch(Exception $e) {
    switch ($e->getCode()) {
        case 'not-exists':
            // FALLTHROUGH
        case 'multiple':
            // FALLTHROUGH
        case 'sudo':
            throw $e->makeWarning(true);
    }

    throw $e;
}
?>