#!/usr/bin/php
<?php
/*
 * This script can return various stats about the website
 */


try {
    foreach ($argv as $arg) {
        switch ($arg) {
            case 'all':
// :TODO: Implement
                break;

            case 'users':
// :TODO: Implement
                break;

            case 'sessions':
// :TODO: Implement
                break;

            case 'errors':
// :TODO: Implement
                break;
        }
    }

}catch(Exception $e) {
    throw new CoreException('scripts/stat: Failed', $e);
}
?>
