<?php

/**
 * Class Response
 *
 * This class manages the execution and processing of response to Commands, HTML, AJAX and API requests.
 *
 * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Copyright © 2025 Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
 * @package   Phoundation\Web
 */


declare(strict_types=1);

namespace Phoundation\Web\Requests;

use JetBrains\PhpStorm\NoReturn;
use Phoundation\Accounts\Users\Locale\Language\Interfaces\LanguageInterface;
use Phoundation\Accounts\Users\Locale\Language\Language;
use Phoundation\Accounts\Users\Sessions\Exception\SessionNotInitializedException;
use Phoundation\Accounts\Users\Sessions\Session;
use Phoundation\Cache\Cache;
use Phoundation\Cache\LocalCache;
use Phoundation\Core\Core;
use Phoundation\Core\Log\Log;
use Phoundation\Data\Interfaces\IteratorInterface;
use Phoundation\Data\Iterator;
use Phoundation\Data\Traits\TraitDataStaticContentType;
use Phoundation\Data\Traits\TraitDataStaticExecuted;
use Phoundation\Data\Traits\TraitDataStaticFlashMessages;
use Phoundation\Data\Traits\TraitGetInstance;
use Phoundation\Data\Validator\Exception\ValidatorException;
use Phoundation\Databases\Sql\Sql;
use Phoundation\Date\PhoDate;
use Phoundation\Date\PhoTime;
use Phoundation\Developer\Project\Project;
use Phoundation\Exception\OutOfBoundsException;
use Phoundation\Filesystem\Exception\FilesystemException;
use Phoundation\Filesystem\PhoPath;
use Phoundation\Filesystem\PhoRestrictions;
use Phoundation\Filesystem\Traits\TraitDataStaticRestrictions;
use Phoundation\Notifications\Notification;
use Phoundation\Os\Processes\Process;
use Phoundation\Utils\Arrays;
use Phoundation\Utils\Numbers;
use Phoundation\Utils\Strings;
use Phoundation\Web\Html\Components\Interfaces\RenderInterface;
use Phoundation\Web\Html\Components\Script;
use Phoundation\Web\Html\Components\Widgets\Breadcrumbs\Breadcrumbs;
use Phoundation\Web\Html\Components\Widgets\Interfaces\BreadcrumbsInterface;
use Phoundation\Web\Html\Enums\EnumAttachJavascript;
use Phoundation\Web\Html\Enums\EnumJavascriptWrappers;
use Phoundation\Web\Http\Exception\HttpException;
use Phoundation\Web\Http\Interfaces\UrlInterface;
use Phoundation\Web\Http\Url;
use Phoundation\Web\Requests\Enums\EnumHeaderFooterType;
use Phoundation\Web\Requests\Enums\EnumRequestTypes;
use Phoundation\Web\Requests\Exception\PageNotFoundException;
use Phoundation\Web\Requests\Exception\ResponseHeadersException;
use Phoundation\Web\Requests\Exception\ResponseRedirectException;
use Phoundation\Web\Requests\Interfaces\ResponseInterface;
use Phoundation\Web\Uploads\Interfaces\UploadHandlersInterface;
use Stringable;
use Throwable;


class Response implements ResponseInterface
{
    use TraitDataStaticFlashMessages;
    use TraitDataStaticContentType;
    use TraitDataStaticExecuted;
    use TraitDataStaticRestrictions;
    use TraitGetInstance;


    /**
     * Singleton instance
     *
     * @var ResponseInterface $instance
     */
    protected static ResponseInterface $instance;

    /**
     * The output generated by the request
     *
     * @var string|null $output
     */
    protected static ?string $output = null;

    /**
     * The status code that will be returned to the client
     *
     * @var int $http_code
     */
    protected static int $http_code = 200;

    /**
     * Tracks if Response::sendHeaders() sent headers already or not.
     *
     * @note IMPORTANT: Since flush() and ob_flush() will NOT lock headers until the buffers are actually flushed, and
     *                  they will neither actually flush the buffers as long as the process is running AND the buffers
     *                  are not full yet, weird things can happen. With a buffer of 4096 bytes (typically), echo 100
     *                  characters, and then execute Response::sendHeaders(), then ob_flush() and flush() and
     *                  headers_sent() will STILL be false, and REMAIN false until the buffer has reached 4096
     *                  characters OR the process ends. This variable just keeps track if Response::sendHeaders() has been
     *                  executed (and it will not execute again), but headers might still be sent out manually. This is
     *                  rather messed up, because it really shows as if information was sent, the buffers are flushed,
     *                  yet nothing is actually flushed, so the headers are also not sent. This is just messed up PHP.
     *
     * @var bool $http_headers_sent
     */
    protected static bool $http_headers_sent = false;

    /**
     * Keeps track on if the HTML headers have been sent / generated or not
     *
     * @var bool $html_headers_sent
     */
    protected static bool $html_headers_sent = false;

    /**
     * Information that goes into the HTML header
     *
     * @var IteratorInterface $http_headers
     */
    protected static IteratorInterface $http_headers;

    /**
     * CORS headers
     *
     * @var array $cors
     */
    protected static array $cors = [];

    /**
     * Classes to apply on default sections of the page
     *
     * @var array $page_classes
     */
    protected static array $page_classes = [];

    /**
     * The client specified ETAG for this request
     *
     * @var string|null $etag
     */
    protected static ?string $etag = null;

    /**
     * !DOCTYPE variable
     *
     * @var string
     */
    protected static string $doctype = 'html';

    /**
     * The browser page title
     *
     * @var string|null $page_title
     */
    protected static ?string $page_title = null;

    /**
     * The browser page description
     *
     * @var string|null $description
     */
    protected static ?string $description = null;

    /**
     * The page header title
     *
     * @var string|null $header_title
     */
    protected static ?string $header_title = null;

    /**
     * The page header subtitle
     *
     * @var string|null $header_sub_title
     */
    protected static ?string $header_sub_title = null;

    /**
     * Bread crumbs for this page
     *
     * @var Breadcrumbs
     */
    protected static Breadcrumbs $bread_crumbs;

    /**
     * If true, the template will build the <body> tag. If false, the page will have to build it itself
     *
     * @var bool $render_main_wrapper
     */
    protected static bool $render_main_wrapper = true;

    /**
     * @var string $language_code
     */
    protected static string $language_code;

    /**
     * @var LanguageInterface $language
     */
    protected static LanguageInterface $language;

    /**
     * Tracks data that goes into the HTML footers
     *
     * @var array $page_footers
     */
    protected static array $page_footers = [];

    /**
     * Tracks data that goes into the HTML headers
     *
     * @var array $page_headers
     */
    protected static array $page_headers = [];

    /**
     * Tracks the total number of bytes sent
     *
     * @var int $bytes_sent
     */
    protected static int $bytes_sent = 0;

    /**
     * Tracks attributes for the <head> tag
     *
     * @var Iterator $_head_data_attributes
     */
    protected static Iterator $_head_data_attributes;

    /**
     * Tracks direct output mode that will bypass everything and send program output to client directly
     *
     * @var bool $direct_output_mode
     */
    protected static bool $direct_output_mode = false;


    /**
     * Response class constructor
     */
    protected function __construct()
    {
        // Take file access restrictions from the Request object
        static::$_restrictions = Request::getRestrictionsObject();

        // Add required HTTP headers
        // TODO Add support for "vary" header
        Response::addHttpHeaders(config()->get('web.headers.accept-ch', ['Sec-CH-UA, Device-Memory, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Viewport-Width, Width, Sec-CH-Prefers-Color-Scheme']), 'Accept-CH');

        // Add required page headers
        Response::addConfiguredHeadDataAttribute();
        Response::setCharset(Response::getCharset());
    }


    /**
     * Initializes the Response object
     *
     * @return void
     */
    public static function initialize(): void
    {
        Response::getInstance();
    }


    /**
     * Returns the total number of bytes sent to the client
     *
     * @return int
     */
    public static function getBytesSent(): int
    {
        return static::$bytes_sent;
    }


    /**
     * Returns direct output mode that will bypass everything and send program output to client directly
     *
     * @return bool
     */
    public static function getDirectOutputMode(): bool
    {
        return static::$direct_output_mode;
    }


    /**
     * Sets direct output mode that will bypass everything and send program output to client directly
     *
     * @param bool $direct_output_mode
     *
     * @return void
     */
    public static function setDirectOutputMode(bool $direct_output_mode): void
    {
        static::$direct_output_mode = $direct_output_mode;
    }


    /**
     * Returns the alternative class for the <body> tag or if not preset, the default
     *
     * @return bool
     */
    public static function getRenderMainWrapper(): bool
    {
        return static::$render_main_wrapper;
    }


    /**
     * Sets an alternative class for the <body> tag
     *
     * @param bool $render_main_wrapper
     *
     * @return void
     */
    public static function setRenderMainWrapper(bool $render_main_wrapper): void
    {
        static::$render_main_wrapper = $render_main_wrapper;
    }


    /**
     * Sets the class for the given page section
     *
     * @param string $class
     * @param string $section
     *
     * @return void
     */
    public static function setClass(string $class, string $section): void
    {
        static::$page_classes[$section] = $class;
    }


    /**
     * Sets the class for the given page section
     *
     * @param string $class
     * @param string $section
     *
     * @return void
     */
    public static function defaultClass(string $class, string $section): void
    {
        if (empty(static::$page_classes[$section])) {
            static::$page_classes[$section] = $class;
        }
    }


    /**
     * Returns the class for the given section, if available
     *
     * @param string      $section
     * @param string|null $default
     *
     * @return string|null
     */
    public static function getClass(string $section, ?string $default = null): ?string
    {
        return array_get_safe(static::$page_classes, $section, $default);
    }


    /**
     * Returns the bread crumbs for this page
     *
     * @return BreadcrumbsInterface
     */
    public static function getBreadcrumbs(): BreadcrumbsInterface
    {
        if (empty(static::$bread_crumbs)) {
            static::$bread_crumbs = new Breadcrumbs();
        }

        return static::$bread_crumbs;
    }


    /**
     * Sets the bread crumbs for this page
     *
     * @param BreadcrumbsInterface|array|null $bread_crumbs
     *
     * @return void
     */
    public static function setBreadcrumbs(BreadcrumbsInterface|array|null $bread_crumbs = null): void
    {
        if (empty($bread_crumbs)) {
            static::$bread_crumbs = new Breadcrumbs();

        } elseif(is_array($bread_crumbs)) {
            static::$bread_crumbs = new Breadcrumbs($bread_crumbs);

        } else {
            static::$bread_crumbs = $bread_crumbs;
        }
    }


    /**
     * Returns the DOCTYPE value
     *
     * @return string
     */
    public static function getDocType(): string
    {
        return static::$doctype;
    }


    /**
     * Sets  the DOCTYPE value
     *
     * @param string $doctype
     *
     * @return void
     */
    public static function setDoctype(string $doctype): void
    {
        static::$doctype = $doctype;
    }


    /**
     * Returns the browser page title
     *
     * @return string|null
     */
    public static function getDescription(): ?string
    {
        return static::$description;
    }


    /**
     * Sets the browser page description
     *
     * @param string|null $description
     *
     * @return void
     */
    public static function setDescription(?string $description): void
    {
        static::$description = strip_tags($description);
    }


    /**
     * Returns the page header title
     *
     * @return string|null
     */
    public static function getHeaderTitle(): ?string
    {
        return static::$header_title;
    }


    /**
     * Sets the page header title
     *
     * @param Stringable|string|float|int|null $header_title
     * @param bool                             $force
     *
     * @return void
     */
    public static function setHeaderTitle(Stringable|string|float|int|null $header_title, bool $force = true): void
    {
        if (empty(static::$header_title) or $force) {
            static::$header_title = get_null((string) $header_title);

            if (!static::$page_title) {
                static::$page_title = Project::getHumanReadableFullName() . ' - ' . $header_title;
            }
        }
    }


    /**
     * Returns the page header subtitle
     *
     * @return string|null
     */
    public static function getHeaderSubTitle(): ?string
    {
        return static::$header_sub_title;
    }


    /**
     * Sets the page header subtitle
     *
     * @param Stringable|string|float|int|null $header_sub_title
     * @param bool                             $force
     *
     * @return void
     */
    public static function setHeaderSubTitle(Stringable|string|float|int|null $header_sub_title, bool $force = true): void
    {
        if (empty(static::$header_title) or $force) {
            static::$header_sub_title = get_null((string) $header_sub_title);
        }
    }


    /**
     * Returns the page character_set
     *
     * @return string|null
     */
    public static function getCharset(): ?string
    {
        return array_get_safe(static::$page_headers, 'meta-character_set');
    }


    /**
     * Sets the page character_set
     *
     * @param string|null $character_set
     *
     * @return void
     */
    public static function setCharset(?string $character_set): void
    {
        Response::addMetaToPageHeaders($character_set, 'character_set');
    }


    /**
     * Returns the page viewport
     *
     * @return string|null
     */
    public static function getViewport(): ?string
    {
        return array_get_safe(static::$page_headers, 'meta-viewport');
    }


    /**
     * Sets the page viewport
     *
     * This method will try to set the specified viewport header. If no viewport was specified, it will try to use the viewport from configuration path
     * "web.viewport". If that was not set, it will default to viewport "width=device-width, initial-scale=1, shrink-to-fit=no"
     *
     * @param string|null $viewport
     *
     * @return void
     */
    public static function setViewport(?string $viewport): void
    {
        Response::addMetaToPageHeaders($viewport ?? config()->get('web.viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no'), 'viewport');
    }


    /**
     * Set the favicon for this page
     *
     * @param string|null $url
     *
     * @return void
     */
    public static function setFavIcon(?string $url = null): void
    {
        try {
            if (empty($url)) {
                $_file = PhoPath::new('img/favicons/project.png', PhoRestrictions::newReadonlyObject(DIRECTORY_PROJECT_CDN), DIRECTORY_PROJECT_CDN);
                $_url  = Url::newFromPath($_file)->makeImg();
                $url    = $_url->getSource();

                Response::addLinkToPageHeaders([
                    'rel'  => 'icon',
                    'href' => $url,
                    'type' => $_file->getMimetype(),
                ], $url);

            } else {
                $_url = Url::new($url)->makeImg();
                $_url = $_url->setSource(Response::versionFile($url, 'img'));
                $url   = $_url->getSource();

                // Unknown (likely remote?) link
                Response::addLinkToPageHeaders([
                    'rel'  => 'icon',
                    'href' => $url,
                    'type' => 'image/' . Strings::fromReverse($url, '.'),
                ], $url);
            }

            Response::setAppleIcons($url);

        } catch (FilesystemException $e) {
            Log::warning(ts('Failed to find favicon, see next message for more information'), 3);
            Log::warning($e->makeWarning(), 3);
        }
    }


    /**
     * Adds apple touch icons to the site with correct locations
     *
     * @param string $url
     *
     * @return void
     */
    protected static function setAppleIcons(string $url): void
    {
        // Do we even want to add these apple touch icons?
        if (!config()->getBoolean('web.icons.apple.enable', false)) {
            return;
        }

        // The sizes we need to support, jeeeezz...
        $sizes = [
            '57x57',
            '60x60',
            '72x72',
            '76x76',
            '114x114',
            '120x120',
            '144x144',
            '152x152',
            '180x180',
        ];

        // apple icons should be in the same path as the favicons
        $url = Strings::untilReverse($url, '/') . '/';

        foreach ($sizes as $size) {
            Response::addLinkToPageHeaders([
                'rel'   => 'apple-touch-icon',
                'sizes' => $size,
                'href'  => Url::new($url . 'apple-touch-icon-' . $size . '.png')->makeImg(),
                'type'  => 'image/png', // Require these files to always be PNG as we do not want to do a mimetype lookup because apple likes being a ...
            ], 'apple-touch-icon-' . $size . '.png');

            if (config()->getBoolean('web.icons.apple.precomposed', true)) {
                // Because of course, lets add an entire other set too just for apple, why not?
                Response::addLinkToPageHeaders([
                    'rel'   => 'apple-touch-icon-precomposed',
                    'sizes' => $size,
                    'href'  => Url::new($url . 'apple-touch-icon-' . $size . '-precomposed.png')->makeImg(),
                    'type'  => 'image/png', // Require these files to always be PNG as we do not want to do a mimetype lookup because apple likes being a ...
                ], 'apple-touch-icon-' . $size . '-precomposed.png');
            }
        }
    }


    /**
     * Will automatically add the timestamp of the specified file as a versioning string
     *
     * This is done for efficient caching where you can pretty much set cache to 10 years as changes are picked up by
     * updated versions of the files
     *
     * @see http://particletree.com/notebook/automatically-version-your-css-and-javascript-files/
     *
     * @todo Move this to the URL class, and be probably used somewhere in the ->makeCdn() call?
     * @param string $url
     * @param string $type
     *
     * @return string
     */
    public static function versionFile(string $url, string $type): string
    {
        static $minified = null;

        // Ensure the extension is stripped.
        // Ensure anything before templates/ is stripped.
        $url = Strings::untilReverse($url, '.' . $type);
        $url = Strings::until($url, '.min');
        $url = Strings::from($url, 'templates/');

        if ($minified === null) {
            // All files are minified or none are
            $minified = (config()->get('web.cdn.resources.minified', true) ? '.min' : '');
        }

        // Return URL with timestamp injected into the given file
        if (config()->getBoolean('web.cdn.resources.versioning', true)) {
            // Determine the absolute file path
            return $url . '-v' . filectime(DIRECTORY_DATA . 'content/cdn/' . LANGUAGE . '/templates/' . $url . $minified . '.' . $type) . $minified . '.' . $type;
        }

        // Return URL without an injected timestamp
        return $url . $minified . '.' . $type;
    }


    /**
     * Returns true if the specified HTTP code is the specified HTTP code
     *
     * @param int $code
     *
     * @return bool
     */
    public static function isHttpCode(int $code): bool
    {
        return static::$http_code === $code;
    }


    /**
     * Returns true if the HTTP headers have been sent
     *
     * @return bool
     */
    public static function getHttpHeadersSent(): bool
    {
        return static::$http_headers_sent;
    }


    /**
     * Returns the HTTP headers for this response
     *
     * @return IteratorInterface
     */
    public static function getHttpHeaders(): IteratorInterface
    {
        if (empty(static::$http_headers)) {
            static::$http_headers = new Iterator();
        }

        return static::$http_headers;
    }


    /**
     * Sets the HTTP headers for this response
     *
     * @param IteratorInterface|array $http_headers
     *
     * @return void
     */
    public static function setHttpHeaders(IteratorInterface|array $http_headers): void
    {
        static::$http_headers = new Iterator($http_headers);
        Response::addHttpHeaders($http_headers);
    }


    /**
     * Adds the specified HTTP headers for this response
     *
     * @param IteratorInterface|array|string $http_headers
     * @param string|null                    $key
     *
     * @return void
     */
    public static function addHttpHeaders(IteratorInterface|array|string $http_headers, ?string $key = null): void
    {
        $_headers = Response::getHttpHeaders();

        if (is_string($http_headers)) {
            $_headers->add(($key ? Strings::ensureEndsWith($key, ':') : null) . $http_headers);

        } else {
            foreach ($http_headers as $header => $value) {
                if ($value === false) {
                    // Do not add this header
                    continue;
                }

                if ($key) {
                    Response::addHttpHeaders($value, $key);

                } else {
                    Response::addHttpHeaders($value, $header);
                }
            }
        }
    }


    /**
     * Sets the CORS response headers
     *
     * @param string $origin
     * @param string $methods
     * @param string $headers
     *
     * @return void
     * @todo Implement
     */
    public static function setCors(string $origin, string $methods, string $headers): void
    {
        // Validate CORS data
        // TODO implement validation
        static::$cors = [
            'origin'  => '*.',
            'methods' => 'GET, POST',
            'headers' => '',
        ];
    }


    /**
     * Returns if the HTML headers have been sent
     *
     * @return bool
     */
    public static function getHtmlHeadersSent(): bool
    {
        return static::$html_headers_sent;
    }


    /**
     * Returns the correct header type prefix for the specified header type
     *
     * @param EnumHeaderFooterType|string $type
     *
     * @return string|null
     */
    protected static function getHeaderTypePrefix(EnumHeaderFooterType|string $type): ?string
    {
        if (is_string($type)) {
            $type = EnumHeaderFooterType::from(strtolower($type));
        }

        if ($type === EnumHeaderFooterType::autodetect) {
            // The specified header key should already have a type header. Usually, this comes from the Cache object
            return null;

        }

        return $type->value . '/';
    }


    /**
     * Adds the specified header item to the "headers" list
     *
     * @param EnumHeaderFooterType|string $type
     * @param IteratorInterface|array     $headers
     * @param bool                        $prefix
     *
     * @return void
     */
    public static function addPageHeaders(EnumHeaderFooterType|string $type, IteratorInterface|array $headers, bool $prefix = false): void
    {
        if (is_string($type)) {
            $type = EnumHeaderFooterType::from($type);
        }

        $headers = Arrays::force($headers, null);

        if ($prefix) {
            $headers = array_reverse($headers);
        }

        foreach ($headers as $key => $value) {
            Response::addPageHeader($type, $value, $key, $prefix);
        }
    }


    /**
     * Adds the specified header item to the "headers" list
     *
     * @param EnumHeaderFooterType|string                                   $type
     * @param RenderInterface|IteratorInterface|array|string|int|float|null $value
     * @param string|null                                                   $key
     * @param bool                                                          $prefix
     *
     * @return void
     */
    public static function addPageHeader(EnumHeaderFooterType|string $type, RenderInterface|IteratorInterface|array|string|int|float|null $value, ?string $key = null, bool $prefix = false): void
    {
        $type = Response::getHeaderTypePrefix($type);

        if ($prefix) {
            static::$page_headers = array_merge([$type . $key => $value], static::$page_headers);

        } else {
            static::$page_headers[$type . $key] = $value;
        }
    }


    /**
     * Adds the specified footer item to the "footers" list
     *
     * @param EnumHeaderFooterType|string $type
     * @param array|string                $footers
     * @param bool                        $prefix
     *
     * @return void
     */
    public static function addPageFooters(EnumHeaderFooterType|string $type, array|string $footers, bool $prefix = false): void
    {
        if (is_string($type)) {
            $type = EnumHeaderFooterType::from($type);
        }

        $footers = Arrays::force($footers, null);

        if ($prefix) {
            $footers = array_reverse($footers);
        }

        foreach ($footers as $key => $value) {
            Response::addPageFooter($type, $value, $key, $prefix);
        }
    }


    /**
     * Adds the specified footer to the "footers" list
     *
     * @param EnumHeaderFooterType|string                                   $type
     * @param RenderInterface|IteratorInterface|array|string|int|float|null $value
     * @param string|null                                                   $key
     * @param bool                                                          $prefix
     *
     * @return void
     */
    public static function addPageFooter(EnumHeaderFooterType|string $type, RenderInterface|IteratorInterface|array|string|int|float|null $value, ?string $key = null, bool $prefix = false): void
    {
        $type = Response::getHeaderTypePrefix($type);

        if ($prefix) {
            static::$page_footers = array_merge([$type . $key => $value], static::$page_footers);

        } else {
            static::$page_footers[$type . $key] = $value;
        }
    }


    /**
     * Add the specified HTML to the HEAD tag
     *
     * @param RenderInterface|array|string|int|float|null $value
     * @param bool                                        $prefix
     *
     * @return void
     * @todo This should -in the near future- be updated to sending Javascript, Css, etc objects instead of "some array"
     */
    public static function addHtmlToPageHeaders(RenderInterface|array|string|int|float|null $value, bool $prefix = false): void
    {
        static $count = 0;
        Response::addPageHeader(EnumHeaderFooterType::html, $value, 'html' . $count++, $prefix);
    }


    /**
     * Add the specified HTML to the footer
     *
     * @param RenderInterface|array|string|int|float|null $value
     * @param bool                                        $prefix
     *
     * @return void
     * @todo This should -in the near future- be updated to sending Javascript, Css, etc objects instead of "some array"
     */
    public static function addHtmlToPageFooters(RenderInterface|array|string|int|float|null $value, bool $prefix = false): void
    {
        static $count = 0;
        Response::addPageFooter(EnumHeaderFooterType::html, $value, 'html' . $count++, $prefix);
    }


    /**
     * Add meta page header
     *
     * @param IteratorInterface|array|string|int|float|null $value
     * @param Stringable|string                             $key
     * @param bool                                          $prefix
     *
     * @return void
     */
    public static function addMetaToPageHeaders(IteratorInterface|array|string|int|float|null $value, Stringable|string $key, bool $prefix = false): void
    {
        Response::addPageHeader(EnumHeaderFooterType::meta, $value, (string) $key, $prefix);
    }


    /**
     * Add link page header
     *
     * @param IteratorInterface|array|string|int|float|null $value
     * @param Stringable|string                             $key
     * @param bool                                          $prefix
     *
     * @return void
     */
    public static function addLinkToPageHeaders(IteratorInterface|array|string|int|float|null $value, Stringable|string $key, bool $prefix = false): void
    {
        Response::addPageHeader(EnumHeaderFooterType::link, $value, (string) $key, $prefix);
    }


    /**
     * Load the specified JavaScript file(s) by adding them to the "headers" or "footers" list
     *
     * @param string|array $urls
     * @param bool|null    $header
     * @param bool         $prefix If true, the scripts are added at the beginning of the "headers" or "footers" list
     *
     * @return void
     */
    public static function loadJavaScript(string|array $urls, ?bool $header = null, bool $prefix = false): void
    {
        if ($header === null) {
            $header = !config()->getBoolean('web.javascript.delay', true);
        }

        if ($header and static::$html_headers_sent) {
            Log::warning(ts('Not adding files ":files" to HTML headers as the HTML headers have already been generated', [
                ':files' => $urls,
            ]));
        }

        $scripts = [];

        // Convert the given URL (parts) to real URLs and add it to the "scripts" list
        foreach (Arrays::force($urls, ',') as $url) {
            if (!Url::isValidUrl($url)) {
                // Pre-process local URL's
                $url = Strings::ensureEndsNotWith($url, '.js');
                $url = Strings::ensureEndsNotWith($url, '.min');
                $url = Response::versionFile($url, 'js');
            }

            $scripts[$url] = [
                'type' => 'text/javascript',
                'src'  => Url::new($url)->makeJs(),
            ];
        }

        // Add scripts to header or footer
        if ($header) {
            Response::addPageHeaders(EnumHeaderFooterType::javascript, $scripts, $prefix);

        } else {
            Response::addPageFooters(EnumHeaderFooterType::javascript, $scripts, $prefix);
        }
    }


    /**
     * Load the specified CSS file(s)
     *
     * @param UrlInterface|array|string $urls
     * @param bool                      $prefix If true, the scripts are added at the beginning of the "headers" list
     *
     * @return void
     */
    public static function loadCss(UrlInterface|array|string $urls, bool $prefix = false): void
    {
        $scripts = [];

        // Convert the given URL (parts) to real URLs
        foreach (Arrays::force($urls, '') as $url) {
            if (!Url::isValidUrl($url)) {
                // Pre-process local URL's
                $url = Strings::ensureEndsNotWith($url, '.css');
                $url = Strings::ensureEndsNotWith($url, '.min');
                $url = Response::versionFile($url, 'css');
            }

            $scripts[$url] = [
                'rel'  => 'stylesheet',
                'href' => Url::new($url)->makeCss(),
            ];
        }

        Response::addPageHeaders(EnumHeaderFooterType::link, $scripts, $prefix);
    }


    /**
     * Returns the current page headers for this request
     *
     * @return array
     */
    public static function getPageHeaders(): array
    {
        return static::$page_headers;
    }


    /**
     * Returns the current page footers for this request
     *
     * @return array
     */
    public static function getPageFooters(): array
    {
        return static::$page_footers;
    }


    /**
     * Returns the current number of page headers
     *
     * @return int
     */
    public static function getPageHeadersCount(): int
    {
        return count(static::$page_headers);
    }


    /**
     * Returns the current number of page footers
     *
     * @return int
     */
    public static function getPageFootersCount(): int
    {
        return count(static::$page_footers);
    }


    /**
     * Returns the current number of page headers and footers
     *
     * @return int
     */
    public static function getPageHeadersFootersCount(): int
    {
        return Response::getPageHeadersCount() + Response::getPageFootersCount();
    }


    /**
     * Returns the specified amount of last page headers
     *
     * @param int $count
     * @return array
     */
    public static function getLastAmountOfPageHeaders(int $count): array
    {
        return array_slice(static::$page_headers, -$count, preserve_keys: true);
    }


    /**
     * Returns the specified amount of last page footers
     *
     * @param int $count
     * @return array
     */
    public static function getLastAmountOfPageFooters(int $count): array
    {
        return array_slice(static::$page_footers, -$count, preserve_keys: true);
    }


    /**
     * Builds and return the HTML <head> tag
     *
     * @return string|null
     */
    public static function renderHtmlHeaders(): ?string
    {
        $return = Request::getPageObject()?->renderHtmlHeaders(static::$doctype);

        if (Response::getPageTitle()) {
            $return .= '<title>' . (Core::isProductionEnvironment() ? null : '(' . ENVIRONMENT . ') ') . static::$page_title . '</title>' . PHP_EOL;
        }

        foreach (static::$page_headers as $key => $value) {
            $return .= Response::renderHtmlHeaderOrFooter($value, $key);
        }

        static::$html_headers_sent = true;

        return $return . '</head>';
    }


    /**
     * Renders and returns the <head> tag
     *
     * @return string|null
     */
    public static function renderHeadTag(): ?string
    {
        return '<head' . Response::renderHtmlHeadTagData() . '>';
    }


    /**
     * Renders and returns the <head> data attributes
     *
     * @return string|null
     */
    public static function renderHtmlHeadTagData(): ?string
    {
        $data = Response::getHeadDataAttributes(false);

        if (!$data) {
            return null;
        }

        $return = [];

        foreach ($data as $key => $value) {
            $return[] = 'data-' . $key . '="' . $value . '"';
        }

        return ' ' . implode(' ', $return);
    }


    /**
     * Returns the <head> tag "data" attributes Iterator object
     *
     * @param bool $auto_initialize
     *
     * @return IteratorInterface|null
     */
    public static function getHeadDataAttributes(bool $auto_initialize = true): ?IteratorInterface
    {
        if (empty(static::$_head_data_attributes)) {
            if (!$auto_initialize) {
                return null;
            }

            static::$_head_data_attributes = new Iterator();
        }

        return static::$_head_data_attributes;
    }


    /**
     * Adds the specified data attribute to the head tag
     *
     * @return void
     */
    protected static function addConfiguredHeadDataAttribute(): void
    {
        foreach (config()->getArray('web.headers.meta.default', ['robots' => 'noindex,nofollow']) as $key => $value) {
            Response::addMetaToPageHeaders($value, $key);
        }
    }


    /**
     * Adds the specified data attribute to the head tag
     *
     * @param Stringable|string|float|int|null $value
     * @param Stringable|string|float|int|null $key
     *
     * @return void
     */
    public static function addHeadDataAttribute(Stringable|string|float|int|null $value, Stringable|string|float|int|null $key): void
    {
        Response::getHeadDataAttributes()->add($value, $key);
    }


    /**
     * Build and return the HTML page_footers
     *
     * @return string|null
     * @todo This should be upgraded to using Javascript / Css objects
     */
    public static function renderHtmlFooters(): ?string
    {
        Log::warning('TODO Reminder: Response::buildFooters() should be upgraded to using Javascript / Css objects');

        $return = '';

        foreach (static::$page_footers as $key => $value) {
            $return .= Response::renderHtmlHeaderOrFooter($value, $key);
        }

//        foreach (static::$page_footers as $footer) {
//            if (isset($footer['src'])) {
//                $footer = Arrays::implodeWithKeys($footer, ' ', '=', '"');
//                $return .= '<script ' . $footer . '></script>' . PHP_EOL;
//
//            } elseif (isset($footer['content'])) {
//                if ($footer['content'] instanceof ScriptInterface) {
//                    $footer['content']->setAttach(EnumAttachJavascript::here)->render();
//                }
//
//                $return .= $footer['content'] . PHP_EOL;
//
//            } else {
//                throw new OutOfBoundsException(tr('Invalid script footer specified, should contain at least "src" or "content"'));
//            }
//        }

        return $return;
    }


    /**
     * Renders the single specified header and returns it
     *
     * @param RenderInterface|IteratorInterface|array|string|int|float|null $value
     * @param string                                                        $key
     *
     * @return string|null
     */
    public static function renderHtmlHeaderOrFooter(RenderInterface|IteratorInterface|array|string|int|float|null $value, string $key): ?string
    {
        $type = Strings::until($key, '/');
        $key  = Strings::from($key, '/');

        if (is_object($value)) {
            $value = (string) $value;
        }

        return match ($type) {
            'html'       => $value . PHP_EOL,
            'meta'       => '<meta name="' . $key . '" content="' . $value . '" />' . PHP_EOL,
            'link'       => '<link ' . Arrays::implodeWithKeys($value, ' ', '=', '"') . ' />' . PHP_EOL,
            'javascript' => '<script ' . Arrays::implodeWithKeys($value, ' ', '=', '"') . '></script>' . PHP_EOL,
        };
    }


    /**
     * Returns the language used for this page
     *
     * @return LanguageInterface
     */
    public static function getLanguage(): LanguageInterface
    {
        if (empty(static::$language_code)) {
            static::$language = Language::new()->load(Response::getLanguageCode());
        }

        return static::$language;
    }


    /**
     * Returns the language used for this page in ISO 639-2-b format
     *
     * @return string
     */
    public static function getLanguageCode(): string
    {
        if (empty(static::$language)) {
            if (PLATFORM_WEB) {
                // Get requested language
                static::$language_code = Request::detectRequestedLanguage();

            } else {
                // Get requested language from core
                static::$language_code = Core::readRegister('system', 'language');
            }
        }

        return static::$language_code;
    }


    /**
     * Returns the browser page title
     *
     * @return string|null
     */
    public static function getPageTitle(): ?string
    {
        return static::$page_title;
    }


    /**
     * Sets the browser page title
     *
     * @param Stringable|string|float|int|null $page_title
     * @param bool                             $force
     *
     * @return void
     */
    public static function setPageTitle(Stringable|string|float|int|null $page_title, bool $force = true): void
    {
        if (empty(static::$page_title) or $force) {
            static::$page_title = get_null(strip_tags((string) $page_title));
        }
    }


    /**
     * Check if this user should be forcibly being redirected to a different page
     *
     * @return void
     */
    public static function checkForceRedirect(): void
    {
        // Does this user have a forced redirect?
        if (!Session::getUserObject()->isGuest()) {
            $redirect = Session::getUserObject()->getRedirect();

            if ($redirect) {
                // Are we at the forced redirect page? If so, we can stay
                $current = (string) Url::newCurrent();

                if (Strings::until($redirect, '?') !== Strings::until($current, '?')) {
                    // We are at a different page. Should we redirect to the specified page?
                    if (!Response::skipRedirect()) {
                        // No, it is not, redirect!
                        Log::action(ts('User ":user" has a redirect to ":url", redirecting there instead', [
                            ':user' => Session::getUserObject()->getLogId(),
                            ':url'  => $redirect,
                        ]));

                        // Get URL builder object, ensure that sign-in page gets a redirect=$current_url
                        $redirect = Url::new($redirect)->makeWww();

                        if ((string) $redirect === (string) Url::new('sign-in')->makeWww()) {
                            $redirect->addRedirect($current);
                        }

                        Response::redirect($redirect);
                    }

                    Log::warning(ts('User ":user" has a redirect to ":url" which MAY NOT redirected to, ignoring redirect', [
                        ':user' => Session::getUserObject()->getLogId(),
                        ':url'  => $redirect,
                    ]));
                }
            }
        }
    }


    /*
     * Test HTTP caching headers
     *
     * Sends out 304 - Not modified header if ETag matches
     *
     * For more information, see https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
     * and https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
     */
    /**
     * Returns the redirect URL if it should not be skipped
     *
     * @param Stringable|string $redirect
     *
     * @return string|null
     */
    public static function getRedirect(Stringable|string $redirect): ?string
    {
        if (Response::skipRedirect($redirect)) {
            Log::warning(ts('Skipping redirect to ":redirect" as it is now allowed', [
                ':redirect' => $redirect,
            ]));

            return null;
        }

        return (string) $redirect;
    }


    /*
     * Test HTTP caching headers
     *
     * Sends out 304 - Not modified header if ETag matches
     *
     * For more information, see https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
     * and https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
     */
    // ???????????????????????? Was there a function here or what?!


    /**
     * Returns true if redirecting for the specified URL should be skipped
     *
     * Currently, sign-out or index pages should not be redirected to
     *
     * @param Stringable|string|null $url
     *
     * @return bool
     */
    protected static function skipRedirect(Stringable|string|null $url = null): bool
    {
        if (!$url) {
            // Default to current URL
            $url = Url::newCurrent();
        }

        // Compare URLs without queries
        $url  = Strings::until((string) $url, '?');
        $skip = [
            (string) Url::new('sign-out')->makeWww(),
        ];

        return in_array($url, $skip);
    }


    /**
     * Signs the user out of the session and optionally redirects
     *
     * @param callable|null                  $callback_after_signout
     * @param UrlInterface|string|false|null $redirect
     *
     * @return void
     */
    public static function signOut(?callable $callback_after_signout = null, UrlInterface|string|false|null $redirect = null): void
    {
        $session_redirect = Session::getPreviousPage();

        // Sign out and get the user that just signed out
        $user     = Session::signOut();
        $previous = null;

        if ($callback_after_signout) {
            // Execute the post-sign-out callback
            $callback_after_signout();
        }

        if ($redirect === false) {
            // Do NOT redirect
            return;
        }

        // Get a redirect URL and sign the user out
        if (config()->getBoolean('web.sign-out.redirect-back', true)) {
            $previous = Url::new($session_redirect);
            $test     = clone $previous;

            // Redirect URL is NOT allowed to be sign-out type URL
            if ($test->removeAllQueries()->getSource() === Url::new('signout')->makeWww()->removeAllQueries()->getSource()) {
                $previous = null;
            }
        }

        // Redirect to the requested page, or default to the sign-in page
        $redirect = $redirect ?? Url::new('signin')
                                    ->makeWww()
                                    ->addRedirect($previous)
                                    ->addQueries('email=' . $user->getEmail());

        Response::redirect($redirect);
    }


    /**
     * Instructs the client to reload the current page
     *
     * @param int      $http_code
     * @param int|null $time_delay
     *
     * @return void
     */
    #[NoReturn] public static function reload(int $http_code = 302, ?int $time_delay = null): void
    {
        Response::redirect(Url::newCurrent()->clearQueries(), $http_code, $time_delay);
    }


    /**
     * Return the specified URL with a redirect URL stored in $core->register['redirect']
     *
     * @note If no URL is specified, the current URL will be used
     *
     * @param UrlInterface|string|bool|null $url
     * @param int                           $http_code
     * @param int|null                      $time_delay
     * @param string|null                   $reason_warning
     *
     * @return never
     * @see  Url
     * @see  Url::addQueries()
     */
    #[NoReturn] public static function redirect(UrlInterface|string|bool|null $url = null, int $http_code = 302, ?int $time_delay = null, ?string $reason_warning = null): never
    {
        if (!PLATFORM_WEB) {
            throw new ResponseRedirectException(tr('Response->redirect() can only be called on web sessions'));
        }

        //        if (Session::getSignInKey()?->getAllowNavigation()) {
        //            // This session was opened using a sign-in key that does not allow navigation, we cannot target away!
        //            throw new RedirectException(tr('Cannot target sign-in session with UUID ":uuid" for user ":user" to URL ":url", this session does not allow navigation', [
        //                ':uuid' => Session::getSignInKey()->getUuid(),
        //                ':user' => Session::getUser()->getLogId(),
        //                ':url'  => $url
        //            ]));
        //        }

        // Build URL
        $_target = Url::new($url)->makeWww();

        // Make sure this user can redirect and has no forced redirect configured!
        if (Session::isInitialized()) {
            if (Session::getUserObject()->hasRedirect()) {
                if (!Session::getUserObject()->hasRedirect($_target)) {
                    // Well, THIS is a problem! We want to redirect to B, but user will always redirect back to A, so this redirect will never work
                    throw new ResponseRedirectException(tr('Will NOT redirect user ":user" to ":url", the user has forced redirect ":redirect" configured that would redirect the user away from the current required target', [
                        ':url'      => $_target,
                        ':user'     => Session::getUserObject()->getLogId(),
                        ':redirect' => Session::getUserObject()->getRedirect(),
                    ]));
                }
            }
        }

        // Protect against endless redirecting.
        if ($_target->isCurrent()) {
            // POST-requests may target to the same page as the target will change POST to GET
            if (!Request::isPostRequestMethod()) {
                // If the specified target URL was a short code like "prev" or "referer", then it was not hard coded
                // and the system could not know that the short code is the same as the current URL. Redirect to domain
                // root instead
                switch ($url) {
                    case 'prev':
                        // no break;

                    case 'previous':
                        // no break;

                    case 'referer':
                        $_target = Url::newCurrentDomainRootUrl();
                        break;

                    default:
                        if (!Session::userChanged()) {
                            // Redirecting to the same page for the same user may cause an endless redirect loop
                            throw new ResponseRedirectException(tr('Will NOT redirect user ":user" to ":url", its the same URL as the current page and the current request method is not POST', [
                                ':url'  => $_target,
                                ':user' => Session::getUserObject()->getLogId(),
                            ]));
                        }

                        $_target = Url::newCurrentDomainRootUrl();
                };
            }
        }

        if (isset_get($_GET['target'])) {
            // Add a target back query
            $_target = Url::new($_target)->makeWww()->addQueries(['target' => $_GET['target']]);
        }

        /*
         * Validate the specified http_code, must be one of
         *
         * 301 Moved Permanently
         * 302 Found
         * 303 See Other
         * 307 Temporary Redirect
         */
        switch ($http_code) {
            case 301:
                // no break
            case 302:
                // no break
            case 303:
                // no break
            case 307:
                // All valid
            case 401:
                // All valid
                break;
            default:
                throw new OutOfBoundsException(tr('Invalid HTTP code ":code" specified', [
                    ':code' => $http_code,
                ]));
        }

        Response::setHttpCode($http_code);

        if ($reason_warning) {
            Log::warning(ts('Redirecting because: :reason', [':reason' => $reason_warning]));
        }

        // Redirect with time delay
        if ($time_delay) {
            Log::action(ts('Redirecting with HTTP ":http" and ":time" seconds delay to url ":url"', [
                ':http' => $http_code,
                ':time' => $time_delay,
                ':url'  => $_target,
            ]));

            Response::setHttpCode($http_code);
            header('Refresh: ' . $time_delay . ';' . $_target, true, $http_code);

        } else {
            // Redirect immediately
            Log::action(ts('Redirecting with HTTP ":http" to url ":url"', [
                ':http' => $http_code,
                ':url'  => $_target,
            ]));

            Response::setHttpCode($http_code);
            header('Location:' . $_target, true, $http_code);
        }

        exit();
    }


    protected static function cacheTest($etag = null): bool
    {
        static::$etag = sha1(PROJECT . $_SERVER['SCRIPT_FILENAME'] . filemtime($_SERVER['SCRIPT_FILENAME']) . $etag);
        if (!config()->get('web.cache.enabled', 'auto')) {
            return false;
        }
        if (Request::isRequestType(EnumRequestTypes::ajax) or Request::isRequestType(EnumRequestTypes::api)) {
            return false;
        }
        if ((strtotime(isset_get($_SERVER['HTTP_IF_MODIFIED_SINCE'])) == filemtime($_SERVER['SCRIPT_FILENAME'])) or trim(isset_get($_SERVER['HTTP_IF_NONE_MATCH']), '') == static::$etag) {
            if (empty($core->register['flash'])) {
                // The client sent an etag which is still valid, no body (or anything else) necesary
                Response::setHttpCode(304);
                Response::sendHttpHeaders();
                exit();
            }
        }

        return true;
    }


    /**
     * Send all the specified HTTP headers
     *
     * @note The number of sent bytes does NOT include the bytes sent for the HTTP response code header
     * @return int The number of bytes sent. -1 if Response::sendHeaders() was called for the second time.
     * @throws PageNotFoundException
     */
    protected static function sendHttpHeaders(): int
    {
        if (Response::httpHeadersSent(true)) {
            // Headers already sent
            return -1;
        }

        try {
            $length = 0;

            // Set correct headers
            http_response_code(Response::getHttpCode());

            // Send all available headers
            foreach (Response::getHttpHeaders() as $header) {
                $length += strlen($header);
                header($header);
            }

            switch (Response::getHttpCode()) {
                case 200:
                    // no break
                case 301:
                    // no break
                case 302:
                    // no break
                case 304:
                    Log::success(ts('Sent HTTP headers with HTTP code ":http" using ":length" bytes', [
                        ':length' => number_format($length),
                        ':http'   => (static::$http_code ? 'HTTP ' . static::$http_code : 'HTTP 0'),
                    ]), 4);
                    break;
                default:
                    Log::warning(ts('Sent HTTP headers with HTTP code ":http" using ":length" bytes', [
                        ':length' => number_format($length),
                        ':http'   => (static::$http_code ? 'HTTP ' . static::$http_code : 'HTTP 0'),
                    ]));
            }

            static::$bytes_sent += $length;

            return $length;

        } catch (Throwable $e) {
            Notification::new()
                        ->setException($e)
                        ->setTitle(tr('Failed to send headers to client'))
                        ->send();
            // Response::sendHeaders() itself crashed. Since Response::sendHeaders() would send out http 500, and since it
            // crashed, it no longer can do this, send out the http 500 here.
            try {
                http_response_code(500);

            } catch (Throwable) {
                // Yeah, we cannot set HTTP code either, body probably has already been sent then.
            }
            throw new ResponseHeadersException(tr('Failed to send HTTP headers'), $e);
        }
    }


    /**
     * Checks if HTTP headers have already been sent and logs warnings if so
     *
     * @param bool $sending_now
     *
     * @return bool
     */
    protected static function httpHeadersSent(bool $sending_now = false): bool
    {
        if (headers_sent($file, $line)) {
            return true;
        }

        if (static::$http_headers_sent) {
            return true;
        }

        if ($sending_now) {
            static::$http_headers_sent = true;
        }

        return false;
    }


    /**
     * Returns the status code that will be sent to the client
     *
     * @return int
     */
    public static function getHttpCode(): int
    {
        return static::$http_code;
    }


    /**
     * Sets the status code that will be sent to the client
     *
     * @param int $code
     *
     * @return void
     */
    public static function setHttpCode(int $code): void
    {
        if (!$code) {
            if (static::$http_code) {
                // HTTP code was set, no code specified. Ignore this request
                return;
            }
        }

        // Validate status code
        // TODO implement
        static::$http_code = $code;
    }


    /**
     * Send the current buffer to the client
     *
     * @param bool $exit
     *
     * @return void
     * @throws ValidatorException
     * @todo Rewrite this method, its a turdy mess
     */
    public static function send(bool $exit = true): void
    {
        // Only send when on WEB platform
        if (PLATFORM_WEB) {
            // Do not send data if we are going to sign-out when the session terminates, which will cause a HTTP redirect
            if (!Session::getSignOutOnExit()) {
                // ????
                if (isset(static::$page_headers)) {
                    // TODO All this here makes zero sense? We are sending HTTP headers, but caching? Go over this, fix!
                    // Only cache if there are headers. If Response::buildHeaders() returned null this means that the headers
                    // have already been sent before, probably by a debugging function like Debug::show(). DON'T CACHE!
                    $length = Response::sendHttpHeaders();
                    Log::success(ts('Cached ":length" bytes of HTTP to client', [':length' => $length]), 3);
                }

                // Filter output out for certain HTTP codes, then send headers & output
                Response::clearOutputForHttpCodesAndMethods();
                Response::generateHttpHeaders();
                Response::sendHttpHeaders();
                Response::sendOutput();
            }
        }

        if ($exit) {
            exit();
        }
    }


    /**
     * Returns the current HTML output buffer for this page
     *
     * @param bool $clear
     *
     * @return string|null
     */
    public static function getOutput(bool $clear = true): ?string
    {
        if (ob_get_length()) {
            if ($clear) {
                return ob_get_clean();
            }

            return ob_get_contents();
        }

        // Output buffer is disabled or empty
        return null;
    }


    /**
     * Sets the output generated by the request
     *
     * @param string|null $output
     *
     * @return void
     */
    public static function setOutput(?string $output): void
    {
        ob_clean();
        Response::addOutput($output);
    }


    /**
     * Returns NULL output if the request method was HEAD (do not return output, only headers)
     *
     * @return void
     */
    protected static function clearOutputForHttpCodesAndMethods(): void
    {
        // 304 requests indicate the browser to use its local cache, send nothing
        // 429 Tell the client that it made too many requests, send nothing
        switch (Response::getHttpCode()) {
            case 304:
                // no break
            case 429:
                Response::clean();
                break;

            default:
                if (strtoupper($_SERVER['REQUEST_METHOD']) === 'HEAD') {
                    // HEAD request; do not send any HTML whatsoever
                    Response::clean();
                }
        }
    }


    /**
     * Cleans the response output buffer
     *
     * @return void
     */
    public static function clean(): void
    {
        ob_clean();
    }


    /**
     * Builds and returns all the HTTP headers
     *
     * @todo Rewrite this crap
     * @return array|null
     */
    protected static function generateHttpHeaders(): ?array
    {
        if (Response::httpHeadersSent()) {
            return null;
        }

        $headers = [];

        // Remove incorrect or insecure headers
        header_remove('Expires');
        header_remove('Pragma');

        // Create ETAG, possibly send out HTTP304 if the client sent matching ETAG
        Response::cacheEtag();

        // What to do with the PHP signature?
        switch (Core::getExposePhp()) {
            case 'limited':
                $headers[] = 'X-Powered-By: PHP';
                break;

            case 'full':
                $headers[] = 'X-Powered-By: PHP/' . phpversion();
                break;

            case 'fake':
                $headers[] = 'X-Powered-By: PHP/7.1.2';
                break;

            case 'none':
                // Remove the PHP signature
                header_remove('X-Powered-By');
                break;
        }

        // Add a powered-by header
        switch (Core::getExposePhoundation()) {
            case 'limited':
                header('Powered-By-Framework: Phoundation');
                break;

            case 'full':
                header(tr('Powered-By-Framework: Phoundation/:version"', [
                    ':version' => Core::PHOUNDATION_VERSION,
                ]));
                break;

            case 'fake':
                header(tr('Powered-By-Framework: Phoundation/:version"', [
                    ':version' => '4.11.1',
                ]));
        }

        $headers[] = 'Content-Type: ' . static::$content_type . '; charset=' . (array_get_safe(static::$page_headers, 'meta/character_set', Response::getEncoding()));
        $headers[] = 'Content-Language: ' . LANGUAGE;
        $headers[] = 'Content-Length: ' . ob_get_length();

        if (static::$http_code == 200) {
            if (empty($params['last_modified'])) {
                $headers[] = 'Last-Modified: ' . PhoDate::convert(filemtime($_SERVER['SCRIPT_FILENAME']), 'D, d M Y H:i:s', 'GMT') . ' GMT';

            } else {
                $headers[] = 'Last-Modified: ' . PhoDate::convert($params['last_modified'], 'D, d M Y H:i:s', 'GMT') . ' GMT';
            }
        }

        // Add noindex, nofollow and nosnipped headers for non-production environments and non-normal HTTP pages.
        // These pages should NEVER be indexed
        if (!Core::isProductionEnvironment() or !Request::isRequestType(EnumRequestTypes::html) or config()->getBoolean('web.noindex', false)) {
            $headers[] = 'X-Robots-Tag: noindex, nofollow, nosnippet, noarchive, noydir';
        }

        // CORS headers
        if (config()->getBoolean('security.web.cors', true) or static::$cors) {
            // Add CORS / Access-Control-Allow-.... headers
            // TODO This will cause issues if configured web.cors is not an array!
            static::$cors = array_merge(Arrays::force(config()->get('web.cors', [])), static::$cors);

            foreach (static::$cors as $key => $value) {
                switch ($key) {
                    case 'origin':
                        if ($value == '*.') {
                            // Origin is allowed from all subdomains
                            $origin = Strings::from(isset_get($_SERVER['HTTP_ORIGIN']), '://');
                            $length = strlen(isset_get($_SESSION['domain']));

                            if (substr($origin, -$length, $length) === array_get_safe($_SESSION, 'domain')) {
                                // Sub domain matches. Since CORS does not support sub domains, just show the
                                // current sub domain.
                                $value = $_SERVER['HTTP_ORIGIN'];

                            } else {
                                // Sub domain does not match. Since CORS does not support sub domains, just show no
                                // allowed origin domain at all
                                $value = '';
                            }
                        }

                        // no break

                    case 'methods':
                        // no break
                    case 'headers':
                        if ($value) {
                            $headers[] = 'Access-Control-Allow-' . Strings::capitalize($key) . ': ' . $value;
                        }
                        break;
                    default:
                        throw new HttpException(tr('Unknown CORS header ":header" specified', [
                            ':header' => $key,
                        ]));
                }
            }
        }

        // Add cache headers and store headers in the object headers list
        return Response::addHttpCacheHeaders($headers);
    }


    protected static function cacheEtag(): bool
    {
        // ETAG requires HTTP caching enabled. Ajax and API calls do not use ETAG
        if (!config()->get('web.cache.enabled', 'auto') or Request::isRequestType(EnumRequestTypes::ajax) or Request::isRequestType(EnumRequestTypes::api)) {
            static::$etag = null;

            return false;
        }

        // Create local ETAG
        static::$etag = sha1(PROJECT . $_SERVER['SCRIPT_FILENAME'] . filemtime($_SERVER['SCRIPT_FILENAME']) . Core::readRegister('etag'));

        // :TODO: Document why we are trimming with an empty character mask... It does not make sense but something tells me we are doing this for a good reason...
        if (trim((string) isset_get($_SERVER['HTTP_IF_NONE_MATCH']), '') == static::$etag) {
            if (empty($core->register['flash'])) {
                // The client sent an etag which is still valid, no body (or anything else) necessary
                http_response_code(304);
                exit();
            }
        }

        return true;
    }


    /**
     * Adds caching headers to the specified HTTP headers and returns the list
     *
     * Returns headers Cache-Control and ETag
     *
     * @param array $headers Any extra headers that are required
     *
     * @return array
     * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
     * @copyright Copyright © 2022 Sven Olaf Oostenbrink
     * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
         * @package   http
     * @see       htt_noCache()
     * @see       https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
     * @see       https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
     * @version   2.5.92: Added function and documentation
     */
    protected static function addHttpCacheHeaders(array $headers): array
    {
        if (config()->get('web.cache.enabled', 'auto') === 'auto') {
            // PHP will take care of the cache headers
            return $headers;
        }

        if (config()->get('web.cache.enabled', 'auto') === true) {
            // Place headers using phoundation algorithms
            if (!config()->get('web.cache.enabled', 'auto') or (static::$http_code != 200)) {
                // Non HTTP 200 / 304 pages should NOT have cache enabled! For example, 404, 503 etc...
                $headers[]    = 'Cache-Control: no-store, max-age=0';
                static::$etag = null;

            } else {
                // Send caching headers. Ajax, API, and admin calls do not have proxy caching
                switch (Request::getRequestType()) {
                    case EnumRequestTypes::api:
                        // no break

                    case EnumRequestTypes::ajax:
                        // no break

                    default:
                        // Session pages for specific users should not be stored on proxy servers either
                        if (!empty($_SESSION['user']['id'])) {
                            config()->get('web.cache.cacheability', 'private');
                        }

                        $headers[] = 'Cache-Control: ' . config()->get('web.cache.cacheability', 'private') . ', ' . config()->get('web.cache.expiration', 'max-age=604800') . ', ' . config()->get('web.cache.revalidation', 'must-revalidate') . config()->get('web.cache.other', 'no-transform');

                        if (!empty(static::$etag)) {
                            $headers[] = 'ETag: "' . static::$etag . '"';
                        }
                }
            }
        }

        return $headers;
    }


    /**
     * Send the generated page output to the client
     *
     * @return void
     */
    protected static function sendOutput(): void
    {
        if (Request::getAttachment()) {
            // Send download headers and send the $html payload
            FileResponse::new(Request::getTargetObject(), PhoRestrictions::newWeb())
                        ->setAttachment(true)
                        ->setData(Response::getOutput())
                        ->setFilename(basename(Request::getTargetObject()->getSource()))
                        ->send();
        }

        // Track data sizes
        $length             = Response::getOutputLength();
        static::$bytes_sent += $length;

        // Send the page to the client
        echo Response::getOutput();

        // Log how much we sent
        if ($length) {
            Log::action(ts('Sent ":length" output data to client', [
                ':length' => Numbers::getHumanReadableBytes($length),
            ]), 4);

        } else {
            Log::warning(ts('Page generated no output for client, sent "0" bytes'));
        }
    }


    /**
     * Kill this web page script process
     *
     * @note Even if $exit_message was specified, the normal shutdown functions will still be called
     *
     * @param string|null $exit_message If specified, this message will be displayed and the process will be terminated
     * @param bool        $sig_kill
     *
     * @return never
     * @todo Implement this and add required functionality
     */
    #[NoReturn] public static function exit(?string $exit_message = null, bool $sig_kill = false): never
    {
        // If something went really, really wrong...
        if ($sig_kill) {
            exit($exit_message);
        }

        // POST-requests should always show a flash message for feedback!
        if (Request::isPostRequestMethod()) {
            if (!Response::getFlashMessagesObject()->getCount()) {
                Log::warning('Detected POST request without a flash message to give user feedback on what happened with this request!');
            }
        }

        switch (Response::getHttpCode()) {
            case 200:
                // no break
            case 301:
                // no break
            case 302:
                // no break
            case 304:
                if ($exit_message) {
                    // Since we have a success HTTP code, do NOT display the message, that would mess up output
                    Log::success($exit_message);
                }

                Log::success(ts('Script(s) ":script" ended successfully with HTTP code ":http_code", sending ":sent" to client in ":time" with ":usage" peak memory usage', [
                    ':script'    => Request::getExecutedPath(true),
                    ':time'      => PhoTime::difference(STARTTIME, microtime(true), 'auto', 5),
                    ':usage'     => Numbers::getHumanReadableAndPreciseBytes(memory_get_peak_usage()),
                    ':http_code' => Response::getHttpCode(),
                    ':sent'      => Numbers::getHumanReadableAndPreciseBytes(Response::getBytesSent()),
                ]));
                break;

            default:
                if ($exit_message) {
                    echo $exit_message;
                }

                Log::error(ts('Script(s) ":script" ended with HTTP warning code ":http_code", sending ":sent" to client  in ":time" with ":usage" peak memory usage', [
                    ':script'    => Request::getExecutedPath(true),
                    ':time'      => PhoTime::difference(STARTTIME, microtime(true), 'auto', 5),
                    ':usage'     => Numbers::getHumanReadableAndPreciseBytes(memory_get_peak_usage()),
                    ':http_code' => Response::getHttpCode(),
                    ':sent'      => Numbers::getHumanReadableAndPreciseBytes(Response::getBytesSent()),
                ]));
        }

        LocalCache::logStatistics();
        Cache::logStatistics();
        Sql::logStatistics();

        // Remove subprocess run directory
        Process::deleteRunDirectory();

        if (Log::syslogIsOpen()) {
            // Close the syslog
            closelog();
        }

        // Normal kill request
        Log::action(ts('Killing web page process'), 2);
        exit();
    }


    /**
     * Returns the current length HTML output buffer for this page
     *
     * @return int
     */
    public static function getOutputLength(): int
    {
        return (int) ob_get_length();
    }


    /**
     * Adds output generated by the request to the (possibly already existing) current output
     *
     * @param string|null $output
     *
     * @return void
     */
    public static function addOutput(?string $output): void
    {
        echo $output;
    }


    /**
     * Send the required headers to ensure that the page will not be cached ever
     *
     * @return void
     * @copyright Copyright © 2022 Sven Olaf Oostenbrink
     * @license   http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
     * @package   http
     * @see       Http::cache()
     * @version   2.5.92: Added function and documentation
     * @author    Sven Olaf Oostenbrink <so.oostenbrink@gmail.com>
     */
    protected static function sendNoCacheHttpHeaders(): void
    {
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0', true);
        header('Cache-Control: post-check=0, pre-check=0', true);
        header('Pragma: no-cache', true);
        header('Expires: Wed, 10 Jan 2000 07:00:00 GMT', true);
    }


    /**
     * Returns the upload handlers object for this response
     *
     * @return UploadHandlersInterface
     */
    public static function getFileUploadHandlersObject(): UploadHandlersInterface
    {
        return Request::getFileUploadHandlersObject();
    }


    /**
     * Adds JavaScript object to the "window.onbeforeunload" event that will be executed upon leaving the page
     *
     * @param Script $script
     *
     * @return void
     */
    public static function addBeforeUnloadScriptObject(Script $script): void
    {
        $script->setJavascriptWrapper(EnumJavascriptWrappers::onbeforeunload);

        switch ($script->getAttach()) {
            case EnumAttachJavascript::header:
            case EnumAttachJavascript::footer:
                break;

            default:
                $script->setAttach(EnumAttachJavascript::footer);
        }

        $script->render();
    }


    /**
     * Returns the encoding used by Phoundation
     *
     * @return string
     */
    public static function getEncoding(): string
    {
        return config()->getString('languages.encoding.character-set', 'UTF-8');
    }


    /**
     * Returns true if the specified encoding is the same as the encoding used by Phoundation
     *
     * @param string $encoding
     *
     * @return bool
     */
    public static function hasEncoding(string $encoding): bool
    {
        return Response::getEncoding() === $encoding;
    }
}
